# Ⅱ. 따릉이 이용량 변화 분석

In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
import missingno as msno
import warnings
warnings.filterwarnings('ignore')

mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'NanumGothic'

import json
import folium

geo_path = 'C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/seoul_municipalities_geo_simple.json'
geo_str = json.load(open(geo_path, encoding = 'utf-8'))

## 데이터 로드

In [2]:
df = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/정리 데이터/공공자전거 대여소별 월별 이용정보.csv', 
                 parse_dates = ['기준일자'])
df

      대여소위치                 대여소명    기준일자  대여건수   반납건수
0       마포구              서교동 사거리  201801   355  422.0
1       NaN          더샵스타시티 C동 앞  201801   287  256.0
2       양천구         서울시 도로환경관리센터  201801     0    4.0
3       NaN            신자초교입구교차로  201801   370  368.0
4       양천구                 으뜸공원  201801     0    1.0
...     ...                  ...     ...   ...    ...
72085   중랑구     4811. 한양수자인아파트 앞  202106   260    NaN
72086   중랑구       4812. 묵동 이마트 앞  202106  1305    NaN
72087   중랑구      4813. 망우로 버거킹 앞  202106  1624    NaN
72088   중랑구     4815. 중랑데시앙플렉스 앞  202106   218    NaN
72089   중랑구  4819. 면목동 새싹어린이공원 앞  202106   661    NaN

[72090 rows x 5 columns]

In [3]:
df.isnull().sum()

대여소위치      495
대여소명         0
기준일자         0
대여건수         0
반납건수     26530
dtype: int64

In [4]:
temp = df['대여소명'].str.split('.')
df['대여소명'] = temp.str.get(-1)
df

      대여소위치            대여소명    기준일자  대여건수   반납건수
0       마포구         서교동 사거리  201801   355  422.0
1       NaN     더샵스타시티 C동 앞  201801   287  256.0
2       양천구    서울시 도로환경관리센터  201801     0    4.0
3       NaN       신자초교입구교차로  201801   370  368.0
4       양천구            으뜸공원  201801     0    1.0
...     ...             ...     ...   ...    ...
72085   중랑구      한양수자인아파트 앞  202106   260    NaN
72086   중랑구        묵동 이마트 앞  202106  1305    NaN
72087   중랑구       망우로 버거킹 앞  202106  1624    NaN
72088   중랑구      중랑데시앙플렉스 앞  202106   218    NaN
72089   중랑구   면목동 새싹어린이공원 앞  202106   661    NaN

[72090 rows x 5 columns]

In [5]:
df['대여소명'] = df['대여소명'].str.strip()

In [6]:
df

      대여소위치           대여소명    기준일자  대여건수   반납건수
0       마포구        서교동 사거리  201801   355  422.0
1       NaN    더샵스타시티 C동 앞  201801   287  256.0
2       양천구   서울시 도로환경관리센터  201801     0    4.0
3       NaN      신자초교입구교차로  201801   370  368.0
4       양천구           으뜸공원  201801     0    1.0
...     ...            ...     ...   ...    ...
72085   중랑구     한양수자인아파트 앞  202106   260    NaN
72086   중랑구       묵동 이마트 앞  202106  1305    NaN
72087   중랑구      망우로 버거킹 앞  202106  1624    NaN
72088   중랑구     중랑데시앙플렉스 앞  202106   218    NaN
72089   중랑구  면목동 새싹어린이공원 앞  202106   661    NaN

[72090 rows x 5 columns]

In [25]:
df = df.dropna(subset = ['대여소위치'])
df

      대여소위치            대여소명    기준일자  대여건수   반납건수
0       마포구         서교동 사거리  201801   355  422.0
2       양천구    서울시 도로환경관리센터  201801     0    4.0
4       양천구            으뜸공원  201801     0    1.0
5       양천구        목동2단지 상가  201801     0    1.0
6       광진구  자양사거리 광진아크로텔 앞  201801   349  328.0
...     ...             ...     ...   ...    ...
72085   중랑구      한양수자인아파트 앞  202106   260    NaN
72086   중랑구        묵동 이마트 앞  202106  1305    NaN
72087   중랑구       망우로 버거킹 앞  202106  1624    NaN
72088   중랑구      중랑데시앙플렉스 앞  202106   218    NaN
72089   중랑구   면목동 새싹어린이공원 앞  202106   661    NaN

[71595 rows x 5 columns]

In [26]:
df.to_excel('./공공자전거 대여소별 월별 이용정보.xlsx', index = False)