# 공공자전거 대여이력 정보 데이터 병합

In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
import missingno as msno
import warnings
warnings.filterwarnings('ignore')

mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'NanumGothic'

import json
import folium

geo_path = 'C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/seoul_municipalities_geo_simple.json'
geo_str = json.load(open(geo_path, encoding = 'utf-8'))

In [10]:
dirpath = 'C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보'
files = os.listdir(dirpath)
files

['공공자전거 대여이력 정보_201912.csv',
 '공공자전거 대여이력 정보_2020.01.csv',
 '공공자전거 대여이력 정보_2020.02.csv',
 '공공자전거 대여이력 정보_2020.03.csv',
 '공공자전거 대여이력 정보_2020.04.csv',
 '공공자전거 대여이력 정보_2020.06.csv',
 '공공자전거 대여이력 정보_2020.07_08.csv',
 '공공자전거 대여이력 정보_2020.09.csv',
 '공공자전거 대여이력 정보_2020.10.csv',
 '공공자전거 대여이력 정보_2020.11.csv',
 '공공자전거 대여이력 정보_2020.12.csv',
 '공공자전거 대여이력 정보_2021.01.csv',
 '공공자전거 대여이력 정보_2021.02.csv',
 '공공자전거 대여이력 정보_2021.03.csv',
 '공공자전거 대여이력 정보_2021.04.csv',
 '공공자전거 대여이력 정보_2021.05.csv',
 '공공자전거 대여이력 정보_2021.06.csv',
 '공공자전거_대여이력정보_2020.05.csv',
 '서울특별시 공공자전거 대여이력 정보_2018년_1분기1.csv',
 '서울특별시 공공자전거 대여이력 정보_2018년_2분기_1.csv',
 '서울특별시 공공자전거 대여이력 정보_2018년_2분기_2.csv',
 '서울특별시 공공자전거 대여이력 정보_2018년_2분기_3.csv',
 '서울특별시 공공자전거 대여이력 정보_2018년_2분기_4.csv',
 '서울특별시 공공자전거 대여정보_201807_01.xlsx',
 '서울특별시 공공자전거 대여정보_201807_02.xlsx',
 '서울특별시 공공자전거 대여정보_201808.xlsx',
 '서울특별시 공공자전거 대여정보_201809_1.xlsx',
 '서울특별시 공공자전거 대여정보_201809_2.xlsx',
 '서울특별시 공공자전거 대여정보_201810_01.xlsx',
 '서울특별시 공공자전거 대여정보_201810_02.xlsx',
 '서울특별시 공공자전거 대여정보_201811.xlsx',
 '서울특별시 공공자전거 대여정보_201812.csv',
 '서울특별시 공공자전거 대여정보_201901.csv',
 '서울특별시 공공자전거 대여정보_201902.csv',
 '서울특별시 공공자전거 대여정보_201903.csv',
 '서울특별시 공공자전거 대여정보_201904.csv',
 '서울특별시 공공자전거 대여정보_201905.csv',
 '서울특별시 공공자전거 대여정보_201906_1.csv',
 '서울특별시 공공자전거 대여정보_201906_2.csv',
 '서울특별시 공공자전거 대여정보_201906_3.csv',
 '서울특별시 공공자전거 대여정보_201907_1.csv',
 '서울특별시 공공자전거 대여정보_201907_2.csv',
 '서울특별시 공공자전거 대여정보_201907_3.csv',
 '서울특별시 공공자전거 대여정보_201908_1.csv',
 '서울특별시 공공자전거 대여정보_201908_2.csv',
 '서울특별시 공공자전거 대여정보_201908_3.csv',
 '서울특별시 공공자전거 대여정보_201909_1.csv',
 '서울특별시 공공자전거 대여정보_201909_2.csv',
 '서울특별시 공공자전거 대여정보_201909_3.csv',
 '서울특별시 공공자전거 대여정보_201910_1.csv',
 '서울특별시 공공자전거 대여정보_201910_2.csv',
 '서울특별시 공공자전거 대여정보_201910_3.csv',
 '서울특별시 공공자전거 대여정보_201911_1.csv',
 '서울특별시 공공자전거 대여정보_201911_2.csv']

In [13]:
data1 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_201912.csv', engine = 'python')
data1

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-07756,2019-12-01 00:00:09,512,뚝섬역 1번 출구 옆,6,2019-12-01 00:03:14,512,뚝섬역 1번 출구 옆,6,2,0.0
1,SPB-02716,2019-12-01 00:01:51,1151,마곡역1번출구,18,2019-12-01 00:03:41,1168,마곡엠밸리10단지 앞,10,1,380.0
2,SPB-14606,2019-12-01 00:00:05,1244,문정 법조단지8,7,2019-12-01 00:04:52,2615,테라타워2,15,4,940.0
3,SPB-16682,2019-12-01 00:01:24,908,구산역 4번출구,4,2019-12-01 00:04:57,906,연신내역 5번출구150M 아래,6,3,560.0
4,SPB-23119,2019-12-01 00:00:07,2616,거여동 사거리,8,2019-12-01 00:05:02,1227,거여역 8번출구 뒤,3,4,570.0
...,...,...,...,...,...,...,...,...,...,...,...
849189,SPB-18675,2019-12-31 23:38:14,430,KEB하나은행 장충동지점,5,2020-01-01 01:58:18,430,KEB하나은행 장충동지점,7,135,3770.0
849190,SPB-13564,2019-12-31 16:08:16,1673,노원역?5번출구,6,2020-01-01 02:32:10,1636,백병원 사거리 농협은행 앞,8,623,620.0
849191,SPB-11208,2019-12-31 21:11:33,2307,압구정 한양 3차 아파트,5,2020-01-01 02:47:59,3534,건대입구역 5번출구 뒤,6,80,3820.0
849192,SPB-23946,2019-12-31 23:59:58,327,낙원상가 옆,1,2020-01-01 03:02:20,327,낙원상가 옆,1,174,11890.0
849193,SPB-17909,2019-12-31 20:11:43,500,어린이대공원역 3번출구 앞,9,2020-01-01 11:00:47,3542,래미안 구의파크 스위트,9,8,1510.0

In [103]:
data1 = data1.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data1.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-07756,2019-12-01 00:00:09,512,뚝섬역 1번 출구 옆,6,2019-12-01 00:03:14,512,뚝섬역 1번 출구 옆,6,2,0.0
1,SPB-02716,2019-12-01 00:01:51,1151,마곡역1번출구,18,2019-12-01 00:03:41,1168,마곡엠밸리10단지 앞,10,1,380.0
2,SPB-14606,2019-12-01 00:00:05,1244,문정 법조단지8,7,2019-12-01 00:04:52,2615,테라타워2,15,4,940.0
3,SPB-16682,2019-12-01 00:01:24,908,구산역 4번출구,4,2019-12-01 00:04:57,906,연신내역 5번출구150M 아래,6,3,560.0
4,SPB-23119,2019-12-01 00:00:07,2616,거여동 사거리,8,2019-12-01 00:05:02,1227,거여역 8번출구 뒤,3,4,570.0

In [104]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 849194 entries, 0 to 849193
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    849194 non-null  object
 1   대여일시     849194 non-null  object
 2   대여대여소번호  849194 non-null  int64
 3   대여대여소명   849194 non-null  object
 4   대여거치대    849194 non-null  int64
 5   반납일시     849194 non-null  object
 6   반납대여소번호  849194 non-null  int64
 7   반납대여소명   849194 non-null  object
 8   반납거치대    849194 non-null  int64
 9   이용시간     849194 non-null  int64
 10  이용거리     849194 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 71.3+ MB

In [105]:
data1.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [106]:
#data1.to_excel('./공공자전거 대여이력 정보_201912.xlsx', index = False)

In [94]:
data2 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.01.csv', engine = 'python', error_bad_lines=False)
data2

Skipping line 47104: ',' expected after '"'
Skipping line 62482: ',' expected after '"'
Skipping line 63439: ',' expected after '"'
Skipping line 80714: ',' expected after '"'
Skipping line 203730: ',' expected after '"'
Skipping line 217138: ',' expected after '"'
Skipping line 251731: ',' expected after '"'
Skipping line 309395: ',' expected after '"'
Skipping line 331500: ',' expected after '"'
Skipping line 489051: ',' expected after '"'
Skipping line 519797: ',' expected after '"'
Skipping line 552431: ',' expected after '"'
Skipping line 554351: ',' expected after '"'
Skipping line 732885: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-04061,2020-01-01 00:01:04,429,송도병원,2,2020-01-01 00:04:21,372,약수역 3번출구 뒤,8,2,0.0
1,SPB-06686,2020-01-01 00:02:53,1637,KT 노원점 건물 앞,14,2020-01-01 00:04:48,1656,중앙하이츠 아파트 입구,9,1,350.0
2,SPB-15937,2020-01-01 00:01:21,1924,삼부르네상스파크빌,10,2020-01-01 00:05:51,1955,디지털입구 교차로,7,4,800.0
3,SPB-14805,2020-01-01 00:03:12,437,대흥역 1번출구,1,2020-01-01 00:05:54,126,서강대 후문 옆,18,2,0.0
4,SPB-09038,2020-01-01 00:01:11,1168,마곡엠밸리10단지 앞,5,2020-01-01 00:05:57,1152,마곡역교차로,2,4,660.0
...,...,...,...,...,...,...,...,...,...,...,...
765281,SPB-13688,2020-01-31 23:45:51,178,증산3교 앞,3,2020-01-31 23:59:50,194,증산교 앞,3,13,0.0
765282,SPB-22994,2020-01-31 23:35:57,135,명물길 원형무대 앞,4,2020-01-31 23:59:51,188,홍은동 정원여중 입구,10,21,3670.0
765283,SPB-08546,2020-01-31 23:41:46,237,보라매 두산위브 건너편,17,2020-01-31 23:59:56,2169,봉천역 2번출구,2,17,3140.0
765284,SPB-13247,2020-01-31 23:52:34,2377,수서역 5번출구 뒤,4,2020-01-31 23:59:58,1250,문정2동 주민센터,1,6,860.0
765285,SPB-06034,2020-01-31 23:55:48,363,신설동역 11번출구 뒤,3,2020-01-31 23:59:59,361,동묘앞역 1번출구 뒤,6,3,700.0

- 데이터에 에러가 난 행이 여러개 있어서 파일이 안열려서 데이터 에러난 행은 제거하고 불러옴

In [107]:
data2 = data2.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data2.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-04061,2020-01-01 00:01:04,429,송도병원,2,2020-01-01 00:04:21,372,약수역 3번출구 뒤,8,2,0.0
1,SPB-06686,2020-01-01 00:02:53,1637,KT 노원점 건물 앞,14,2020-01-01 00:04:48,1656,중앙하이츠 아파트 입구,9,1,350.0
2,SPB-15937,2020-01-01 00:01:21,1924,삼부르네상스파크빌,10,2020-01-01 00:05:51,1955,디지털입구 교차로,7,4,800.0
3,SPB-14805,2020-01-01 00:03:12,437,대흥역 1번출구,1,2020-01-01 00:05:54,126,서강대 후문 옆,18,2,0.0
4,SPB-09038,2020-01-01 00:01:11,1168,마곡엠밸리10단지 앞,5,2020-01-01 00:05:57,1152,마곡역교차로,2,4,660.0

In [108]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765286 entries, 0 to 765285
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    765286 non-null  object
 1   대여일시     765286 non-null  object
 2   대여대여소번호  765286 non-null  int64
 3   대여대여소명   765286 non-null  object
 4   대여거치대    765286 non-null  int64
 5   반납일시     765286 non-null  object
 6   반납대여소번호  765286 non-null  int64
 7   반납대여소명   765286 non-null  object
 8   반납거치대    765286 non-null  int64
 9   이용시간     765286 non-null  int64
 10  이용거리     765286 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 64.2+ MB

In [109]:
data2.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [110]:
#data2.to_excel('./공공자전거 대여이력 정보_2020.01.xlsx', index = False)

In [95]:
data3 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.02.csv', engine = 'python', error_bad_lines=False)
data3

Skipping line 11752: ',' expected after '"'
Skipping line 35744: ',' expected after '"'
Skipping line 49176: ',' expected after '"'
Skipping line 61684: ',' expected after '"'
Skipping line 195254: ',' expected after '"'
Skipping line 208691: ',' expected after '"'
Skipping line 211582: ',' expected after '"'
Skipping line 314316: ',' expected after '"'
Skipping line 362289: ',' expected after '"'
Skipping line 402615: ',' expected after '"'
Skipping line 414158: ',' expected after '"'
Skipping line 521722: ',' expected after '"'
Skipping line 525558: ',' expected after '"'
Skipping line 618634: ',' expected after '"'
Skipping line 645514: ',' expected after '"'
Skipping line 733684: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22727,2020-01-31 23:40:04,183,하늘채코오롱아파트 건너편,15,2020-02-01 00:00:02,113,홍대입구역 2번출구 앞,10,19,2430.0
1,SPB-21546,2020-01-31 22:05:17,3106,홍남교 두바퀴쉼터,6,2020-02-01 00:00:06,3106,홍남교 두바퀴쉼터,7,105,860.0
2,SPB-24679,2020-01-31 23:55:01,1435,능산삼거리,8,2020-02-01 00:00:08,1430,중랑구청,19,4,720.0
3,SPB-20312,2020-01-31 23:54:06,1656,중앙하이츠 아파트 입구,2,2020-02-01 00:00:11,1625,상계역(4번출구),16,5,660.0
4,SPB-21946,2020-01-31 23:41:05,237,보라매 두산위브 건너편,1,2020-02-01 00:00:11,2169,봉천역 2번출구,6,19,2890.0
...,...,...,...,...,...,...,...,...,...,...,...
734127,SPB-24279,2020-02-29 23:36:05,657,동대문롯데캐슬아파트 앞,5,2020-02-29 23:59:46,559,왕십리역 4번 출구 건너편,1,23,3580.0
734128,SPB-24344,2020-02-29 23:45:29,1340,광운초등학교 앞,2,2020-02-29 23:59:47,1601,석계역 문화광장 내 자전거 보관소,17,13,1710.0
734129,SPB-17675,2020-02-29 23:41:15,3529,어린이대공원정문,10,2020-02-29 23:59:51,3535,중곡사거리(국민은행),2,18,1970.0
734130,SPB-19051,2020-02-29 23:53:02,2294,두상빌딩 앞,2,2020-02-29 23:59:54,2255,시민의숲역 1번출구 옆,6,6,360.0
734131,SPB-23133,2020-02-29 23:56:29,1112,마곡엠밸리4단지 정문,6,2020-02-29 23:59:56,1113,서남환경공원 버스정류장,12,3,530.0

In [111]:
data3 = data3.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data3.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22727,2020-01-31 23:40:04,183,하늘채코오롱아파트 건너편,15,2020-02-01 00:00:02,113,홍대입구역 2번출구 앞,10,19,2430.0
1,SPB-21546,2020-01-31 22:05:17,3106,홍남교 두바퀴쉼터,6,2020-02-01 00:00:06,3106,홍남교 두바퀴쉼터,7,105,860.0
2,SPB-24679,2020-01-31 23:55:01,1435,능산삼거리,8,2020-02-01 00:00:08,1430,중랑구청,19,4,720.0
3,SPB-20312,2020-01-31 23:54:06,1656,중앙하이츠 아파트 입구,2,2020-02-01 00:00:11,1625,상계역(4번출구),16,5,660.0
4,SPB-21946,2020-01-31 23:41:05,237,보라매 두산위브 건너편,1,2020-02-01 00:00:11,2169,봉천역 2번출구,6,19,2890.0

In [112]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734132 entries, 0 to 734131
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    734132 non-null  object
 1   대여일시     734132 non-null  object
 2   대여대여소번호  734132 non-null  int64
 3   대여대여소명   734132 non-null  object
 4   대여거치대    734132 non-null  int64
 5   반납일시     734132 non-null  object
 6   반납대여소번호  734132 non-null  int64
 7   반납대여소명   734132 non-null  object
 8   반납거치대    734132 non-null  int64
 9   이용시간     734132 non-null  int64
 10  이용거리     734132 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 61.6+ MB

In [113]:
data3.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [114]:
#data3.to_excel('./공공자전거 대여이력 정보_2020.02.xlsx', index = False)

In [96]:
data4 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.03.csv', engine = 'python', error_bad_lines=False)
data4

Skipping line 24492: ',' expected after '"'
Skipping line 56167: ',' expected after '"'
Skipping line 78291: ',' expected after '"'
Skipping line 95545: ',' expected after '"'
Skipping line 103229: ',' expected after '"'
Skipping line 209898: ',' expected after '"'
Skipping line 224260: ',' expected after '"'
Skipping line 253985: ',' expected after '"'
Skipping line 397647: ',' expected after '"'
Skipping line 434111: ',' expected after '"'
Skipping line 473471: ',' expected after '"'
Skipping line 511827: ',' expected after '"'
Skipping line 559732: ',' expected after '"'
Skipping line 577058: ',' expected after '"'
Skipping line 622214: ',' expected after '"'
Skipping line 685554: ',' expected after '"'
Skipping line 746022: ',' expected after '"'
Skipping line 805426: ',' expected after '"'
Skipping line 914470: ',' expected after '"'
Skipping line 917360: ',' expected after '"'
Skipping line 956590: ',' expected after '"'
Skipping line 1156081: ',' expected after '"'
Skipping line 1202065: ',' expected after '"'
Skipping line 1230912: ',' expected after '"'
Skipping line 1271969: ',' expected after '"'
Skipping line 1351501: ',' expected after '"'
Skipping line 1391717: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-18902,2020-02-29 23:18:35,358,성대입구 사거리,10,2020-03-01 00:00:02,347,동대문역사문화공원역 9번출구 앞,18,39,5180.0
1,SPB-15556,2020-02-29 23:46:45,641,용두역 4번출구,7,2020-03-01 00:00:06,559,왕십리역 4번 출구 건너편,9,13,0.0
2,SPB-14831,2020-02-29 23:06:15,2335,3호선 매봉역 3번출구앞,1,2020-03-01 00:00:08,2404,대모산입구역 4번 출구 앞,2,53,4040.0
3,SPB-23136,2020-02-29 23:44:11,1913,구로리공원,9,2020-03-01 00:00:09,1920,서울미래초등학교 사거리,4,15,1760.0
4,SPB-22450,2020-02-29 23:02:12,2265,이수고가차도 남단,6,2020-03-01 00:00:15,2220,반포본동 주민센터 앞,6,55,7760.0
...,...,...,...,...,...,...,...,...,...,...,...
1475699,SPB-17326,2020-03-31 23:23:03,2173,당곡사거리,2,2020-03-31 23:59:47,2183,동방1교,8,36,0.0
1475700,SPB-14489,2020-03-31 21:59:12,1506,강북문화예술회관,16,2020-03-31 23:59:51,1540,가오리역,10,120,0.0
1475701,SPB-22226,2020-03-31 22:21:28,1722,창동청소년수련관,2,2020-03-31 23:59:52,1716,하나로마트 창동점,3,96,73850.0
1475702,SPB-19223,2020-03-31 23:53:03,1327,상월곡역 3번출구,3,2020-03-31 23:59:55,1332,석계역 5번출구 건너편,2,6,1420.0
1475703,SPB-10768,2020-03-31 23:44:09,1291,서울체육고등학교 앞,6,2020-03-31 23:59:56,1209,잠실나루역 (2번 출구 쪽),4,15,2730.0

In [115]:
data4 = data4.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data4.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-18902,2020-02-29 23:18:35,358,성대입구 사거리,10,2020-03-01 00:00:02,347,동대문역사문화공원역 9번출구 앞,18,39,5180.0
1,SPB-15556,2020-02-29 23:46:45,641,용두역 4번출구,7,2020-03-01 00:00:06,559,왕십리역 4번 출구 건너편,9,13,0.0
2,SPB-14831,2020-02-29 23:06:15,2335,3호선 매봉역 3번출구앞,1,2020-03-01 00:00:08,2404,대모산입구역 4번 출구 앞,2,53,4040.0
3,SPB-23136,2020-02-29 23:44:11,1913,구로리공원,9,2020-03-01 00:00:09,1920,서울미래초등학교 사거리,4,15,1760.0
4,SPB-22450,2020-02-29 23:02:12,2265,이수고가차도 남단,6,2020-03-01 00:00:15,2220,반포본동 주민센터 앞,6,55,7760.0

In [116]:
data4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1475704 entries, 0 to 1475703
Data columns (total 11 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   자전거번호    1475704 non-null  object
 1   대여일시     1475704 non-null  object
 2   대여대여소번호  1475704 non-null  int64
 3   대여대여소명   1475704 non-null  object
 4   대여거치대    1475704 non-null  int64
 5   반납일시     1475704 non-null  object
 6   반납대여소번호  1475704 non-null  int64
 7   반납대여소명   1475704 non-null  object
 8   반납거치대    1475704 non-null  int64
 9   이용시간     1475704 non-null  int64
 10  이용거리     1475704 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 123.8+ MB

In [117]:
data4.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [120]:
#data4.to_csv('./공공자전거 대여이력 정보_2020.03.csv', index = False, encoding ='cp949')

In [97]:
data5 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.04.csv', engine = 'python', error_bad_lines=False)
data5

Skipping line 448: ',' expected after '"'
Skipping line 9118: ',' expected after '"'
Skipping line 149428: ',' expected after '"'
Skipping line 168680: ',' expected after '"'
Skipping line 280949: ',' expected after '"'
Skipping line 382714: ',' expected after '"'
Skipping line 393262: ',' expected after '"'
Skipping line 621417: ',' expected after '"'
Skipping line 690704: ',' expected after '"'
Skipping line 728243: ',' expected after '"'
Skipping line 729200: ',' expected after '"'
Skipping line 790806: ',' expected after '"'
Skipping line 795604: ',' expected after '"'
Skipping line 965294: ',' expected after '"'
Skipping line 1050034: ',' expected after '"'
Skipping line 1050995: ',' expected after '"'
Skipping line 1189261: ',' expected after '"'
Skipping line 1213377: ',' expected after '"'
Skipping line 1219144: ',' expected after '"'
Skipping line 1232593: ',' expected after '"'
Skipping line 1382615: ',' expected after '"'
Skipping line 1393279: ',' expected after '"'
Skipping line 1459274: ',' expected after '"'
Skipping line 1512641: ',' expected after '"'
Skipping line 1567026: ',' expected after '"'
Skipping line 1643491: ',' expected after '"'
Skipping line 1660872: ',' expected after '"'
Skipping line 1748834: ',' expected after '"'
Skipping line 1768295: ',' expected after '"'
Skipping line 1922585: ',' expected after '"'
Skipping line 1943964: ',' expected after '"'
Skipping line 1985535: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-04779,2020-03-31 22:46:39,1722,창동청소년수련관,1,2020-04-01 00:00:00,1716,하나로마트 창동점,1,72,0.0
1,SPB-19055,2020-03-31 23:54:27,806,전자랜드 본관 앞,6,2020-04-01 00:00:11,844,이촌2동 동원베네스트 아파트 앞,11,5,980.0
2,SPB-23457,2020-03-31 23:38:26,1352,e 편한세상 보문아파트 내,1,2020-04-01 00:00:11,375,다산 어린이공원,4,22,2590.0
3,SPB-11094,2020-03-31 23:26:56,1355,보문2교,15,2020-04-01 00:00:12,1351,안암2교 옆,3,33,6750.0
4,SPB-22342,2020-03-31 23:57:22,2316,삼성역 8번출구,1,2020-04-01 00:00:13,2348,포스코사거리(기업은행),11,2,390.0
...,...,...,...,...,...,...,...,...,...,...,...
2085457,SPB-30310,2020-04-30 23:34:14,249,여의도중학교 옆,0,2020-04-30 23:59:57,249,여의도중학교 옆,0,26,0.0
2085458,SPB-33363,2020-04-30 23:27:38,553,중곡 성원APT 앞,0,2020-04-30 23:59:57,1425,용마문화복지센터,0,32,0.0
2085459,SPB-31303,2020-04-30 23:10:36,2102,봉림교 교통섬,0,2020-04-30 23:59:57,2102,봉림교 교통섬,0,49,0.0
2085460,SPB-33912,2020-04-30 22:50:08,548,자양나들목,0,2020-04-30 23:59:58,627,장안동삼거리 교통섬,0,70,0.0
2085461,SPB-32504,2020-04-30 22:53:06,1610,화랑대역 2번출구 앞,0,2020-04-30 23:59:58,1610,화랑대역 2번출구 앞,0,67,0.0

In [121]:
data5 = data5.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data5.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-04779,2020-03-31 22:46:39,1722,창동청소년수련관,1,2020-04-01 00:00:00,1716,하나로마트 창동점,1,72,0.0
1,SPB-19055,2020-03-31 23:54:27,806,전자랜드 본관 앞,6,2020-04-01 00:00:11,844,이촌2동 동원베네스트 아파트 앞,11,5,980.0
2,SPB-23457,2020-03-31 23:38:26,1352,e 편한세상 보문아파트 내,1,2020-04-01 00:00:11,375,다산 어린이공원,4,22,2590.0
3,SPB-11094,2020-03-31 23:26:56,1355,보문2교,15,2020-04-01 00:00:12,1351,안암2교 옆,3,33,6750.0
4,SPB-22342,2020-03-31 23:57:22,2316,삼성역 8번출구,1,2020-04-01 00:00:13,2348,포스코사거리(기업은행),11,2,390.0

In [122]:
data5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2085462 entries, 0 to 2085461
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 175.0+ MB

In [123]:
data5.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [124]:
#data5.to_csv('./공공자전거 대여이력 정보_2020.04.csv', index = False, encoding ='cp949')

In [33]:
data6 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.06.csv', engine = 'python')
data6

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-36260,2020-06-01 00:00:35,1681,현대6차 아파트,0,2020-06-01 00:05:24,1665,양지근린공원앞,0,5,0.00
1,SPB-36146,2020-06-01 00:01:47,816,신용산역 6번출구 앞,0,2020-06-01 00:05:54,829,베르가모앞,0,4,0.00
2,SPB-33273,2020-06-01 00:03:05,1050,둔촌역 3번 출입구,0,2020-06-01 00:05:59,1078,둔촌사거리,0,3,0.00
3,SPB-35969,2020-06-01 00:04:31,1209,잠실나루역 (2번 출구 쪽),0,2020-06-01 00:06:10,1209,잠실나루역 (2번 출구 쪽),0,2,0.00
4,SPB-30703,2020-06-01 00:00:46,1132,등촌역 7번출구,0,2020-06-01 00:06:53,1169,염창역 1번 출구,0,6,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2725232,SPB-12680,2020-06-30 13:01:33,1346,길음8골어린이공원 옆,1,2020-07-01 02:50:27,1347,길음래미안아파트817동 상가 앞,1,15,7230.00
2725233,SPB-40800,2020-06-30 23:56:30,107,신한은행 서교동금융센터점 앞,0,2020-07-01 07:41:32,438,성산2-1 공영주차장,0,465,0.00
2725234,SPB-32402,2020-06-30 16:45:32,1956,도야미리숯불갈비 앞,0,2020-07-01 08:04:52,1956,도야미리숯불갈비 앞,0,919,39786.76
2725235,SPB-38526,2020-06-30 23:23:38,703,오목교역 7번출구 앞,0,2020-07-01 08:37:15,734,신트리공원 입구,0,554,0.00
2725236,SPB-21598,2020-06-30 23:52:23,1008,암사역 3번출구(국민은행앞),4,2020-07-01 09:07:47,1008,암사역 3번출구(국민은행앞),4,42,310.00

In [125]:
data6 = data6.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data6.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-36260,2020-06-01 00:00:35,1681,현대6차 아파트,0,2020-06-01 00:05:24,1665,양지근린공원앞,0,5,0.0
1,SPB-36146,2020-06-01 00:01:47,816,신용산역 6번출구 앞,0,2020-06-01 00:05:54,829,베르가모앞,0,4,0.0
2,SPB-33273,2020-06-01 00:03:05,1050,둔촌역 3번 출입구,0,2020-06-01 00:05:59,1078,둔촌사거리,0,3,0.0
3,SPB-35969,2020-06-01 00:04:31,1209,잠실나루역 (2번 출구 쪽),0,2020-06-01 00:06:10,1209,잠실나루역 (2번 출구 쪽),0,2,0.0
4,SPB-30703,2020-06-01 00:00:46,1132,등촌역 7번출구,0,2020-06-01 00:06:53,1169,염창역 1번 출구,0,6,0.0

In [126]:
data6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2725237 entries, 0 to 2725236
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 228.7+ MB

In [128]:
data6.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [129]:
#data6.to_csv('./공공자전거 대여이력 정보_2020.06.csv', index = False, encoding ='cp949')

In [98]:
data7 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.07_08.csv', engine = 'python', error_bad_lines=False)
data7

Skipping line 18477: ',' expected after '"'
Skipping line 105731: ',' expected after '"'
Skipping line 109615: ',' expected after '"'
Skipping line 227980: ',' expected after '"'
Skipping line 230905: ',' expected after '"'
Skipping line 237713: ',' expected after '"'
Skipping line 278455: ',' expected after '"'
Skipping line 465524: ',' expected after '"'
Skipping line 474228: ',' expected after '"'
Skipping line 480994: ',' expected after '"'
Skipping line 527570: ',' expected after '"'
Skipping line 572302: ',' expected after '"'
Skipping line 697580: ',' expected after '"'
Skipping line 913247: ',' expected after '"'
Skipping line 987481: ',' expected after '"'
Skipping line 1056760: ',' expected after '"'
Skipping line 1066381: ',' expected after '"'
Skipping line 1071188: ',' expected after '"'
Skipping line 1198142: ',' expected after '"'
Skipping line 1251978: ',' expected after '"'
Skipping line 1279056: ',' expected after '"'
Skipping line 1298352: ',' expected after '"'
Skipping line 1307011: ',' expected after '"'
Skipping line 1335826: ',' expected after '"'
Skipping line 1348315: ',' expected after '"'
Skipping line 1389861: ',' expected after '"'
Skipping line 1413000: ',' expected after '"'
Skipping line 1415886: ',' expected after '"'
Skipping line 1419731: ',' expected after '"'
Skipping line 1420693: ',' expected after '"'
Skipping line 1501669: ',' expected after '"'
Skipping line 1513225: ',' expected after '"'
Skipping line 1522829: ',' expected after '"'
Skipping line 1543010: ',' expected after '"'
Skipping line 1631551: ',' expected after '"'
Skipping line 1723040: ',' expected after '"'
Skipping line 1755811: ',' expected after '"'
Skipping line 1780891: ',' expected after '"'
Skipping line 1817094: ',' expected after '"'
Skipping line 1829801: ',' expected after '"'
Skipping line 1919668: ',' expected after '"'
Skipping line 1975477: ',' expected after '"'
Skipping line 1978399: ',' expected after '"'
Skipping line 2069202: ',' expected after '"'
Skipping line 2070178: ',' expected after '"'
Skipping line 2131652: ',' expected after '"'
Skipping line 2158993: ',' expected after '"'
Skipping line 2247885: ',' expected after '"'
Skipping line 2284146: ',' expected after '"'
Skipping line 2355665: ',' expected after '"'
Skipping line 2450573: ',' expected after '"'
Skipping line 2451555: ',' expected after '"'
Skipping line 2457420: ',' expected after '"'
Skipping line 2527844: ',' expected after '"'
Skipping line 2557671: ',' expected after '"'
Skipping line 2568434: ',' expected after '"'
Skipping line 2636958: ',' expected after '"'
Skipping line 2697644: ',' expected after '"'
Skipping line 2771056: ',' expected after '"'
Skipping line 2777903: ',' expected after '"'
Skipping line 2857148: ',' expected after '"'
Skipping line 2891429: ',' expected after '"'
Skipping line 2901239: ',' expected after '"'
Skipping line 2993295: ',' expected after '"'
Skipping line 3003080: ',' expected after '"'
Skipping line 3087241: ',' expected after '"'
Skipping line 3099964: ',' expected after '"'
Skipping line 3249731: ',' expected after '"'
Skipping line 3269309: ',' expected after '"'
Skipping line 3318219: ',' expected after '"'
Skipping line 3337782: ',' expected after '"'
Skipping line 3360377: ',' expected after '"'
Skipping line 3391704: ',' expected after '"'
Skipping line 3394641: ',' expected after '"'
Skipping line 3476910: ',' expected after '"'
Skipping line 3509220: ',' expected after '"'
Skipping line 3558206: ',' expected after '"'
Skipping line 3579716: ',' expected after '"'
Skipping line 3603264: ',' expected after '"'
Skipping line 3653178: ',' expected after '"'
Skipping line 3720700: ',' expected after '"'
Skipping line 3829292: ',' expected after '"'
Skipping line 3862504: ',' expected after '"'
Skipping line 3937916: ',' expected after '"'
Skipping line 4042710: ',' expected after '"'
Skipping line 4065215: ',' expected after '"'
Skipping line 4109261: ',' expected after '"'
Skipping line 4114146: ',' expected after '"'
Skipping line 4133739: ',' expected after '"'
Skipping line 4145467: ',' expected after '"'
Skipping line 4157206: ',' expected after '"'
Skipping line 4164066: ',' expected after '"'
Skipping line 4222863: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-36089,2020-07-01 00:00:54,1734,쌍문현대1차아파트 108동 앞,0,2020-07-01 00:03:13,1726,삼익세라믹아파트교차로,0,2,0.0
1,SPB-11402,2020-07-01 00:00:15,610,동대문중 교차로,10,2020-07-01 00:03:23,657,동대문롯데캐슬아파트 앞,1,3,450.0
2,SPB-36935,2020-07-01 00:01:02,3557,서울숲리버뷰자이APT105동 앞,0,2020-07-01 00:04:15,3511,응봉역 1번출구,0,3,0.0
3,SPB-35374,2020-07-01 00:00:04,146,마포역 2번출구 뒤,0,2020-07-01 00:04:22,148,용강동 주민센터 앞,0,4,0.0
4,SPB-37258,2020-07-01 00:01:52,2170,조원동서울본병원,0,2020-07-01 00:04:24,2170,조원동서울본병원,0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4260105,SPB-41716,2020-08-31 23:12:27,2002,노들역 1번출구,0,2020-09-01 03:05:38,2220,반포본동 주민센터 앞,0,233,0.0
4260106,SPB-31279,2020-08-31 21:08:23,1159,서서울모터리움앞,0,2020-09-01 03:13:03,1103,방화역 4번출구앞,0,365,0.0
4260107,SPB-30443,2020-08-31 23:02:51,242,신길선원가와인아파트 앞,0,2020-09-01 03:22:42,241,신길우성1차아파트 앞 공원,0,260,0.0
4260108,SPB-31171,2020-08-31 21:26:58,726,목동3단지 시내버스정류장,0,2020-09-01 03:42:35,243,이앤씨드림타워 앞,0,376,0.0
4260109,SPB-31725,2020-08-31 23:05:39,2526,반포경남쇼핑 앞,0,2020-09-01 05:12:34,1380,월곡역 5번출구 앞,0,367,0.0

In [130]:
data7 = data7.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data7.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-36089,2020-07-01 00:00:54,1734,쌍문현대1차아파트 108동 앞,0,2020-07-01 00:03:13,1726,삼익세라믹아파트교차로,0,2,0.0
1,SPB-11402,2020-07-01 00:00:15,610,동대문중 교차로,10,2020-07-01 00:03:23,657,동대문롯데캐슬아파트 앞,1,3,450.0
2,SPB-36935,2020-07-01 00:01:02,3557,서울숲리버뷰자이APT105동 앞,0,2020-07-01 00:04:15,3511,응봉역 1번출구,0,3,0.0
3,SPB-35374,2020-07-01 00:00:04,146,마포역 2번출구 뒤,0,2020-07-01 00:04:22,148,용강동 주민센터 앞,0,4,0.0
4,SPB-37258,2020-07-01 00:01:52,2170,조원동서울본병원,0,2020-07-01 00:04:24,2170,조원동서울본병원,0,3,0.0

In [131]:
data7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4260110 entries, 0 to 4260109
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 357.5+ MB

In [132]:
data7.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [133]:
#data7.to_csv('./공공자전거 대여이력 정보_2020.07_08.csv', index = False, encoding ='cp949')

In [37]:
data8 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.09.csv', engine = 'python')
data8

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-42373,2020-09-01 00:00:28,787,양천아파트 입구,0,2020-09-01 00:01:58,787,양천아파트 입구,0,2,0.0
1,SPB-35204,2020-09-01 00:00:18,1440,하나은행 면목지점,0,2020-09-01 00:02:23,1440,하나은행 면목지점,0,2,0.0
2,SPB-32450,2020-09-01 00:01:11,1041,묘곡초등학교,0,2020-09-01 00:04:00,1083,광문고교사거리(아이파크),0,3,0.0
3,SPB-32422,2020-09-01 00:01:05,240,문래역 4번출구 앞,0,2020-09-01 00:04:33,262,영문초등학교 사거리,0,3,0.0
4,SPB-35520,2020-09-01 00:00:00,2137,KT&G 관악지점,0,2020-09-01 00:04:43,2169,봉천역 2번출구,0,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2784698,SPB-37145,2020-09-30 17:01:22,2369,KT선릉타워,0,2020-10-01 12:22:32,2369,KT선릉타워,0,1161,0.0
2784699,SPB-41234,2020-09-30 17:30:53,1300,오륜사거리,0,2020-10-01 13:16:02,1213,백토공원 앞,0,1185,0.0
2784700,SPB-32681,2020-09-30 20:44:08,701,목동사거리 부근,0,2020-10-01 13:34:55,752,성원2차 아파트,0,1011,0.0
2784701,SPB-31286,2020-09-30 15:20:14,284,센트럴 푸르지오 시티 앞,0,2020-10-01 17:35:05,703,오목교역 7번출구 앞,0,1575,0.0
2784702,SPB-32474,2020-09-30 04:54:49,1540,가오리역,0,2020-10-01 18:40:03,1538,솔밭공원역,0,2265,0.0

In [134]:
data8 = data8.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data8.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-42373,2020-09-01 00:00:28,787,양천아파트 입구,0,2020-09-01 00:01:58,787,양천아파트 입구,0,2,0.0
1,SPB-35204,2020-09-01 00:00:18,1440,하나은행 면목지점,0,2020-09-01 00:02:23,1440,하나은행 면목지점,0,2,0.0
2,SPB-32450,2020-09-01 00:01:11,1041,묘곡초등학교,0,2020-09-01 00:04:00,1083,광문고교사거리(아이파크),0,3,0.0
3,SPB-32422,2020-09-01 00:01:05,240,문래역 4번출구 앞,0,2020-09-01 00:04:33,262,영문초등학교 사거리,0,3,0.0
4,SPB-35520,2020-09-01 00:00:00,2137,KT&G 관악지점,0,2020-09-01 00:04:43,2169,봉천역 2번출구,0,5,0.0

In [135]:
data8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2784703 entries, 0 to 2784702
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 233.7+ MB

In [136]:
data8.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [137]:
#data8.to_csv('./공공자전거 대여이력 정보_2020.09.csv', index = False, encoding ='cp949')

In [39]:
data9 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.10.csv', engine = 'python')
data9

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-32784,2020-10-01 00:00:19,2403,공무원연금매점 교차로 (개포주공9단지 입구),0,2020-10-01 00:03:56,2423,영희초교 사거리(래미안개포루체하임),0,4,0.0
1,SPB-33175,2020-10-01 00:01:20,1946,구로역 광장,0,2020-10-01 00:04:09,1946,구로역 광장,0,3,0.0
2,SPB-35926,2020-10-01 00:02:57,1541,삼양역,0,2020-10-01 00:04:53,1541,삼양역,0,2,0.0
3,SPB-21575,2020-10-01 00:00:07,1161,강서면허시험장앞,1,2020-10-01 00:04:59,1184,마곡13단지,11,4,850.0
4,SPB-19842,2020-10-01 00:01:47,2264,이수역 1번출구,4,2020-10-01 00:05:06,2228,뒷벌공원 옆,17,3,540.0
...,...,...,...,...,...,...,...,...,...,...,...
2869177,SPB-39736,2020-10-31 21:25:40,1199,우장산역 3번출구,0,2020-11-01 08:26:40,2737,까치산역 3번 출구,0,661,0.0
2869178,SPB-50812,2020-10-31 22:49:34,1090,상일동역 2번출구 앞,0,2020-11-01 08:40:06,1016,해뜨는 주유소옆 리엔파크 109동앞,0,591,0.0
2869179,SPB-44402,2020-10-31 22:09:40,765,오목교역 3번출구,0,2020-11-01 10:07:54,764,목동청소년수련관,0,718,0.0
2869180,SPB-51314,2020-10-31 22:33:53,838,숙대입구역 4번출구,0,2020-11-01 16:30:50,445,대한상공회의소,0,1077,0.0
2869181,SPB-51448,2020-10-31 22:33:37,838,숙대입구역 4번출구,0,2020-11-01 16:30:55,445,대한상공회의소,0,1077,0.0

In [138]:
data9 = data9.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data9.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-32784,2020-10-01 00:00:19,2403,공무원연금매점 교차로 (개포주공9단지 입구),0,2020-10-01 00:03:56,2423,영희초교 사거리(래미안개포루체하임),0,4,0.0
1,SPB-33175,2020-10-01 00:01:20,1946,구로역 광장,0,2020-10-01 00:04:09,1946,구로역 광장,0,3,0.0
2,SPB-35926,2020-10-01 00:02:57,1541,삼양역,0,2020-10-01 00:04:53,1541,삼양역,0,2,0.0
3,SPB-21575,2020-10-01 00:00:07,1161,강서면허시험장앞,1,2020-10-01 00:04:59,1184,마곡13단지,11,4,850.0
4,SPB-19842,2020-10-01 00:01:47,2264,이수역 1번출구,4,2020-10-01 00:05:06,2228,뒷벌공원 옆,17,3,540.0

In [139]:
data9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2869182 entries, 0 to 2869181
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 240.8+ MB

In [140]:
data9.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [141]:
#data9.to_csv('./공공자전거 대여이력 정보_2020.10.csv', index = False, encoding ='cp949')

In [41]:
data10 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.11.csv', engine = 'python')
data10

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-36740,2020-11-01 00:01:00,1149,신방화역환승주차장,0,2020-11-01 00:03:39,2702,마곡 엠밸리2단지,0,3,0.0
1,SPB-37147,2020-11-01 00:02:09,3520,광진경찰서,0,2020-11-01 00:04:20,3501,광진구청 앞,0,2,0.0
2,SPB-30331,2020-11-01 00:00:12,3009,서교동사거리(신),0,2020-11-01 00:04:25,3010,홍대입구역 3번출구,0,4,0.0
3,SPB-36835,2020-11-01 00:01:52,2711,가로공원공영주차장 1번 출구,0,2020-11-01 00:04:27,1127,화곡역(에이스정형외과앞) 버스정류장,0,3,0.0
4,SPB-31250,2020-11-01 00:03:31,1637,KT 노원점 건물 앞,0,2020-11-01 00:05:04,1637,KT 노원점 건물 앞,0,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1975132,SPB-51218,2020-11-30 23:38:28,1617,하계동 중평어린이공원 앞,0,2020-12-01 01:35:30,1656,중앙하이츠 아파트 입구,0,117,0.0
1975133,SPB-33827,2020-11-30 23:54:12,153,성산2교 사거리,0,2020-12-01 01:46:38,153,성산2교 사거리,0,112,0.0
1975134,SPB-42198,2020-11-30 21:15:52,170,가재울 뉴타운 주유소 옆,0,2020-12-01 02:08:20,165,중앙근린공원,0,292,0.0
1975135,SPB-35244,2020-11-30 21:29:15,2111,서울대입구역 1번출구,0,2020-12-01 02:49:14,2284,CJ오쇼핑앞,0,320,0.0
1975136,SPB-33922,2020-11-30 19:28:03,2822,제니스스포츠 앞,0,2020-12-01 05:04:15,263,근로자회관 사거리,0,576,0.0

In [142]:
data10 = data10.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data10.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-36740,2020-11-01 00:01:00,1149,신방화역환승주차장,0,2020-11-01 00:03:39,2702,마곡 엠밸리2단지,0,3,0.0
1,SPB-37147,2020-11-01 00:02:09,3520,광진경찰서,0,2020-11-01 00:04:20,3501,광진구청 앞,0,2,0.0
2,SPB-30331,2020-11-01 00:00:12,3009,서교동사거리(신),0,2020-11-01 00:04:25,3010,홍대입구역 3번출구,0,4,0.0
3,SPB-36835,2020-11-01 00:01:52,2711,가로공원공영주차장 1번 출구,0,2020-11-01 00:04:27,1127,화곡역(에이스정형외과앞) 버스정류장,0,3,0.0
4,SPB-31250,2020-11-01 00:03:31,1637,KT 노원점 건물 앞,0,2020-11-01 00:05:04,1637,KT 노원점 건물 앞,0,2,0.0

In [143]:
data10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1975137 entries, 0 to 1975136
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 165.8+ MB

In [144]:
data10.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [145]:
#data10.to_csv('./공공자전거 대여이력 정보_2020.11.csv', index = False, encoding ='cp949')

In [43]:
data11= pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2020.12.csv', engine = 'python')
data11

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-33225,2020-12-01 00:00:05,671,대광빌딩,0,2020-12-01 00:01:45,672,대광고등학교,0,2,0.00
1,SPB-32037,2020-12-01 00:00:49,352,중앙고입구 삼거리,0,2020-12-01 00:02:33,353,재동초교 앞 삼거리,0,2,0.00
2,SPB-33654,2020-12-01 00:01:37,2644,성내5교 (GS주유소),0,2020-12-01 00:03:57,1277,오금동 송파 참병원,0,2,0.00
3,SPB-52806,2020-12-01 00:01:00,1953,천왕역 4번출구 뒤,0,2020-12-01 00:04:10,1952,천왕연지타운2단지 앞,0,3,0.00
4,SPB-80266,2020-12-01 00:00:53,1036,고덕동 주양쇼핑,99,2020-12-01 00:04:34,1036,고덕동 주양쇼핑,99,4,80.00
...,...,...,...,...,...,...,...,...,...,...,...
1185902,SPB-32746,2020-12-31 20:36:25,1009,천호역4번출구(현대백화점),0,2021-01-01 01:52:00,1022,길동 사거리(초소앞),0,315,1869.66
1185903,SPB-30390,2020-12-31 22:51:36,1965,삼환로즈빌아파트 105동 옆,0,2021-01-01 02:29:15,210,IFC몰,0,217,16245.85
1185904,SPB-50439,2020-12-31 22:56:32,1964,원메디타운 앞,0,2021-01-01 02:29:32,210,IFC몰,0,213,0.00
1185905,SPB-37080,2020-12-31 22:18:07,130,신촌역(2호선) 7번출구 앞,0,2021-01-01 02:47:57,148,용강동 주민센터 앞,0,269,1627.36
1185906,SPB-33700,2020-12-31 21:52:24,1735,"도봉역 1,2번 출구사이 건너편",0,2021-01-01 04:39:40,1630,수연빌딩 앞,0,407,7415.48

In [146]:
data11 = data11.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data11.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-33225,2020-12-01 00:00:05,671,대광빌딩,0,2020-12-01 00:01:45,672,대광고등학교,0,2,0.0
1,SPB-32037,2020-12-01 00:00:49,352,중앙고입구 삼거리,0,2020-12-01 00:02:33,353,재동초교 앞 삼거리,0,2,0.0
2,SPB-33654,2020-12-01 00:01:37,2644,성내5교 (GS주유소),0,2020-12-01 00:03:57,1277,오금동 송파 참병원,0,2,0.0
3,SPB-52806,2020-12-01 00:01:00,1953,천왕역 4번출구 뒤,0,2020-12-01 00:04:10,1952,천왕연지타운2단지 앞,0,3,0.0
4,SPB-80266,2020-12-01 00:00:53,1036,고덕동 주양쇼핑,99,2020-12-01 00:04:34,1036,고덕동 주양쇼핑,99,4,80.0

In [147]:
data11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1185907 entries, 0 to 1185906
Data columns (total 11 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   자전거번호    1185907 non-null  object
 1   대여일시     1185907 non-null  object
 2   대여대여소번호  1185907 non-null  int64
 3   대여대여소명   1185907 non-null  object
 4   대여거치대    1185907 non-null  int64
 5   반납일시     1185907 non-null  object
 6   반납대여소번호  1185907 non-null  int64
 7   반납대여소명   1185907 non-null  object
 8   반납거치대    1185907 non-null  int64
 9   이용시간     1185907 non-null  int64
 10  이용거리     1185907 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 99.5+ MB

In [148]:
data11.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [149]:
#data11.to_csv('./공공자전거 대여이력 정보_2020.12.csv', index = False, encoding ='cp949')

In [45]:
data12 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2021.01.csv', engine = 'python')
data12

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-53145,2021-01-02 20:50:36,3,중랑센터,0,2021-01-02 21:15:41,668,서울축산농협(장안지점),0,25,0.00
1,SPB-53074,2021-01-04 16:02:12,3,중랑센터,0,2021-01-04 16:17:06,668,서울축산농협(장안지점),0,14,0.00
2,SPB-50952,2021-01-13 21:02:05,3,중랑센터,0,2021-01-13 21:14:04,668,서울축산농협(장안지점),0,11,1853.99
3,SPB-52380,2021-01-14 21:02:55,3,중랑센터,0,2021-01-14 21:13:41,668,서울축산농협(장안지점),0,10,0.00
4,SPB-52380,2021-01-18 18:02:08,3,중랑센터,0,2021-01-18 18:15:22,540,군자역 7번출구 베스트샵 앞,0,13,2291.05
...,...,...,...,...,...,...,...,...,...,...,...
806498,SPB-81270,2021-01-24 20:13:33,9999,상담센터,0,2021-01-24 20:56:28,2908,광운대학교 중앙도서관,99,42,3730.00
806499,SPB-39891,2021-01-25 12:10:06,9999,상담센터,0,2021-01-25 12:35:20,626,군자교 서측 녹지대,0,25,3680.00
806500,SPB-32679,2021-01-27 14:47:18,9999,상담센터,0,2021-01-27 15:12:45,2299,한전아트센터 앞,0,25,2471.37
806501,SPB-80712,2021-01-31 14:39:45,9999,상담센터,0,2021-01-31 15:46:49,175,홍연2교옆,99,67,4050.00
806502,SPB-80617,2021-01-31 15:54:05,9999,상담센터,0,2021-01-31 16:11:01,117,홍은사거리,99,16,2310.00

In [150]:
data12 = data12.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data12.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-53145,2021-01-02 20:50:36,3,중랑센터,0,2021-01-02 21:15:41,668,서울축산농협(장안지점),0,25,0.00
1,SPB-53074,2021-01-04 16:02:12,3,중랑센터,0,2021-01-04 16:17:06,668,서울축산농협(장안지점),0,14,0.00
2,SPB-50952,2021-01-13 21:02:05,3,중랑센터,0,2021-01-13 21:14:04,668,서울축산농협(장안지점),0,11,1853.99
3,SPB-52380,2021-01-14 21:02:55,3,중랑센터,0,2021-01-14 21:13:41,668,서울축산농협(장안지점),0,10,0.00
4,SPB-52380,2021-01-18 18:02:08,3,중랑센터,0,2021-01-18 18:15:22,540,군자역 7번출구 베스트샵 앞,0,13,2291.05

In [151]:
data12.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 806503 entries, 0 to 806502
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    806503 non-null  object
 1   대여일시     806503 non-null  object
 2   대여대여소번호  806503 non-null  int64
 3   대여대여소명   806503 non-null  object
 4   대여거치대    806503 non-null  int64
 5   반납일시     806503 non-null  object
 6   반납대여소번호  806503 non-null  int64
 7   반납대여소명   806503 non-null  object
 8   반납거치대    806503 non-null  int64
 9   이용시간     806503 non-null  int64
 10  이용거리     806503 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.7+ MB

In [152]:
data12.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [153]:
#data12.to_csv('./공공자전거 대여이력 정보_2021.01.csv', index = False, encoding ='cp949')

In [99]:
data13 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2021.02.csv', engine = 'python', error_bad_lines=False)
data13

Skipping line 32789: ',' expected after '"'
Skipping line 152342: ',' expected after '"'
Skipping line 164860: ',' expected after '"'
Skipping line 235077: ',' expected after '"'
Skipping line 242803: ',' expected after '"'
Skipping line 283340: ',' expected after '"'
Skipping line 309361: ',' expected after '"'
Skipping line 373873: ',' expected after '"'
Skipping line 571857: ',' expected after '"'
Skipping line 617229: ',' expected after '"'
Skipping line 837570: ',' expected after '"'
Skipping line 850085: ',' expected after '"'
Skipping line 918574: ',' expected after '"'
Skipping line 948484: ',' expected after '"'
Skipping line 988999: ',' expected after '"'
Skipping line 1038196: ',' expected after '"'
Skipping line 1042058: ',' expected after '"'
Skipping line 1111335: ',' expected after '"'
Skipping line 1154516: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-51323,2021-02-01 00:00:38,1514,강북구청 사거리 버스정류소 앞,0,2021-02-01 00:03:05,1554,번동사거리,0,2,736.02
1,SPB-52771,2021-02-01 00:01:09,1977,천왕역 1번 출입구 앞,0,2021-02-01 00:04:59,1981,천왕이펜하우스5단지 앞,0,3,856.09
2,SPB-33780,2021-02-01 00:02:48,1358,정릉도서관 앞,0,2021-02-01 00:05:10,1360,정릉역,0,2,397.92
3,SPB-52936,2021-02-01 00:00:39,1211,방이삼거리,0,2021-02-01 00:05:27,2639,석촌역 8번출구,0,4,1015.50
4,SPB-41150,2021-02-01 00:01:59,1721,창동역 2번출구,0,2021-02-01 00:06:10,1708,보건소사거리(다비치안경창동점),0,4,0.00
...,...,...,...,...,...,...,...,...,...,...,...
1226387,SPB-35567,2021-02-28 23:21:55,2910,도깨비시장,0,2021-02-28 23:59:48,1726,삼익세라믹아파트교차로,0,37,6403.05
1226388,SPB-52298,2021-02-28 23:32:22,1336,성북3교 위,0,2021-02-28 23:59:49,346,맥스타일 앞,0,27,3839.32
1226389,SPB-43850,2021-02-28 22:56:01,590,건국대학교 (입학정보관),0,2021-02-28 23:59:54,502,뚝섬유원지역 1번출구 앞,0,63,2021.30
1226390,SPB-31466,2021-02-28 23:09:27,283,아크로타워 스퀘어(영등포시장),0,2021-02-28 23:59:56,283,아크로타워 스퀘어(영등포시장),0,50,8361.71
1226391,SPB-43306,2021-02-28 23:44:24,152,마포구민체육센터 앞,0,2021-02-28 23:59:56,427,성산시영아파트,0,15,2370.33

In [154]:
data13 = data13.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data13.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-51323,2021-02-01 00:00:38,1514,강북구청 사거리 버스정류소 앞,0,2021-02-01 00:03:05,1554,번동사거리,0,2,736.02
1,SPB-52771,2021-02-01 00:01:09,1977,천왕역 1번 출입구 앞,0,2021-02-01 00:04:59,1981,천왕이펜하우스5단지 앞,0,3,856.09
2,SPB-33780,2021-02-01 00:02:48,1358,정릉도서관 앞,0,2021-02-01 00:05:10,1360,정릉역,0,2,397.92
3,SPB-52936,2021-02-01 00:00:39,1211,방이삼거리,0,2021-02-01 00:05:27,2639,석촌역 8번출구,0,4,1015.50
4,SPB-41150,2021-02-01 00:01:59,1721,창동역 2번출구,0,2021-02-01 00:06:10,1708,보건소사거리(다비치안경창동점),0,4,0.00

In [155]:
data13.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1226392 entries, 0 to 1226391
Data columns (total 11 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   자전거번호    1226392 non-null  object
 1   대여일시     1226392 non-null  object
 2   대여대여소번호  1226392 non-null  int64
 3   대여대여소명   1226392 non-null  object
 4   대여거치대    1226392 non-null  int64
 5   반납일시     1226392 non-null  object
 6   반납대여소번호  1226392 non-null  int64
 7   반납대여소명   1226392 non-null  object
 8   반납거치대    1226392 non-null  int64
 9   이용시간     1226392 non-null  int64
 10  이용거리     1226392 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 102.9+ MB

In [156]:
data13.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [157]:
#data13.to_csv('./공공자전거 대여이력 정보_2021.02.csv', index = False, encoding ='cp949')

In [100]:
data14= pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2021.03.csv', engine = 'python', error_bad_lines=False)
data14

Skipping line 19509: ',' expected after '"'
Skipping line 45523: ',' expected after '"'
Skipping line 51303: ',' expected after '"'
Skipping line 91836: ',' expected after '"'
Skipping line 99532: ',' expected after '"'
Skipping line 119740: ',' expected after '"'
Skipping line 136195: ',' expected after '"'
Skipping line 214332: ',' expected after '"'
Skipping line 258576: ',' expected after '"'
Skipping line 282677: ',' expected after '"'
Skipping line 299006: ',' expected after '"'
Skipping line 401957: ',' expected after '"'
Skipping line 417429: ',' expected after '"'
Skipping line 435733: ',' expected after '"'
Skipping line 467504: ',' expected after '"'
Skipping line 468474: ',' expected after '"'
Skipping line 502278: ',' expected after '"'
Skipping line 506132: ',' expected after '"'
Skipping line 662334: ',' expected after '"'
Skipping line 710580: ',' expected after '"'
Skipping line 724108: ',' expected after '"'
Skipping line 729880: ',' expected after '"'
Skipping line 761644: ',' expected after '"'
Skipping line 896249: ',' expected after '"'
Skipping line 980150: ',' expected after '"'
Skipping line 1033237: ',' expected after '"'
Skipping line 1113302: ',' expected after '"'
Skipping line 1125805: ',' expected after '"'
Skipping line 1299298: ',' expected after '"'
Skipping line 1300259: ',' expected after '"'
Skipping line 1303150: ',' expected after '"'
Skipping line 1370592: ',' expected after '"'
Skipping line 1524945: ',' expected after '"'
Skipping line 1548978: ',' expected after '"'
Skipping line 1564424: ',' expected after '"'
Skipping line 1590504: ',' expected after '"'
Skipping line 1600140: ',' expected after '"'
Skipping line 1636716: ',' expected after '"'
Skipping line 1691726: ',' expected after '"'
Skipping line 1863068: ',' expected after '"'
Skipping line 1909341: ',' expected after '"'
Skipping line 1960445: ',' expected after '"'
Skipping line 1963341: ',' expected after '"'
Skipping line 1974960: ',' expected after '"'
Skipping line 2028024: ',' expected after '"'
Skipping line 2143648: ',' expected after '"'
Skipping line 2152281: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-50838,2021-02-28 23:14:47,1203,밀리아나2빌딩 앞,0,2021-03-01 00:00:03,1211,방이삼거리,0,45,3553.80
1,SPB-44343,2021-02-28 23:15:01,4480,가락시장역 롯데마트2,0,2021-03-01 00:00:03,3579,광진 캠퍼스시티,0,45,10426.18
2,SPB-33391,2021-02-28 23:32:33,1336,성북3교 위,0,2021-03-01 00:00:05,346,맥스타일 앞,0,27,3773.41
3,SPB-43223,2021-02-28 23:06:35,1012,서울 상운차량,0,2021-03-01 00:00:07,1002,해공공원(천호동),0,53,2695.24
4,SPB-32340,2021-02-28 23:18:18,2312,청담역 13번 출구 앞,0,2021-03-01 00:00:09,2503,반포1동 서초빌딩 앞,0,41,9092.37
...,...,...,...,...,...,...,...,...,...,...,...
2171928,SPB-31667,2021-03-31 23:35:58,700,KB국민은행 염창역 지점 앞,0,2021-03-31 23:59:54,702,목4동주민센터 옆,0,23,2878.63
2171929,SPB-38293,2021-03-31 22:17:29,1111,마곡엠밸리6_7단지 마곡중학교,0,2021-03-31 23:59:55,3796,송정역 3번출구 앞,0,102,2449.49
2171930,SPB-31383,2021-03-31 23:50:17,947,연신내 선일하이츠빌 정류소,0,2021-03-31 23:59:56,962,은평뉴타운 힐데스하임,0,9,1958.25
2171931,SPB-35281,2021-03-31 23:32:42,2228,뒷벌공원 옆,0,2021-03-31 23:59:56,2082,7호선 이수역7번출구,0,27,3780.21
2171932,SPB-37264,2021-03-31 23:12:17,911,은평평화공원(역촌역4번출구),0,2021-03-31 23:59:59,175,홍연2교옆,0,47,8984.35

In [158]:
data14 = data14.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data14.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-50838,2021-02-28 23:14:47,1203,밀리아나2빌딩 앞,0,2021-03-01 00:00:03,1211,방이삼거리,0,45,3553.80
1,SPB-44343,2021-02-28 23:15:01,4480,가락시장역 롯데마트2,0,2021-03-01 00:00:03,3579,광진 캠퍼스시티,0,45,10426.18
2,SPB-33391,2021-02-28 23:32:33,1336,성북3교 위,0,2021-03-01 00:00:05,346,맥스타일 앞,0,27,3773.41
3,SPB-43223,2021-02-28 23:06:35,1012,서울 상운차량,0,2021-03-01 00:00:07,1002,해공공원(천호동),0,53,2695.24
4,SPB-32340,2021-02-28 23:18:18,2312,청담역 13번 출구 앞,0,2021-03-01 00:00:09,2503,반포1동 서초빌딩 앞,0,41,9092.37

In [159]:
data14.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2171933 entries, 0 to 2171932
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 182.3+ MB

In [160]:
data14.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [161]:
#data14.to_csv('./공공자전거 대여이력 정보_2021.03.csv', index = False, encoding ='cp949')

In [101]:
data15 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2021.04.csv', engine = 'python', error_bad_lines=False)
data15

Skipping line 30455: ',' expected after '"'
Skipping line 59358: ',' expected after '"'
Skipping line 91075: ',' expected after '"'
Skipping line 97793: ',' expected after '"'
Skipping line 117992: ',' expected after '"'
Skipping line 180704: ',' expected after '"'
Skipping line 206661: ',' expected after '"'
Skipping line 374145: ',' expected after '"'
Skipping line 460851: ',' expected after '"'
Skipping line 495575: ',' expected after '"'
Skipping line 510985: ',' expected after '"'
Skipping line 525425: ',' expected after '"'
Skipping line 535996: ',' expected after '"'
Skipping line 555255: ',' expected after '"'
Skipping line 614101: ',' expected after '"'
Skipping line 851078: ',' expected after '"'
Skipping line 883731: ',' expected after '"'
Skipping line 888544: ',' expected after '"'
Skipping line 1083738: ',' expected after '"'
Skipping line 1105853: ',' expected after '"'
Skipping line 1127104: ',' expected after '"'
Skipping line 1156134: ',' expected after '"'
Skipping line 1167739: ',' expected after '"'
Skipping line 1170631: ',' expected after '"'
Skipping line 1218848: ',' expected after '"'
Skipping line 1272958: ',' expected after '"'
Skipping line 1456216: ',' expected after '"'
Skipping line 1464903: ',' expected after '"'
Skipping line 1476482: ',' expected after '"'
Skipping line 1485152: ',' expected after '"'
Skipping line 1511146: ',' expected after '"'
Skipping line 1531428: ',' expected after '"'
Skipping line 1587283: ',' expected after '"'
Skipping line 1689345: ',' expected after '"'
Skipping line 1715473: ',' expected after '"'
Skipping line 1764620: ',' expected after '"'
Skipping line 1778086: ',' expected after '"'
Skipping line 1790612: ',' expected after '"'
Skipping line 1798353: ',' expected after '"'
Skipping line 1989400: ',' expected after '"'
Skipping line 2008627: ',' expected after '"'
Skipping line 2015364: ',' expected after '"'
Skipping line 2026919: ',' expected after '"'
Skipping line 2071364: ',' expected after '"'
Skipping line 2097386: ',' expected after '"'
Skipping line 2135903: ',' expected after '"'
Skipping line 2172608: ',' expected after '"'
Skipping line 2233314: ',' expected after '"'
Skipping line 2325737: ',' expected after '"'
Skipping line 2379636: ',' expected after '"'
Skipping line 2396030: ',' expected after '"'
Skipping line 2432609: ',' expected after '"'
Skipping line 2499898: ',' expected after '"'
Skipping line 2545331: ',' expected after '"'
Skipping line 2648471: ',' expected after '"'
Skipping line 2672592: ',' expected after '"'
Skipping line 2696673: ',' expected after '"'
Skipping line 2700528: ',' expected after '"'
Skipping line 2773858: ',' expected after '"'
Skipping line 2847996: ',' expected after '"'
Skipping line 2940498: ',' expected after '"'
Skipping line 2965602: ',' expected after '"'
Skipping line 2995464: ',' expected after '"'
Skipping line 3019513: ',' expected after '"'
Skipping line 3024330: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-31332,2021-03-31 22:04:39,585,성수2가1동 공영주차장 인근,0,2021-04-01 00:00:01,3571,화양 APT(횡단보도 옆),0,115,0.00
1,SPB-53010,2021-03-31 23:47:26,2408,강남한양수자인아파트,0,2021-04-01 00:00:03,2615,테라타워2,0,12,1552.44
2,SPB-50637,2021-03-31 23:38:54,1222,잠실새내역 5번 출구 뒤,0,2021-04-01 00:00:04,2631,배명고등학교,0,21,2476.53
3,SPB-81056,2021-03-31 23:58:28,1709,쌍문역4번출구 주변,99,2021-04-01 00:00:06,1774,반석교회(쌍문동),99,1,0.00
4,SPB-40739,2021-03-31 23:47:27,2745,수명초등학교,0,2021-04-01 00:00:06,2746,수명산파크 4단지 411동 앞,0,12,628.75
...,...,...,...,...,...,...,...,...,...,...,...
3027461,SPB-53450,2021-04-30 23:57:21,1013,강동구청역 1번 출입구,0,2021-04-30 23:59:56,1020,강동경찰서,0,2,548.38
3027462,SPB-35293,2021-04-30 22:41:41,2301,현대고등학교 건너편,0,2021-04-30 23:59:56,2429,압구정로데오역 6번출구,0,78,2750.40
3027463,SPB-36957,2021-04-30 23:33:45,3803,세븐일레븐 신림점,0,2021-04-30 23:59:57,3803,세븐일레븐 신림점,0,26,6191.43
3027464,SPB-44673,2021-04-30 23:23:18,2173,당곡사거리,0,2021-04-30 23:59:58,2179,양녕로 입구,0,36,2930.55
3027465,SPB-33396,2021-04-30 23:52:13,482,예수소망교회,0,2021-04-30 23:59:58,375,다산 어린이공원,0,7,444.78

In [162]:
data15 = data15.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data15.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-31332,2021-03-31 22:04:39,585,성수2가1동 공영주차장 인근,0,2021-04-01 00:00:01,3571,화양 APT(횡단보도 옆),0,115,0.00
1,SPB-53010,2021-03-31 23:47:26,2408,강남한양수자인아파트,0,2021-04-01 00:00:03,2615,테라타워2,0,12,1552.44
2,SPB-50637,2021-03-31 23:38:54,1222,잠실새내역 5번 출구 뒤,0,2021-04-01 00:00:04,2631,배명고등학교,0,21,2476.53
3,SPB-81056,2021-03-31 23:58:28,1709,쌍문역4번출구 주변,99,2021-04-01 00:00:06,1774,반석교회(쌍문동),99,1,0.00
4,SPB-40739,2021-03-31 23:47:27,2745,수명초등학교,0,2021-04-01 00:00:06,2746,수명산파크 4단지 411동 앞,0,12,628.75

In [163]:
data15.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3027466 entries, 0 to 3027465
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 254.1+ MB

In [164]:
data15.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [165]:
#data15.to_csv('./공공자전거 대여이력 정보_2021.04.csv', index = False, encoding ='cp949')

In [102]:
data16 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2021.05.csv', engine = 'python', error_bad_lines=False)
data16

Skipping line 9339: ',' expected after '"'
Skipping line 44013: ',' expected after '"'
Skipping line 107502: ',' expected after '"'
Skipping line 133430: ',' expected after '"'
Skipping line 259686: ',' expected after '"'
Skipping line 266419: ',' expected after '"'
Skipping line 278940: ',' expected after '"'
Skipping line 357945: ',' expected after '"'
Skipping line 495615: ',' expected after '"'
Skipping line 503329: ',' expected after '"'
Skipping line 505251: ',' expected after '"'
Skipping line 554331: ',' expected after '"'
Skipping line 564966: ',' expected after '"'
Skipping line 579453: ',' expected after '"'
Skipping line 583301: ',' expected after '"'
Skipping line 611248: ',' expected after '"'
Skipping line 662299: ',' expected after '"'
Skipping line 683452: ',' expected after '"'
Skipping line 743131: ',' expected after '"'
Skipping line 769062: ',' expected after '"'
Skipping line 773859: ',' expected after '"'
Skipping line 823872: ',' expected after '"'
Skipping line 895318: ',' expected after '"'
Skipping line 1176626: ',' expected after '"'
Skipping line 1177586: ',' expected after '"'
Skipping line 1204633: ',' expected after '"'
Skipping line 1258601: ',' expected after '"'
Skipping line 1288403: ',' expected after '"'
Skipping line 1357832: ',' expected after '"'
Skipping line 1427075: ',' expected after '"'
Skipping line 1440553: ',' expected after '"'
Skipping line 1462708: ',' expected after '"'
Skipping line 1534036: ',' expected after '"'
Skipping line 1584268: ',' expected after '"'
Skipping line 1622732: ',' expected after '"'
Skipping line 1630412: ',' expected after '"'
Skipping line 1638106: ',' expected after '"'
Skipping line 1650611: ',' expected after '"'
Skipping line 1655423: ',' expected after '"'
Skipping line 1732384: ',' expected after '"'
Skipping line 1739110: ',' expected after '"'
Skipping line 1791008: ',' expected after '"'
Skipping line 1874075: ',' expected after '"'
Skipping line 1909732: ',' expected after '"'
Skipping line 1989694: ',' expected after '"'
Skipping line 2018545: ',' expected after '"'
Skipping line 2176236: ',' expected after '"'
Skipping line 2265918: ',' expected after '"'
Skipping line 2304416: ',' expected after '"'
Skipping line 2322767: ',' expected after '"'
Skipping line 2363203: ',' expected after '"'
Skipping line 2462570: ',' expected after '"'
Skipping line 2473150: ',' expected after '"'
Skipping line 2506820: ',' expected after '"'
Skipping line 2512588: ',' expected after '"'
Skipping line 2559799: ',' expected after '"'
Skipping line 2566525: ',' expected after '"'
Skipping line 2575188: ',' expected after '"'
Skipping line 2652272: ',' expected after '"'
Skipping line 2703301: ',' expected after '"'
Skipping line 2774577: ',' expected after '"'
Skipping line 2814937: ',' expected after '"'
Skipping line 2819729: ',' expected after '"'
Skipping line 2868010: ',' expected after '"'
Skipping line 2919983: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-51372,2021-04-30 23:13:46,605,신설동역8번출구,0,2021-05-01 00:00:03,4710,자교교회 앞,0,46,6234.92
1,SPB-51159,2021-04-30 23:52:51,2277,길마중4교 하부,0,2021-05-01 00:00:04,2525,반포쇼핑타운 2동 앞,0,7,1660.90
2,SPB-32374,2021-04-30 23:52:31,703,오목교역 7번출구 앞,0,2021-05-01 00:00:04,796,목동아파트 14단지 B상가 앞,0,7,1377.78
3,SPB-39733,2021-04-30 23:50:46,1721,창동역 2번출구,0,2021-05-01 00:00:05,1690,도봉운전면허시험장,0,9,1404.03
4,SPB-81816,2021-04-30 23:51:57,1351,안암2교 옆,99,2021-05-01 00:00:05,378,청계7가 사거리,99,8,1770.00
...,...,...,...,...,...,...,...,...,...,...,...
2935434,SPB-31282,2021-05-31 23:48:22,2190,도원맨션,0,2021-05-31 23:59:57,2102,봉림교 교통섬,0,11,1145.32
2935435,SPB-50316,2021-05-31 23:55:04,1106,신방화사거리,0,2021-05-31 23:59:57,1103,방화역 4번출구앞,0,4,639.19
2935436,SPB-44035,2021-05-31 23:51:12,1627,수락산역 4번출구,0,2021-05-31 23:59:58,1727,서울도봉초등학교인근,0,8,1383.25
2935437,SPB-50409,2021-05-31 23:31:37,1008,암사역 3번출구(국민은행앞),0,2021-05-31 23:59:58,544,광남중학교,0,28,3234.21
2935438,SPB-55881,2021-05-31 23:51:36,2377,수서역 5번출구 뒤,0,2021-05-31 23:59:58,1257,가락시장역 롯데마트앞,0,8,1430.00

In [166]:
data16 = data16.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data16.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-51372,2021-04-30 23:13:46,605,신설동역8번출구,0,2021-05-01 00:00:03,4710,자교교회 앞,0,46,6234.92
1,SPB-51159,2021-04-30 23:52:51,2277,길마중4교 하부,0,2021-05-01 00:00:04,2525,반포쇼핑타운 2동 앞,0,7,1660.90
2,SPB-32374,2021-04-30 23:52:31,703,오목교역 7번출구 앞,0,2021-05-01 00:00:04,796,목동아파트 14단지 B상가 앞,0,7,1377.78
3,SPB-39733,2021-04-30 23:50:46,1721,창동역 2번출구,0,2021-05-01 00:00:05,1690,도봉운전면허시험장,0,9,1404.03
4,SPB-81816,2021-04-30 23:51:57,1351,안암2교 옆,99,2021-05-01 00:00:05,378,청계7가 사거리,99,8,1770.00

In [167]:
data16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2935439 entries, 0 to 2935438
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 246.4+ MB

In [168]:
data16.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [169]:
#data16.to_csv('./공공자전거 대여이력 정보_2021.05.csv', index = False, encoding ='cp949')

In [91]:
data17 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거 대여이력 정보_2021.06.csv', engine = 'python', error_bad_lines=False)
data17

Skipping line 96255: ',' expected after '"'
Skipping line 99146: ',' expected after '"'
Skipping line 100109: ',' expected after '"'
Skipping line 168636: ',' expected after '"'
Skipping line 187898: ',' expected after '"'
Skipping line 196557: ',' expected after '"'
Skipping line 246596: ',' expected after '"'
Skipping line 555788: ',' expected after '"'
Skipping line 557723: ',' expected after '"'
Skipping line 563501: ',' expected after '"'
Skipping line 564463: ',' expected after '"'
Skipping line 577960: ',' expected after '"'
Skipping line 652032: ',' expected after '"'
Skipping line 655883: ',' expected after '"'
Skipping line 660707: ',' expected after '"'
Skipping line 686797: ',' expected after '"'
Skipping line 725369: ',' expected after '"'
Skipping line 754208: ',' expected after '"'
Skipping line 836230: ',' expected after '"'
Skipping line 861272: ',' expected after '"'
Skipping line 868961: ',' expected after '"'
Skipping line 880506: ',' expected after '"'
Skipping line 886282: ',' expected after '"'
Skipping line 893025: ',' expected after '"'
Skipping line 925827: ',' expected after '"'
Skipping line 991413: ',' expected after '"'
Skipping line 1129338: ',' expected after '"'
Skipping line 1235318: ',' expected after '"'
Skipping line 1316213: ',' expected after '"'
Skipping line 1574409: ',' expected after '"'
Skipping line 1657315: ',' expected after '"'
Skipping line 1665980: ',' expected after '"'
Skipping line 1790360: ',' expected after '"'
Skipping line 1809622: ',' expected after '"'
Skipping line 1898385: ',' expected after '"'
Skipping line 1914751: ',' expected after '"'
Skipping line 2053490: ',' expected after '"'
Skipping line 2154502: ',' expected after '"'
Skipping line 2181509: ',' expected after '"'
Skipping line 2192115: ',' expected after '"'
Skipping line 2207502: ',' expected after '"'
Skipping line 2236337: ',' expected after '"'
Skipping line 2237299: ',' expected after '"'
Skipping line 2245966: ',' expected after '"'
Skipping line 2259473: ',' expected after '"'
Skipping line 2273024: ',' expected after '"'
Skipping line 2291365: ',' expected after '"'
Skipping line 2312585: ',' expected after '"'
Skipping line 2345322: ',' expected after '"'
Skipping line 2352058: ',' expected after '"'
Skipping line 2376093: ',' expected after '"'
Skipping line 2404071: ',' expected after '"'
Skipping line 2410840: ',' expected after '"'
Skipping line 2418570: ',' expected after '"'
Skipping line 2440775: ',' expected after '"'
Skipping line 2442709: ',' expected after '"'
Skipping line 2557425: ',' expected after '"'
Skipping line 2561282: ',' expected after '"'
Skipping line 2586408: ',' expected after '"'
Skipping line 2609517: ',' expected after '"'
Skipping line 2674188: ',' expected after '"'
Skipping line 2749318: ',' expected after '"'
Skipping line 2751244: ',' expected after '"'
Skipping line 2838086: ',' expected after '"'
Skipping line 2939106: ',' expected after '"'
Skipping line 2983357: ',' expected after '"'
Skipping line 3050707: ',' expected after '"'
Skipping line 3065151: ',' expected after '"'
Skipping line 3127784: ',' expected after '"'
Skipping line 3158681: ',' expected after '"'
Skipping line 3334064: ',' expected after '"'
Skipping line 3369844: ',' expected after '"'
Skipping line 3385280: ',' expected after '"'

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-30385,2021-05-31 23:07:00,3571,화양 APT(횡단보도 옆),0,2021-06-01 00:00:00,3538,서울숲 IT캐슬,0,53,2502.80
1,SPB-46321,2021-05-31 23:37:19,1911,구로디지털단지역 앞,0,2021-06-01 00:00:02,1843,독산고등학교,0,22,1630.00
2,SPB-48119,2021-05-31 23:48:40,3860,건국대학교 정문 앞,0,2021-06-01 00:00:03,3586,군자역 비채온 오피스텔,0,11,1420.00
3,SPB-55360,2021-05-31 23:47:52,2222,사당역 12번출구 뒤,0,2021-06-01 00:00:05,2228,뒷벌공원 옆,0,12,1350.00
4,SPB-54699,2021-05-31 23:51:14,1955,디지털입구 교차로,0,2021-06-01 00:00:08,1856,모두의학교,0,8,930.00
...,...,...,...,...,...,...,...,...,...,...,...
3445866,SPB-36886,2021-06-30 22:44:14,152,마포구민체육센터 앞,0,2021-07-01 04:48:33,126,서강대 후문 옆,0,364,10153.36
3445867,SPB-30409,2021-06-30 22:45:19,152,마포구민체육센터 앞,0,2021-07-01 04:52:25,437,대흥역 1번출구,0,367,10100.71
3445868,SPB-46230,2021-06-30 22:43:43,152,마포구민체육센터 앞,0,2021-07-01 04:52:27,437,대흥역 1번출구,0,368,430.00
3445869,SPB-41691,2021-06-30 22:11:14,2220,반포본동 주민센터 앞,0,2021-07-01 04:55:29,2526,반포경남쇼핑 앞,0,404,0.00
3445870,SPB-52274,2021-06-30 22:12:10,2220,반포본동 주민센터 앞,0,2021-07-01 04:55:30,2526,반포경남쇼핑 앞,0,403,4541.22

In [170]:
data17 = data17.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data17.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-30385,2021-05-31 23:07:00,3571,화양 APT(횡단보도 옆),0,2021-06-01 00:00:00,3538,서울숲 IT캐슬,0,53,2502.8
1,SPB-46321,2021-05-31 23:37:19,1911,구로디지털단지역 앞,0,2021-06-01 00:00:02,1843,독산고등학교,0,22,1630.0
2,SPB-48119,2021-05-31 23:48:40,3860,건국대학교 정문 앞,0,2021-06-01 00:00:03,3586,군자역 비채온 오피스텔,0,11,1420.0
3,SPB-55360,2021-05-31 23:47:52,2222,사당역 12번출구 뒤,0,2021-06-01 00:00:05,2228,뒷벌공원 옆,0,12,1350.0
4,SPB-54699,2021-05-31 23:51:14,1955,디지털입구 교차로,0,2021-06-01 00:00:08,1856,모두의학교,0,8,930.0

In [171]:
data17.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3445871 entries, 0 to 3445870
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 289.2+ MB

In [172]:
data17.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [173]:
#data17.to_csv('./공공자전거 대여이력 정보_2021.06.csv', index = False, encoding ='cp949')

In [52]:
data18 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/공공자전거_대여이력정보_2020.05.csv', engine = 'python')
data18

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-19866,2020-05-01 00:01:09,1706,기업은행 앞,5,2020-05-01 00:03:06,1733,방학사거리 (봄마당 앞),12,1,330.0
1,SPB-07309,2020-05-01 00:00:11,585,성수2가1동 공영주차장 인근,4,2020-05-01 00:03:56,585,성수2가1동 공영주차장 인근,4,3,0.0
2,SPB-09425,2020-05-01 00:02:25,1155,기쁜우리복지관,10,2020-05-01 00:04:40,1155,기쁜우리복지관,10,2,0.0
3,SPB-13624,2020-05-01 00:01:55,2396,영동3교 북단(우성캐릭터 앞 보도),1,2020-05-01 00:04:57,2335,3호선 매봉역 3번출구앞,6,2,0.0
4,SPB-32740,2020-05-01 00:00:31,917,녹번역 4번출구,0,2020-05-01 00:05:10,958,신한은행 응암동 지점 앞,0,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...
2426953,SPB-21898,2020-05-31 03:15:54,1149,신방화역환승주차장,7,2020-06-01 07:05:54,1165,마곡중학교 후문,19,94,7730.0
2426954,SPB-34153,2020-05-31 22:16:56,1222,잠실새내역 5번 출구 뒤,0,2020-06-01 08:22:42,1221,삼전사거리 포스코더샵,0,606,0.0
2426955,SPB-30675,2020-05-31 22:42:24,1257,가락시장역 롯데마트앞,0,2020-06-01 08:29:09,1271,송파도서관,0,587,0.0
2426956,SPB-35362,2020-05-31 22:25:29,913,이마트 은평점,0,2020-06-01 08:35:06,131,증산2교,0,610,0.0
2426957,SPB-33088,2020-05-31 23:00:13,1359,장위뉴타운 꿈에 숲 코오롱 하늘채 앞,0,2020-06-01 09:33:49,1373,성북구보건소 건너편,0,634,0.0

In [174]:
data18 = data18.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data18.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-19866,2020-05-01 00:01:09,1706,기업은행 앞,5,2020-05-01 00:03:06,1733,방학사거리 (봄마당 앞),12,1,330.0
1,SPB-07309,2020-05-01 00:00:11,585,성수2가1동 공영주차장 인근,4,2020-05-01 00:03:56,585,성수2가1동 공영주차장 인근,4,3,0.0
2,SPB-09425,2020-05-01 00:02:25,1155,기쁜우리복지관,10,2020-05-01 00:04:40,1155,기쁜우리복지관,10,2,0.0
3,SPB-13624,2020-05-01 00:01:55,2396,영동3교 북단(우성캐릭터 앞 보도),1,2020-05-01 00:04:57,2335,3호선 매봉역 3번출구앞,6,2,0.0
4,SPB-32740,2020-05-01 00:00:31,917,녹번역 4번출구,0,2020-05-01 00:05:10,958,신한은행 응암동 지점 앞,0,5,0.0

In [175]:
data18.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2426958 entries, 0 to 2426957
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 203.7+ MB

In [176]:
data18.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [177]:
#data18.to_csv('./공공자전거_대여이력정보_2020.05.csv', index = False, encoding ='cp949')

In [188]:
data19 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여이력 정보_2018년_1분기1.csv', engine = 'python')
data19

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,'SPB-02041','2018-01-01 00:00:10','227',' 양평2나들목 보행통로 입구',9,'2018-01-01 00:04:03','227',' 양평2나들목 보행통로 입구',9,3,50
1,'SPB-03796','2018-01-01 00:00:42','2219',"' 고속터미널역 8-1번, 8-2번 출구 사이'",15,'2018-01-01 00:25:41','3511',' 응봉역 1번출구',9,24,7670
2,'SPB-02402','2018-01-01 00:00:58','567',' 성수역 2번출구 앞',13,'2018-01-01 00:09:33','3506',' 영동대교 북단',2,8,1390
3,'SPB-01564','2018-01-01 00:01:02','568',' 청계8가사거리 부근',5,'2018-01-01 00:10:13','521',' 왕십리역 11번 출구 앞',9,8,1820
4,'SPB-05713','2018-01-01 00:01:03','361',' 동묘앞역 1번출구 뒤',4,'2018-01-01 00:06:18','383',' 신당역 12번 출구 뒤',8,4,850
...,...,...,...,...,...,...,...,...,...,...,...
784729,'SPB-00326','2018-03-31 23:59:46','2034',' 사당역 7번출구쪽',4,'2018-04-01 00:26:50','2136',' 신림역 8번출구',7,26,5010
784730,'SPB-07675','2018-03-31 23:59:52','266',' 영등포청과시장 사거리',10,'2018-04-01 00:07:30','245',' 삼성생명 당산사옥 앞',10,7,950
784731,'SPB-10926','2018-03-31 23:59:54','926',' 불광역 8번출구',2,'2018-04-01 00:40:21','926',' 불광역 8번출구',6,39,3130
784732,'SPB-15970','2018-03-31 23:59:56','503',' 더샵스타시티 C동 앞',15,'2018-04-01 00:04:38','504',' 신자초교입구교차로',1,4,590
784733,'SPB-04887','2018-03-31 23:59:58','1026',' 대명초교 입구 교차로',4,'2018-04-01 01:45:18','1017',' 맥도날드(길동)',11,104,16830

In [189]:
data19["'자전거번호'"] = data19["'자전거번호'"].str.strip("''")
data19["'대여일시'"] = data19["'대여일시'"].str.strip("''")
data19["'대여대여소번호'"] = data19["'대여대여소번호'"].str.strip("''")
data19["'대여대여소명'"] = data19["'대여대여소명'"].str.strip("''")
data19["'반납일시'"] = data19["'반납일시'"].str.strip("''")
data19["'반납대여소번호'"] = data19["'반납대여소번호'"].str.strip("''")
data19["'반납대여소명'"]= data19["'반납대여소명'"].str.strip("''")
data19.head()

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,SPB-02041,2018-01-01 00:00:10,227,양평2나들목 보행통로 입구,9,2018-01-01 00:04:03,227,양평2나들목 보행통로 입구,9,3,50
1,SPB-03796,2018-01-01 00:00:42,2219,"고속터미널역 8-1번, 8-2번 출구 사이",15,2018-01-01 00:25:41,3511,응봉역 1번출구,9,24,7670
2,SPB-02402,2018-01-01 00:00:58,567,성수역 2번출구 앞,13,2018-01-01 00:09:33,3506,영동대교 북단,2,8,1390
3,SPB-01564,2018-01-01 00:01:02,568,청계8가사거리 부근,5,2018-01-01 00:10:13,521,왕십리역 11번 출구 앞,9,8,1820
4,SPB-05713,2018-01-01 00:01:03,361,동묘앞역 1번출구 뒤,4,2018-01-01 00:06:18,383,신당역 12번 출구 뒤,8,4,850

In [190]:
data19 = data19.rename(columns = {"'자전거번호'" : '자전거번호', "'대여일시'" : '대여일시', "'대여대여소번호'" : '대여대여소번호', 
                                "'대여대여소명'" : '대여대여소명', "'대여거치대'" : '대여거치대', "'반납일시'" : '반납일시',
                                "'반납대여소번호'" : '반납대여소번호', "'반납대여소명'" : '반납대여소명', "'반납거치대'" : '반납거치대',
                                "'이용시간(분)'" : '이용시간', "'이용거리(M)'" : '이용거리'})
data19.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-02041,2018-01-01 00:00:10,227,양평2나들목 보행통로 입구,9,2018-01-01 00:04:03,227,양평2나들목 보행통로 입구,9,3,50
1,SPB-03796,2018-01-01 00:00:42,2219,"고속터미널역 8-1번, 8-2번 출구 사이",15,2018-01-01 00:25:41,3511,응봉역 1번출구,9,24,7670
2,SPB-02402,2018-01-01 00:00:58,567,성수역 2번출구 앞,13,2018-01-01 00:09:33,3506,영동대교 북단,2,8,1390
3,SPB-01564,2018-01-01 00:01:02,568,청계8가사거리 부근,5,2018-01-01 00:10:13,521,왕십리역 11번 출구 앞,9,8,1820
4,SPB-05713,2018-01-01 00:01:03,361,동묘앞역 1번출구 뒤,4,2018-01-01 00:06:18,383,신당역 12번 출구 뒤,8,4,850

In [219]:
data19['대여대여소명'] = data19['대여대여소명'].str.strip()
data19['반납대여소명'] = data19['반납대여소명'].str.strip()
data19.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-02041,2018-01-01 00:00:10,227,양평2나들목 보행통로 입구,9,2018-01-01 00:04:03,227,양평2나들목 보행통로 입구,9,3,50
1,SPB-03796,2018-01-01 00:00:42,2219,"고속터미널역 8-1번, 8-2번 출구 사이",15,2018-01-01 00:25:41,3511,응봉역 1번출구,9,24,7670
2,SPB-02402,2018-01-01 00:00:58,567,성수역 2번출구 앞,13,2018-01-01 00:09:33,3506,영동대교 북단,2,8,1390
3,SPB-01564,2018-01-01 00:01:02,568,청계8가사거리 부근,5,2018-01-01 00:10:13,521,왕십리역 11번 출구 앞,9,8,1820
4,SPB-05713,2018-01-01 00:01:03,361,동묘앞역 1번출구 뒤,4,2018-01-01 00:06:18,383,신당역 12번 출구 뒤,8,4,850

In [191]:
data19.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 784734 entries, 0 to 784733
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    784734 non-null  object
 1   대여일시     784734 non-null  object
 2   대여대여소번호  784734 non-null  object
 3   대여대여소명   784734 non-null  object
 4   대여거치대    784734 non-null  int64
 5   반납일시     784734 non-null  object
 6   반납대여소번호  784734 non-null  object
 7   반납대여소명   784734 non-null  object
 8   반납거치대    784734 non-null  int64
 9   이용시간     784734 non-null  int64
 10  이용거리     784734 non-null  int64
dtypes: int64(4), object(7)
memory usage: 65.9+ MB

In [192]:
data19.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [220]:
#data19.to_csv('./서울특별시 공공자전거 대여이력 정보_2018년_1분기1.csv', index = False, encoding ='cp949')

In [54]:
data20 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여이력 정보_2018년_2분기_1.csv', engine = 'python')
data20

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,'SPB-15882','2018-04-01 00:00:01','266',' 영등포청과시장 사거리',9,'2018-04-01 00:07:39','245',' 삼성생명 당산사옥 앞',1,7,1390
1,'SPB-06226','2018-04-01 00:00:16','1946',' 구로역 광장',1,'2018-04-01 00:44:38','1820',' 신한은행 시흥대로금융센터지점',1,44,9170
2,'SPB-03366','2018-04-01 00:00:17','1449',' 상봉역 1번출구',14,'2018-04-01 00:42:56','1433',' 중화역 2번출구',6,42,4700
3,'SPB-12878','2018-04-01 00:00:20','2034',' 사당역 7번출구쪽',18,'2018-04-01 00:34:22','2032',' 이수역 11번출구쪽',5,32,5430
4,'SPB-14075','2018-04-01 00:00:23','141',' 연대 대운동장 옆',15,'2018-04-01 00:10:59','172',' 서대문소방서',1,10,1960
...,...,...,...,...,...,...,...,...,...,...,...
677873,'SPB-05414','2018-04-30 23:59:49','1440',' 하나은행 면목지점',1,'2018-05-01 00:11:58','1414',' 사가정역 1번출구',7,11,1410
677874,'SPB-12151','2018-04-30 23:59:49','102',' 망원역 1번출구 앞',11,'2018-05-01 00:24:27','412',' DMC산학협력연구센터 앞',20,24,3540
677875,'SPB-06162','2018-04-30 23:59:50','102',' 망원역 1번출구 앞',17,'2018-05-01 00:24:39','412',' DMC산학협력연구센터 앞',18,24,4010
677876,'SPB-01613','2018-04-30 23:59:53','2050',' 노량진역 5번출구',6,'2018-05-01 00:12:19','2015',' 신대방삼거리역 6번출구쪽',10,12,2070
677877,'SPB-09328','2018-04-30 23:59:58','2063',' 대방역 4번출구',11,'2018-05-01 00:14:30','2054',' 삼익아파트',4,14,2090

In [194]:
data20["'자전거번호'"] = data20["'자전거번호'"].str.strip("''")
data20["'대여일시'"] = data20["'대여일시'"].str.strip("''")
data20["'대여대여소번호'"] = data20["'대여대여소번호'"].str.strip("''")
data20["'대여대여소명'"] = data20["'대여대여소명'"].str.strip("''")
data20["'반납일시'"] = data20["'반납일시'"].str.strip("''")
data20["'반납대여소번호'"] = data20["'반납대여소번호'"].str.strip("''")
data20["'반납대여소명'"]= data20["'반납대여소명'"].str.strip("''")
data20.head()

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,SPB-15882,2018-04-01 00:00:01,266,영등포청과시장 사거리,9,2018-04-01 00:07:39,245,삼성생명 당산사옥 앞,1,7,1390
1,SPB-06226,2018-04-01 00:00:16,1946,구로역 광장,1,2018-04-01 00:44:38,1820,신한은행 시흥대로금융센터지점,1,44,9170
2,SPB-03366,2018-04-01 00:00:17,1449,상봉역 1번출구,14,2018-04-01 00:42:56,1433,중화역 2번출구,6,42,4700
3,SPB-12878,2018-04-01 00:00:20,2034,사당역 7번출구쪽,18,2018-04-01 00:34:22,2032,이수역 11번출구쪽,5,32,5430
4,SPB-14075,2018-04-01 00:00:23,141,연대 대운동장 옆,15,2018-04-01 00:10:59,172,서대문소방서,1,10,1960

In [195]:
data20 = data20.rename(columns = {"'자전거번호'" : '자전거번호', "'대여일시'" : '대여일시', "'대여대여소번호'" : '대여대여소번호', 
                                "'대여대여소명'" : '대여대여소명', "'대여거치대'" : '대여거치대', "'반납일시'" : '반납일시',
                                "'반납대여소번호'" : '반납대여소번호', "'반납대여소명'" : '반납대여소명', "'반납거치대'" : '반납거치대',
                                "'이용시간(분)'" : '이용시간', "'이용거리(M)'" : '이용거리'})
data20.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15882,2018-04-01 00:00:01,266,영등포청과시장 사거리,9,2018-04-01 00:07:39,245,삼성생명 당산사옥 앞,1,7,1390
1,SPB-06226,2018-04-01 00:00:16,1946,구로역 광장,1,2018-04-01 00:44:38,1820,신한은행 시흥대로금융센터지점,1,44,9170
2,SPB-03366,2018-04-01 00:00:17,1449,상봉역 1번출구,14,2018-04-01 00:42:56,1433,중화역 2번출구,6,42,4700
3,SPB-12878,2018-04-01 00:00:20,2034,사당역 7번출구쪽,18,2018-04-01 00:34:22,2032,이수역 11번출구쪽,5,32,5430
4,SPB-14075,2018-04-01 00:00:23,141,연대 대운동장 옆,15,2018-04-01 00:10:59,172,서대문소방서,1,10,1960

In [221]:
data20['대여대여소명'] = data20['대여대여소명'].str.strip()
data20['반납대여소명'] = data20['반납대여소명'].str.strip()
data20.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15882,2018-04-01 00:00:01,266,영등포청과시장 사거리,9,2018-04-01 00:07:39,245,삼성생명 당산사옥 앞,1,7,1390
1,SPB-06226,2018-04-01 00:00:16,1946,구로역 광장,1,2018-04-01 00:44:38,1820,신한은행 시흥대로금융센터지점,1,44,9170
2,SPB-03366,2018-04-01 00:00:17,1449,상봉역 1번출구,14,2018-04-01 00:42:56,1433,중화역 2번출구,6,42,4700
3,SPB-12878,2018-04-01 00:00:20,2034,사당역 7번출구쪽,18,2018-04-01 00:34:22,2032,이수역 11번출구쪽,5,32,5430
4,SPB-14075,2018-04-01 00:00:23,141,연대 대운동장 옆,15,2018-04-01 00:10:59,172,서대문소방서,1,10,1960

In [196]:
data20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677878 entries, 0 to 677877
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    677878 non-null  object
 1   대여일시     677878 non-null  object
 2   대여대여소번호  677878 non-null  object
 3   대여대여소명   677878 non-null  object
 4   대여거치대    677878 non-null  int64
 5   반납일시     677878 non-null  object
 6   반납대여소번호  677878 non-null  object
 7   반납대여소명   677878 non-null  object
 8   반납거치대    677878 non-null  int64
 9   이용시간     677878 non-null  int64
 10  이용거리     677878 non-null  int64
dtypes: int64(4), object(7)
memory usage: 56.9+ MB

In [197]:
data20.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [222]:
#data20.to_csv('./서울특별시 공공자전거 대여이력 정보_2018년_2분기_1.csv', index = False, encoding ='cp949')

In [55]:
data21 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여이력 정보_2018년_2분기_2.csv', engine = 'python')
data21

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,'SPB-06801','2018-05-01 00:00:00','179',' 가좌역 4번출구 앞',9,'2018-05-01 00:15:18','166',' 가재울 초등학교',1,15,2630
1,'SPB-12967','2018-05-01 00:00:01','647',' 신이문역 1번출구',1,'2018-05-01 00:07:49','634',' 외국어대 정문 앞',1,7,1340
2,'SPB-07435','2018-05-01 00:00:04','1611',' 과기대 입구(우)',10,'2018-05-01 01:43:58','1611',' 과기대 입구(우)',8,99,13490
3,'SPB-12710','2018-05-01 00:00:06','2167',' 낙성대역 1번출구',6,'2018-05-01 00:11:37','2129',' 낙성대 과학전시관',10,11,1460
4,'SPB-13000','2018-05-01 00:00:06','2140',' 신림1교 교차로',3,'2018-05-01 00:12:55','2139',' 서울신성초등학교',10,11,1520
...,...,...,...,...,...,...,...,...,...,...,...
951441,'SPB-11311','2018-05-31 23:59:47','178',' 증산3교 앞',5,'2018-06-01 00:03:03','177',' 북가좌 초등학교',1,3,280
951442,'SPB-05327','2018-05-31 23:59:48','1601',' 석계역 문화광장 내 자전거 보관소',16,'2018-06-01 00:06:17','1333',' 석관초등학교 앞',2,6,890
951443,'SPB-09961','2018-05-31 23:59:52','562',' 군자지하보도 앞',4,'2018-06-01 00:44:25','1448',' 코스트코 상봉점',7,42,7550
951444,'SPB-09284','2018-05-31 23:59:57','1663',' 동해문화예술관앞',4,'2018-06-01 00:19:22','1320',' 종암 농협지점 앞',8,18,3680
951445,'SPB-05972','2018-05-31 23:59:59','1601',' 석계역 문화광장 내 자전거 보관소',15,'2018-06-01 00:28:34','1709',' 쌍문역4번출구 주변',1,28,6490

In [199]:
data21["'자전거번호'"] = data21["'자전거번호'"].str.strip("''")
data21["'대여일시'"] = data21["'대여일시'"].str.strip("''")
data21["'대여대여소번호'"] = data21["'대여대여소번호'"].str.strip("''")
data21["'대여대여소명'"] = data21["'대여대여소명'"].str.strip("''")
data21["'반납일시'"] = data21["'반납일시'"].str.strip("''")
data21["'반납대여소번호'"] = data21["'반납대여소번호'"].str.strip("''")
data21["'반납대여소명'"]= data21["'반납대여소명'"].str.strip("''")
data21.head()

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,SPB-06801,2018-05-01 00:00:00,179,가좌역 4번출구 앞,9,2018-05-01 00:15:18,166,가재울 초등학교,1,15,2630
1,SPB-12967,2018-05-01 00:00:01,647,신이문역 1번출구,1,2018-05-01 00:07:49,634,외국어대 정문 앞,1,7,1340
2,SPB-07435,2018-05-01 00:00:04,1611,과기대 입구(우),10,2018-05-01 01:43:58,1611,과기대 입구(우),8,99,13490
3,SPB-12710,2018-05-01 00:00:06,2167,낙성대역 1번출구,6,2018-05-01 00:11:37,2129,낙성대 과학전시관,10,11,1460
4,SPB-13000,2018-05-01 00:00:06,2140,신림1교 교차로,3,2018-05-01 00:12:55,2139,서울신성초등학교,10,11,1520

In [200]:
data21 = data21.rename(columns = {"'자전거번호'" : '자전거번호', "'대여일시'" : '대여일시', "'대여대여소번호'" : '대여대여소번호', 
                                "'대여대여소명'" : '대여대여소명', "'대여거치대'" : '대여거치대', "'반납일시'" : '반납일시',
                                "'반납대여소번호'" : '반납대여소번호', "'반납대여소명'" : '반납대여소명', "'반납거치대'" : '반납거치대',
                                "'이용시간(분)'" : '이용시간', "'이용거리(M)'" : '이용거리'})
data21.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06801,2018-05-01 00:00:00,179,가좌역 4번출구 앞,9,2018-05-01 00:15:18,166,가재울 초등학교,1,15,2630
1,SPB-12967,2018-05-01 00:00:01,647,신이문역 1번출구,1,2018-05-01 00:07:49,634,외국어대 정문 앞,1,7,1340
2,SPB-07435,2018-05-01 00:00:04,1611,과기대 입구(우),10,2018-05-01 01:43:58,1611,과기대 입구(우),8,99,13490
3,SPB-12710,2018-05-01 00:00:06,2167,낙성대역 1번출구,6,2018-05-01 00:11:37,2129,낙성대 과학전시관,10,11,1460
4,SPB-13000,2018-05-01 00:00:06,2140,신림1교 교차로,3,2018-05-01 00:12:55,2139,서울신성초등학교,10,11,1520

In [223]:
data21['대여대여소명'] = data21['대여대여소명'].str.strip()
data21['반납대여소명'] = data21['반납대여소명'].str.strip()
data21.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06801,2018-05-01 00:00:00,179,가좌역 4번출구 앞,9,2018-05-01 00:15:18,166,가재울 초등학교,1,15,2630
1,SPB-12967,2018-05-01 00:00:01,647,신이문역 1번출구,1,2018-05-01 00:07:49,634,외국어대 정문 앞,1,7,1340
2,SPB-07435,2018-05-01 00:00:04,1611,과기대 입구(우),10,2018-05-01 01:43:58,1611,과기대 입구(우),8,99,13490
3,SPB-12710,2018-05-01 00:00:06,2167,낙성대역 1번출구,6,2018-05-01 00:11:37,2129,낙성대 과학전시관,10,11,1460
4,SPB-13000,2018-05-01 00:00:06,2140,신림1교 교차로,3,2018-05-01 00:12:55,2139,서울신성초등학교,10,11,1520

In [201]:
data21.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 951446 entries, 0 to 951445
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    951446 non-null  object
 1   대여일시     951446 non-null  object
 2   대여대여소번호  951446 non-null  object
 3   대여대여소명   951446 non-null  object
 4   대여거치대    951446 non-null  int64
 5   반납일시     951446 non-null  object
 6   반납대여소번호  951446 non-null  object
 7   반납대여소명   951446 non-null  object
 8   반납거치대    951446 non-null  int64
 9   이용시간     951446 non-null  int64
 10  이용거리     951446 non-null  int64
dtypes: int64(4), object(7)
memory usage: 79.8+ MB

In [202]:
data21.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [224]:
#data21.to_csv('./서울특별시 공공자전거 대여이력 정보_2018년_2분기_2.csv', index = False, encoding ='cp949')

In [56]:
data22 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여이력 정보_2018년_2분기_3.csv', engine = 'python')
data22

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,'SPB-06782','2018-06-01 00:00:02','1952',' 천왕연지타운2단지 앞',2,'2018-06-01 00:15:13','1969',' 궁동생태공원',10,14,3060
1,'SPB-04511','2018-06-01 00:00:08','1446',' 중랑전화국 교차로',8,'2018-06-01 00:19:01','1456',' 상아빌딩(우림시장 교차로)',3,18,2070
2,'SPB-10103','2018-06-01 00:00:08','2244','교육개발원입구 교차로',13,'2018-06-01 00:34:08','2276',' 영동1교 (양재천근린공원)',15,32,2750
3,'SPB-06223','2018-06-01 00:00:13','349',' 사직동주민센터',1,'2018-06-01 00:06:39','348',' 독립문역 사거리',4,6,1090
4,'SPB-06325','2018-06-01 00:00:15','504',' 신자초교입구교차로',2,'2018-06-01 00:16:36','551',' 구의삼성쉐르빌 앞',3,16,2200
...,...,...,...,...,...,...,...,...,...,...,...
566854,'SPB-17268','2018-06-15 23:59:50','813',' 삼각지역 3번출구',20,'2018-06-16 00:44:51','188',' 홍은동 정원여중 입구',5,44,9270
566855,'SPB-12494','2018-06-15 23:59:53','334',' 종로3가역 2번출구 뒤',3,'2018-06-16 00:10:42','340',' 혜화동 로터리',3,10,2450
566856,'SPB-14821','2018-06-15 23:59:53','1244',' 문정 법조단지8',1,'2018-06-16 00:22:45','2344',' 리엔파크 2단지 앞',3,22,3250
566857,'SPB-09282','2018-06-15 23:59:55','1703',' 도봉산광역환승센터앞 ',10,'2018-06-16 00:53:15','650',' 중랑교사거리',6,50,12160
566858,'SPB-06087','2018-06-15 23:59:59','818',' 숙명여대 입구 교차로',2,'2018-06-16 00:06:35','820',' 청파동입구 교차로',6,6,710

In [204]:
data22["'자전거번호'"] = data22["'자전거번호'"].str.strip("''")
data22["'대여일시'"] = data22["'대여일시'"].str.strip("''")
data22["'대여대여소번호'"] = data22["'대여대여소번호'"].str.strip("''")
data22["'대여대여소명'"] = data22["'대여대여소명'"].str.strip("''")
data22["'반납일시'"] = data22["'반납일시'"].str.strip("''")
data22["'반납대여소번호'"] = data22["'반납대여소번호'"].str.strip("''")
data22["'반납대여소명'"]= data22["'반납대여소명'"].str.strip("''")
data22.head()

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,SPB-06782,2018-06-01 00:00:02,1952,천왕연지타운2단지 앞,2,2018-06-01 00:15:13,1969,궁동생태공원,10,14,3060
1,SPB-04511,2018-06-01 00:00:08,1446,중랑전화국 교차로,8,2018-06-01 00:19:01,1456,상아빌딩(우림시장 교차로),3,18,2070
2,SPB-10103,2018-06-01 00:00:08,2244,교육개발원입구 교차로,13,2018-06-01 00:34:08,2276,영동1교 (양재천근린공원),15,32,2750
3,SPB-06223,2018-06-01 00:00:13,349,사직동주민센터,1,2018-06-01 00:06:39,348,독립문역 사거리,4,6,1090
4,SPB-06325,2018-06-01 00:00:15,504,신자초교입구교차로,2,2018-06-01 00:16:36,551,구의삼성쉐르빌 앞,3,16,2200

In [206]:
data22 = data22.rename(columns = {"'자전거번호'" : '자전거번호', "'대여일시'" : '대여일시', "'대여대여소번호'" : '대여대여소번호', 
                                "'대여대여소명'" : '대여대여소명', "'대여거치대'" : '대여거치대', "'반납일시'" : '반납일시',
                                "'반납대여소번호'" : '반납대여소번호', "'반납대여소명'" : '반납대여소명', "'반납거치대'" : '반납거치대',
                                "'이용시간(분)'" : '이용시간', "'이용거리(M)'" : '이용거리'})
data22.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06782,2018-06-01 00:00:02,1952,천왕연지타운2단지 앞,2,2018-06-01 00:15:13,1969,궁동생태공원,10,14,3060
1,SPB-04511,2018-06-01 00:00:08,1446,중랑전화국 교차로,8,2018-06-01 00:19:01,1456,상아빌딩(우림시장 교차로),3,18,2070
2,SPB-10103,2018-06-01 00:00:08,2244,교육개발원입구 교차로,13,2018-06-01 00:34:08,2276,영동1교 (양재천근린공원),15,32,2750
3,SPB-06223,2018-06-01 00:00:13,349,사직동주민센터,1,2018-06-01 00:06:39,348,독립문역 사거리,4,6,1090
4,SPB-06325,2018-06-01 00:00:15,504,신자초교입구교차로,2,2018-06-01 00:16:36,551,구의삼성쉐르빌 앞,3,16,2200

In [225]:
data22['대여대여소명'] = data22['대여대여소명'].str.strip()
data22['반납대여소명'] = data22['반납대여소명'].str.strip()
data22.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06782,2018-06-01 00:00:02,1952,천왕연지타운2단지 앞,2,2018-06-01 00:15:13,1969,궁동생태공원,10,14,3060
1,SPB-04511,2018-06-01 00:00:08,1446,중랑전화국 교차로,8,2018-06-01 00:19:01,1456,상아빌딩(우림시장 교차로),3,18,2070
2,SPB-10103,2018-06-01 00:00:08,2244,교육개발원입구 교차로,13,2018-06-01 00:34:08,2276,영동1교 (양재천근린공원),15,32,2750
3,SPB-06223,2018-06-01 00:00:13,349,사직동주민센터,1,2018-06-01 00:06:39,348,독립문역 사거리,4,6,1090
4,SPB-06325,2018-06-01 00:00:15,504,신자초교입구교차로,2,2018-06-01 00:16:36,551,구의삼성쉐르빌 앞,3,16,2200

In [207]:
data22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566859 entries, 0 to 566858
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    566859 non-null  object
 1   대여일시     566859 non-null  object
 2   대여대여소번호  566859 non-null  object
 3   대여대여소명   566859 non-null  object
 4   대여거치대    566859 non-null  int64
 5   반납일시     566859 non-null  object
 6   반납대여소번호  566859 non-null  object
 7   반납대여소명   566859 non-null  object
 8   반납거치대    566859 non-null  int64
 9   이용시간     566859 non-null  int64
 10  이용거리     566859 non-null  int64
dtypes: int64(4), object(7)
memory usage: 47.6+ MB

In [208]:
data22.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [226]:
#data22.to_csv('./서울특별시 공공자전거 대여이력 정보_2018년_2분기_3.csv', index = False, encoding ='cp949')

In [57]:
data23 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여이력 정보_2018년_2분기_4.csv', engine = 'python')
data23

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,'SPB-11906','2018-06-16 00:00:07','932',' 예일여중',1,'2018-06-16 00:16:41','934',' 신사동 성당',11,15,2160
1,'SPB-16954','2018-06-16 00:00:07','272',' 당산육갑문',16,'2018-06-16 02:00:36','1827',' 독산보도육교 앞 자전거 보관소',9,120,18100
2,'SPB-09676','2018-06-16 00:00:11','1036',' 고덕동 주양쇼핑',7,'2018-06-16 00:24:05','1038',' 강일 다솜 어린이 공원',9,23,3350
3,'SPB-07143','2018-06-16 00:00:15','1726',' 삼익세라믹아파트교차로',7,'2018-06-16 00:15:31','1706',' 기업은행 앞',9,14,1480
4,'SPB-13007','2018-06-16 00:00:16','2058',' 노량진동 맥도널드앞',10,'2018-06-16 00:14:25','258',' 신길역3번출구',8,13,2920
...,...,...,...,...,...,...,...,...,...,...,...
586299,'SPB-15985','2018-06-30 23:59:55','505',' 자양사거리 광진아크로텔 앞',9,'2018-07-01 00:09:38','593','자양중앙나들목',5,9,1230
586300,'SPB-15081','2018-06-30 23:59:55','1328',' 월곡역 3번출구',7,'2018-07-01 00:18:02','647',' 신이문역 1번출구',7,17,3600
586301,'SPB-13677','2018-06-30 23:59:57','2376',' 수서역 6번출구 앞',2,'2018-07-01 00:20:38','2387',' 래미안강남힐즈 사거리',5,20,2590
586302,'SPB-06577','2018-06-30 23:59:57','1251',' 석촌역 2번출구',2,'2018-07-01 00:57:29','1245',' 문정 법조단지9',4,57,6640
586303,'SPB-03842','2018-06-30 23:59:58','2169',' 봉천역 2번출구',6,'2018-07-01 00:08:05','2112',' 서울대입구역 마에스트로',7,7,910

In [210]:
data23["'자전거번호'"] = data23["'자전거번호'"].str.strip("''")
data23["'대여일시'"] = data23["'대여일시'"].str.strip("''")
data23["'대여대여소번호'"] = data23["'대여대여소번호'"].str.strip("''")
data23["'대여대여소명'"] = data23["'대여대여소명'"].str.strip("''")
data23["'반납일시'"] = data23["'반납일시'"].str.strip("''")
data23["'반납대여소번호'"] = data23["'반납대여소번호'"].str.strip("''")
data23["'반납대여소명'"]= data23["'반납대여소명'"].str.strip("''")
data23.head()

,'자전거번호','대여일시','대여대여소번호','대여대여소명','대여거치대','반납일시','반납대여소번호','반납대여소명','반납거치대','이용시간(분)','이용거리(M)'
0,SPB-11906,2018-06-16 00:00:07,932,예일여중,1,2018-06-16 00:16:41,934,신사동 성당,11,15,2160
1,SPB-16954,2018-06-16 00:00:07,272,당산육갑문,16,2018-06-16 02:00:36,1827,독산보도육교 앞 자전거 보관소,9,120,18100
2,SPB-09676,2018-06-16 00:00:11,1036,고덕동 주양쇼핑,7,2018-06-16 00:24:05,1038,강일 다솜 어린이 공원,9,23,3350
3,SPB-07143,2018-06-16 00:00:15,1726,삼익세라믹아파트교차로,7,2018-06-16 00:15:31,1706,기업은행 앞,9,14,1480
4,SPB-13007,2018-06-16 00:00:16,2058,노량진동 맥도널드앞,10,2018-06-16 00:14:25,258,신길역3번출구,8,13,2920

In [211]:
data23 = data23.rename(columns = {"'자전거번호'" : '자전거번호', "'대여일시'" : '대여일시', "'대여대여소번호'" : '대여대여소번호', 
                                "'대여대여소명'" : '대여대여소명', "'대여거치대'" : '대여거치대', "'반납일시'" : '반납일시',
                                "'반납대여소번호'" : '반납대여소번호', "'반납대여소명'" : '반납대여소명', "'반납거치대'" : '반납거치대',
                                "'이용시간(분)'" : '이용시간', "'이용거리(M)'" : '이용거리'})
data23.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-11906,2018-06-16 00:00:07,932,예일여중,1,2018-06-16 00:16:41,934,신사동 성당,11,15,2160
1,SPB-16954,2018-06-16 00:00:07,272,당산육갑문,16,2018-06-16 02:00:36,1827,독산보도육교 앞 자전거 보관소,9,120,18100
2,SPB-09676,2018-06-16 00:00:11,1036,고덕동 주양쇼핑,7,2018-06-16 00:24:05,1038,강일 다솜 어린이 공원,9,23,3350
3,SPB-07143,2018-06-16 00:00:15,1726,삼익세라믹아파트교차로,7,2018-06-16 00:15:31,1706,기업은행 앞,9,14,1480
4,SPB-13007,2018-06-16 00:00:16,2058,노량진동 맥도널드앞,10,2018-06-16 00:14:25,258,신길역3번출구,8,13,2920

In [227]:
data23['대여대여소명'] = data23['대여대여소명'].str.strip()
data23['반납대여소명'] = data23['반납대여소명'].str.strip()
data23.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-11906,2018-06-16 00:00:07,932,예일여중,1,2018-06-16 00:16:41,934,신사동 성당,11,15,2160
1,SPB-16954,2018-06-16 00:00:07,272,당산육갑문,16,2018-06-16 02:00:36,1827,독산보도육교 앞 자전거 보관소,9,120,18100
2,SPB-09676,2018-06-16 00:00:11,1036,고덕동 주양쇼핑,7,2018-06-16 00:24:05,1038,강일 다솜 어린이 공원,9,23,3350
3,SPB-07143,2018-06-16 00:00:15,1726,삼익세라믹아파트교차로,7,2018-06-16 00:15:31,1706,기업은행 앞,9,14,1480
4,SPB-13007,2018-06-16 00:00:16,2058,노량진동 맥도널드앞,10,2018-06-16 00:14:25,258,신길역3번출구,8,13,2920

In [212]:
data23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 586304 entries, 0 to 586303
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    586304 non-null  object
 1   대여일시     586304 non-null  object
 2   대여대여소번호  586304 non-null  object
 3   대여대여소명   586304 non-null  object
 4   대여거치대    586304 non-null  int64
 5   반납일시     586304 non-null  object
 6   반납대여소번호  586304 non-null  object
 7   반납대여소명   586304 non-null  object
 8   반납거치대    586304 non-null  int64
 9   이용시간     586304 non-null  int64
 10  이용거리     586304 non-null  int64
dtypes: int64(4), object(7)
memory usage: 49.2+ MB

In [213]:
data23.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [228]:
#data23.to_csv('./서울특별시 공공자전거 대여이력 정보_2018년_2분기_4.csv', index = False, encoding ='cp949')

In [2]:
data24 = pd.read_excel('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201807_01.xlsx')
data24

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16427,2018-07-01 00:00:30,2226,신동아럭스빌아파트 앞,7,2018-07-01 00:03:59,2225,백석예술대학교 제3캠퍼스 앞,9,3,570
1,SPB-14104,2018-07-01 00:01:29,129,신촌역(2호선) 6번출구 옆,5,2018-07-01 00:04:57,125,서강대 남문 옆,9,3,660
2,SPB-06808,2018-07-01 00:02:19,1351,안암2교 옆,2,2018-07-01 00:05:00,1351,안암2교 옆,2,2,20
3,SPB-11154,2018-07-01 00:00:43,954,은평뉴타운구파발9단지,3,2018-07-01 00:05:14,903,은평뉴타운 아이파크,8,4,680
4,SPB-10458,2018-07-01 00:02:35,623,서울시립대 정문 앞,12,2018-07-01 00:05:27,623,서울시립대 정문 앞,8,2,10
...,...,...,...,...,...,...,...,...,...,...,...
1048570,SPB-17211,2018-07-30 20:52:09,2220,반포본동 주민센터 앞,4,2018-07-30 22:23:38,2220,반포본동 주민센터 앞,4,91,21930
1048571,SPB-18442,2018-07-30 22:10:36,1215,올림픽공원역 1번출구 앞,14,2018-07-30 22:23:38,1214,오금역 7번 출구 인근,8,12,2030
1048572,SPB-14058,2018-07-30 21:24:00,1601,석계역 문화광장 내 자전거 보관소,3,2018-07-30 22:23:39,1601,석계역 문화광장 내 자전거 보관소,4,59,9040
1048573,SPB-11997,2018-07-30 22:10:48,589,성수역3번출구,8,2018-07-30 22:23:40,509,이마트 버스정류소 옆,7,13,1210
1048574,SPB-15359,2018-07-30 21:25:14,1943,온수역 북측,7,2018-07-30 22:23:43,1943,온수역 북측,7,58,4550

In [3]:
data24 = data24.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data24.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16427,2018-07-01 00:00:30,2226,신동아럭스빌아파트 앞,7,2018-07-01 00:03:59,2225,백석예술대학교 제3캠퍼스 앞,9,3,570
1,SPB-14104,2018-07-01 00:01:29,129,신촌역(2호선) 6번출구 옆,5,2018-07-01 00:04:57,125,서강대 남문 옆,9,3,660
2,SPB-06808,2018-07-01 00:02:19,1351,안암2교 옆,2,2018-07-01 00:05:00,1351,안암2교 옆,2,2,20
3,SPB-11154,2018-07-01 00:00:43,954,은평뉴타운구파발9단지,3,2018-07-01 00:05:14,903,은평뉴타운 아이파크,8,4,680
4,SPB-10458,2018-07-01 00:02:35,623,서울시립대 정문 앞,12,2018-07-01 00:05:27,623,서울시립대 정문 앞,8,2,10

In [4]:
data24.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 11 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   자전거번호    1048575 non-null  object
 1   대여일시     1048575 non-null  datetime64[ns]
 2   대여소번호    1048575 non-null  int64
 3   대여대여소명   1048575 non-null  object
 4   대여거치대    1048575 non-null  int64
 5   반납일시     1048575 non-null  datetime64[ns]
 6   반납대여소번호  1048575 non-null  int64
 7   반납대여소명   1048575 non-null  object
 8   반납거치대    1048575 non-null  int64
 9   이용시간     1048575 non-null  int64
 10  이용거리     1048575 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 88.0+ MB

In [5]:
data24.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [9]:
#data24.to_excel('./서울특별시 공공자전거 대여정보_201807_01.xlsx', index = False)

In [10]:
data25 = pd.read_excel('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201807_02.xlsx')
data25

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12284,2018-07-30 21:25:44,630,동대문구 보건소,10,2018-07-30 21:28:38,641,용두역 4번출구,1,2,340
1,SPB-11173,2018-07-30 21:26:05,168,남가좌동 사거리,5,2018-07-30 21:29:03,170,가재울 뉴타운 주유소 옆,9,3,540
2,SPB-06280,2018-07-30 21:26:49,1708,보건소사거리(다비치안경창동점),5,2018-07-30 21:29:26,1707,도봉구민회관,12,2,330
3,SPB-16456,2018-07-30 21:25:57,310,청계광장 옆,1,2018-07-30 21:29:29,312,시청역 1번출구 뒤,5,3,520
4,SPB-14453,2018-07-30 21:25:10,1308,안암로터리 버스정류장 앞,5,2018-07-30 21:29:37,1351,안암2교 옆,3,3,580
...,...,...,...,...,...,...,...,...,...,...,...
41302,SPB-09771,2018-07-31 23:30:17,1661,당현천근린공원,4,2018-08-01 05:21:17,1661,당현천근린공원,2,93,7560
41303,SPB-14425,2018-07-31 22:04:24,2003,사육신공원앞,7,2018-08-01 07:19:14,257,신길삼거리(우리은행),8,554,3020
41304,SPB-07946,2018-07-31 23:29:01,1911,구로디지털단지역 앞,6,2018-08-01 08:50:58,2107,도림천 신화교,25,49,3930
41305,SPB-10990,2018-07-31 23:46:37,704,남부법원검찰청 교차로,9,2018-08-01 09:26:41,716,신정6동 주민센터 인근,10,19,3270
41306,SPB-12546,2018-07-31 21:55:23,950,구산역 2번 출구,3,2018-08-01 10:51:16,900,은평예술회관,6,236,67710

In [11]:
data25 = data25.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data25.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12284,2018-07-30 21:25:44,630,동대문구 보건소,10,2018-07-30 21:28:38,641,용두역 4번출구,1,2,340
1,SPB-11173,2018-07-30 21:26:05,168,남가좌동 사거리,5,2018-07-30 21:29:03,170,가재울 뉴타운 주유소 옆,9,3,540
2,SPB-06280,2018-07-30 21:26:49,1708,보건소사거리(다비치안경창동점),5,2018-07-30 21:29:26,1707,도봉구민회관,12,2,330
3,SPB-16456,2018-07-30 21:25:57,310,청계광장 옆,1,2018-07-30 21:29:29,312,시청역 1번출구 뒤,5,3,520
4,SPB-14453,2018-07-30 21:25:10,1308,안암로터리 버스정류장 앞,5,2018-07-30 21:29:37,1351,안암2교 옆,3,3,580

In [12]:
data25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41307 entries, 0 to 41306
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   자전거번호    41307 non-null  object
 1   대여일시     41307 non-null  datetime64[ns]
 2   대여소번호    41307 non-null  int64
 3   대여대여소명   41307 non-null  object
 4   대여거치대    41307 non-null  int64
 5   반납일시     41307 non-null  datetime64[ns]
 6   반납대여소번호  41307 non-null  int64
 7   반납대여소명   41307 non-null  object
 8   반납거치대    41307 non-null  int64
 9   이용시간     41307 non-null  int64
 10  이용거리     41307 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 3.5+ MB

In [13]:
data25.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [16]:
#data25.to_excel('./서울특별시 공공자전거 대여정보_201807_02.xlsx', index = False)

In [17]:
data26 = pd.read_excel('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201808.xlsx')
data26

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06960,2018-08-01 00:00:50,130,신촌역(2호선) 7번출구 앞,8,2018-08-01 00:03:33,130,신촌역(2호선) 7번출구 앞,5,2,170
1,SPB-08793,2018-08-01 00:00:35,579,마장역 4번출구,3,2018-08-01 00:03:53,558,성동광진 교육지원청 앞,16,2,630
2,SPB-01292,2018-08-01 00:01:38,2255,시민의숲역 1번출구 옆,25,2018-08-01 00:04:48,2251,더케이호텔 입구(양재2),2,2,550
3,SPB-10915,2018-08-01 00:01:11,1668,중계역 6번출구,5,2018-08-01 00:04:55,1623,노원 구민회관,2,3,44340
4,SPB-06320,2018-08-01 00:02:15,1984,구로구청,3,2018-08-01 00:05:22,1913,구로리공원,1,2,580
...,...,...,...,...,...,...,...,...,...,...,...
1026088,SPB-06728,2018-08-31 22:02:16,3518,군자역 7번출구뒤,4,2018-09-01 07:45:14,1617,하계동 중평어린이공원 앞,12,70,12420
1026089,SPB-18189,2018-08-31 19:52:06,406,상암월드컵파크 7단지 앞,9,2018-09-01 07:53:36,401,상암월드컵파크 10단지 앞,9,721,1170
1026090,SPB-05543,2018-08-31 23:18:13,146,마포역 2번출구 뒤,1,2018-09-01 09:08:21,160,북아현동 가구거리,13,589,0
1026091,SPB-15449,2018-08-31 18:33:47,2294,두상빌딩 앞,13,2018-09-01 12:46:08,2244,교육개발원입구 교차로,19,1092,1880
1026092,SPB-09528,2018-08-31 23:15:02,1019,다성이즈빌아파트(호원대 대각선 맞은편),6,2018-09-01 16:04:56,1020,강동경찰서,14,205,8560

In [18]:
data26 = data26.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data26.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06960,2018-08-01 00:00:50,130,신촌역(2호선) 7번출구 앞,8,2018-08-01 00:03:33,130,신촌역(2호선) 7번출구 앞,5,2,170
1,SPB-08793,2018-08-01 00:00:35,579,마장역 4번출구,3,2018-08-01 00:03:53,558,성동광진 교육지원청 앞,16,2,630
2,SPB-01292,2018-08-01 00:01:38,2255,시민의숲역 1번출구 옆,25,2018-08-01 00:04:48,2251,더케이호텔 입구(양재2),2,2,550
3,SPB-10915,2018-08-01 00:01:11,1668,중계역 6번출구,5,2018-08-01 00:04:55,1623,노원 구민회관,2,3,44340
4,SPB-06320,2018-08-01 00:02:15,1984,구로구청,3,2018-08-01 00:05:22,1913,구로리공원,1,2,580

In [19]:
data26.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1026093 entries, 0 to 1026092
Data columns (total 11 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   자전거번호    1026093 non-null  object
 1   대여일시     1026093 non-null  datetime64[ns]
 2   대여소번호    1026093 non-null  int64
 3   대여대여소명   1026093 non-null  object
 4   대여거치대    1026093 non-null  int64
 5   반납일시     1026093 non-null  datetime64[ns]
 6   반납대여소번호  1026093 non-null  int64
 7   반납대여소명   1026093 non-null  object
 8   반납거치대    1026093 non-null  int64
 9   이용시간     1026093 non-null  int64
 10  이용거리     1026093 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 86.1+ MB

In [20]:
data26.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [22]:
#data26.to_excel('./서울특별시 공공자전거 대여정보_201808.xlsx', index = False)

In [23]:
data27 = pd.read_excel('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201809_1.xlsx')
data27

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16278,2018-09-01 00:01:14,1355,보문2교,4,2018-09-01 00:04:14,1338,용문2교 옆,15,2,310
1,SPB-07017,2018-09-01 00:00:08,1914,대림역4번출구,5,2018-09-01 00:05:03,1985,구로도서관,20,4,470
2,SPB-00857,2018-09-01 00:02:42,144,공덕역 8번출구,1,2018-09-01 00:05:04,144,공덕역 8번출구,1,2,0
3,SPB-16272,2018-09-01 00:01:04,1119,염창동 한마음아파트앞(염창동 빛나는 음악학원앞),1,2018-09-01 00:05:08,1115,등촌역 1번출구옆,5,3,510
4,SPB-11204,2018-09-01 00:00:01,559,왕십리역 4번 출구 건너편,10,2018-09-01 00:05:12,537,한양대후문역 부근,9,5,880
...,...,...,...,...,...,...,...,...,...,...,...
1048570,SPB-14310,2018-09-23 20:39:16,1531,미아사거리 1번 출구,1,2018-09-23 20:56:52,1535,효성인텔리안 앞,3,17,2900
1048571,SPB-17308,2018-09-23 19:43:49,2311,학동로 래미안 아파트 앞,6,2018-09-23 20:56:52,1264,천호역 10번 출구 앞,3,72,11670
1048572,SPB-10318,2018-09-23 20:29:23,211,여의도역 4번출구 옆,11,2018-09-23 20:56:53,247,당산역 10번출구 앞,14,27,4590
1048573,SPB-18216,2018-09-23 20:17:55,2206,언남초등학교 앞,4,2018-09-23 20:56:54,2206,언남초등학교 앞,5,38,6940
1048574,SPB-07388,2018-09-23 20:45:01,1009,천호역4번출구(현대백화점),8,2018-09-23 20:56:54,1047,건강보험 강동지사kt,2,11,1290

In [24]:
data27 = data27.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data27.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16278,2018-09-01 00:01:14,1355,보문2교,4,2018-09-01 00:04:14,1338,용문2교 옆,15,2,310
1,SPB-07017,2018-09-01 00:00:08,1914,대림역4번출구,5,2018-09-01 00:05:03,1985,구로도서관,20,4,470
2,SPB-00857,2018-09-01 00:02:42,144,공덕역 8번출구,1,2018-09-01 00:05:04,144,공덕역 8번출구,1,2,0
3,SPB-16272,2018-09-01 00:01:04,1119,염창동 한마음아파트앞(염창동 빛나는 음악학원앞),1,2018-09-01 00:05:08,1115,등촌역 1번출구옆,5,3,510
4,SPB-11204,2018-09-01 00:00:01,559,왕십리역 4번 출구 건너편,10,2018-09-01 00:05:12,537,한양대후문역 부근,9,5,880

In [25]:
data27.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 11 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   자전거번호    1048575 non-null  object
 1   대여일시     1048575 non-null  datetime64[ns]
 2   대여소번호    1048575 non-null  int64
 3   대여대여소명   1048575 non-null  object
 4   대여거치대    1048575 non-null  int64
 5   반납일시     1048575 non-null  datetime64[ns]
 6   반납대여소번호  1048575 non-null  int64
 7   반납대여소명   1048575 non-null  object
 8   반납거치대    1048575 non-null  int64
 9   이용시간     1048575 non-null  int64
 10  이용거리     1048575 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 88.0+ MB

In [26]:
data27.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [28]:
#data27.to_excel('./서울특별시 공공자전거 대여정보_201809_1.xlsx', index = False)

In [29]:
data28 = pd.read_excel('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201809_2.xlsx')
data28

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-11299,2018-09-23 20:46:05,125,서강대 남문 옆,2,2018-09-23 20:50:02,129,신촌역(2호선) 6번출구 옆,9,4,670
1,SPB-14425,2018-09-23 20:46:03,1518,SK telecom(수유직영점) 앞,9,2018-09-23 20:50:12,1512,강북중학교 앞,19,3,1150
2,SPB-05366,2018-09-23 20:47:55,3501,광진구청 앞,3,2018-09-23 20:50:20,3520,광진경찰서,5,2,360
3,SPB-05791,2018-09-23 20:45:33,2307,압구정 한양 3차 아파트,1,2018-09-23 20:50:20,2307,압구정 한양 3차 아파트,1,4,360
4,SPB-18318,2018-09-23 20:47:01,591,건국대학교 (행정관),1,2018-09-23 20:50:30,503,더샵스타시티 C동 앞,15,3,850
...,...,...,...,...,...,...,...,...,...,...,...
385062,SPB-13770,2018-09-30 23:59:12,106,합정역 7번출구 앞,3,2018-10-01 03:43:04,248,초원아파트 앞,4,223,7730
385063,SPB-06362,2018-09-30 22:47:39,1208,풍납현대아파트쉼터,3,2018-10-01 05:49:59,1208,풍납현대아파트쉼터,10,422,0
385064,SPB-12767,2018-09-30 22:02:56,2222,사당역 12번출구 뒤,1,2018-10-01 06:29:11,2048,삼일초등학교 인근,1,250,1790
385065,SPB-18187,2018-09-30 23:59:59,277,영등포뉴타운지하상가 2번게이트,5,2018-10-01 07:07:24,268,그랜드컨벤션센터 앞,3,427,2480
385066,SPB-13571,2018-09-30 22:30:16,2025,흑석역 1번출구,6,2018-10-01 07:41:29,247,당산역 10번출구 앞,10,550,8500

In [30]:
data28 = data28.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data28.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-11299,2018-09-23 20:46:05,125,서강대 남문 옆,2,2018-09-23 20:50:02,129,신촌역(2호선) 6번출구 옆,9,4,670
1,SPB-14425,2018-09-23 20:46:03,1518,SK telecom(수유직영점) 앞,9,2018-09-23 20:50:12,1512,강북중학교 앞,19,3,1150
2,SPB-05366,2018-09-23 20:47:55,3501,광진구청 앞,3,2018-09-23 20:50:20,3520,광진경찰서,5,2,360
3,SPB-05791,2018-09-23 20:45:33,2307,압구정 한양 3차 아파트,1,2018-09-23 20:50:20,2307,압구정 한양 3차 아파트,1,4,360
4,SPB-18318,2018-09-23 20:47:01,591,건국대학교 (행정관),1,2018-09-23 20:50:30,503,더샵스타시티 C동 앞,15,3,850

In [31]:
data28.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385067 entries, 0 to 385066
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    385067 non-null  object
 1   대여일시     385067 non-null  datetime64[ns]
 2   대여소번호    385067 non-null  int64
 3   대여대여소명   385067 non-null  object
 4   대여거치대    385067 non-null  int64
 5   반납일시     385067 non-null  datetime64[ns]
 6   반납대여소번호  385067 non-null  int64
 7   반납대여소명   385067 non-null  object
 8   반납거치대    385067 non-null  int64
 9   이용시간     385067 non-null  int64
 10  이용거리     385067 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 32.3+ MB

In [32]:
data28.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [34]:
#data28.to_excel('./서울특별시 공공자전거 대여정보_201809_2.xlsx', index = False)

In [35]:
data29 = pd.read_excel('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201810_01.xlsx')
data29

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-13621,2018-10-01 00:02:24,127,현대벤처빌 앞,9,2018-10-01 00:04:20,124,서강대 정문 건너편,18,1,350
1,SPB-10560,2018-10-01 00:01:25,1326,상월곡역 1번출구,5,2018-10-01 00:04:37,1328,월곡역 3번출구,4,3,630
2,SPB-16256,2018-10-01 00:00:48,815,LIG강촌아파트 103동앞,10,2018-10-01 00:04:41,832,이촌1동 주민센터 뒤,11,3,44210
3,SPB-07969,2018-10-01 00:01:10,1308,안암로터리 버스정류장 앞,12,2018-10-01 00:04:51,614,용두동 사거리,1,3,560
4,SPB-10866,2018-10-01 00:02:04,575,중앙농협 중곡지점,9,2018-10-01 00:04:52,3510,중곡SK아파트앞,10,2,300
...,...,...,...,...,...,...,...,...,...,...,...
1048570,SPB-17643,2018-10-22 12:45:24,328,탑골공원 앞,3,2018-10-22 12:54:57,354,포르투갈 대사관 앞,2,9,1410
1048571,SPB-16580,2018-10-22 12:01:30,222,시범아파트버스정류장 옆,10,2018-10-22 12:54:58,222,시범아파트버스정류장 옆,10,52,8510
1048572,SPB-04430,2018-10-22 12:39:24,1243,문정 법조단지7,9,2018-10-22 12:55:01,2387,래미안강남힐즈 사거리,2,15,0
1048573,SPB-12247,2018-10-22 12:42:18,509,이마트 버스정류소 옆,5,2018-10-22 12:55:04,592,건국대학교 학생회관,2,12,1890
1048574,SPB-02720,2018-10-22 12:46:58,2033,사당동 아르테스 웨딩앞,5,2018-10-22 12:55:08,2221,하나은행 방배동지점 앞,6,7,1590

In [36]:
data29 = data29.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data29.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-13621,2018-10-01 00:02:24,127,현대벤처빌 앞,9,2018-10-01 00:04:20,124,서강대 정문 건너편,18,1,350
1,SPB-10560,2018-10-01 00:01:25,1326,상월곡역 1번출구,5,2018-10-01 00:04:37,1328,월곡역 3번출구,4,3,630
2,SPB-16256,2018-10-01 00:00:48,815,LIG강촌아파트 103동앞,10,2018-10-01 00:04:41,832,이촌1동 주민센터 뒤,11,3,44210
3,SPB-07969,2018-10-01 00:01:10,1308,안암로터리 버스정류장 앞,12,2018-10-01 00:04:51,614,용두동 사거리,1,3,560
4,SPB-10866,2018-10-01 00:02:04,575,중앙농협 중곡지점,9,2018-10-01 00:04:52,3510,중곡SK아파트앞,10,2,300

In [37]:
data29.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 11 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   자전거번호    1048575 non-null  object
 1   대여일시     1048575 non-null  datetime64[ns]
 2   대여소번호    1048575 non-null  int64
 3   대여대여소명   1048575 non-null  object
 4   대여거치대    1048575 non-null  int64
 5   반납일시     1048575 non-null  datetime64[ns]
 6   반납대여소번호  1048575 non-null  int64
 7   반납대여소명   1048575 non-null  object
 8   반납거치대    1048575 non-null  int64
 9   이용시간     1048575 non-null  int64
 10  이용거리     1048575 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 88.0+ MB

In [38]:
data29.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [40]:
#data29.to_excel('./서울특별시 공공자전거 대여정보_201810_01.xlsx', index = False)

In [41]:
data30 = pd.read_excel('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201810_02.xlsx')
data30

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16369,2018-10-22 12:47:09,3504,원일교회,4,2018-10-22 12:49:32,590,건국대학교 (입학정보관),1,2,500
1,SPB-01983,2018-10-22 12:46:48,191,정명학원,10,2018-10-22 12:50:27,178,증산3교 앞,10,3,530
2,SPB-15300,2018-10-22 12:47:08,3502,중곡역 1번출구,3,2018-10-22 12:50:45,3517,용마사거리,10,3,440
3,SPB-17504,2018-10-22 12:48:25,2264,이수역 1번출구,8,2018-10-22 12:50:56,2230,이수역 4번 출구,5,2,390
4,SPB-04958,2018-10-22 12:47:08,521,왕십리역 11번 출구 앞,9,2018-10-22 12:51:04,525,한양대병원사거리,16,3,730
...,...,...,...,...,...,...,...,...,...,...,...
366460,SPB-14494,2018-10-31 21:34:00,106,합정역 7번출구 앞,8,2018-11-01 08:31:54,101,(구)합정동 주민센터,4,657,1090
366461,SPB-13521,2018-10-31 21:26:20,2034,사당역 7번출구쪽,20,2018-11-01 08:35:16,2230,이수역 4번 출구,3,668,1230
366462,SPB-16660,2018-10-31 23:18:35,125,서강대 남문 옆,14,2018-11-01 08:44:03,374,청구역 2번출구 앞,3,565,10670
366463,SPB-04094,2018-10-31 22:52:45,2139,서울신성초등학교,1,2018-11-01 09:19:56,2176,보라매공원 보도육교,9,626,3890
366464,SPB-07469,2018-10-31 15:26:04,617,청솔우성아파트 앞,4,2018-11-01 10:14:22,639,서울시립대 후문,5,65,3900

In [42]:
data30 = data30.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data30.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16369,2018-10-22 12:47:09,3504,원일교회,4,2018-10-22 12:49:32,590,건국대학교 (입학정보관),1,2,500
1,SPB-01983,2018-10-22 12:46:48,191,정명학원,10,2018-10-22 12:50:27,178,증산3교 앞,10,3,530
2,SPB-15300,2018-10-22 12:47:08,3502,중곡역 1번출구,3,2018-10-22 12:50:45,3517,용마사거리,10,3,440
3,SPB-17504,2018-10-22 12:48:25,2264,이수역 1번출구,8,2018-10-22 12:50:56,2230,이수역 4번 출구,5,2,390
4,SPB-04958,2018-10-22 12:47:08,521,왕십리역 11번 출구 앞,9,2018-10-22 12:51:04,525,한양대병원사거리,16,3,730

In [43]:
data30.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366465 entries, 0 to 366464
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    366465 non-null  object
 1   대여일시     366465 non-null  datetime64[ns]
 2   대여소번호    366465 non-null  int64
 3   대여대여소명   366465 non-null  object
 4   대여거치대    366465 non-null  int64
 5   반납일시     366465 non-null  datetime64[ns]
 6   반납대여소번호  366465 non-null  int64
 7   반납대여소명   366465 non-null  object
 8   반납거치대    366465 non-null  int64
 9   이용시간     366465 non-null  int64
 10  이용거리     366465 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 30.8+ MB

In [44]:
data30.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [46]:
#data30.to_excel('./서울특별시 공공자전거 대여정보_201810_02.xlsx', index = False)

In [47]:
data31 = pd.read_excel('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201811.xlsx')
data31

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16975,2018-11-01 00:00:17,194,증산교 앞,5,2018-11-01 00:01:55,178,증산3교 앞,3,1,510
1,SPB-04475,2018-11-01 00:00:10,1024,강동구청 앞,3,2018-11-01 00:02:47,1030,미호 플랜트 앞,2,2,310
2,SPB-17659,2018-11-01 00:00:26,907,CJ 드림시티,7,2018-11-01 00:05:05,931,역촌파출소,3,4,670
3,SPB-10808,2018-11-01 00:00:24,588,뚝섬 유원지역,12,2018-11-01 00:05:07,548,자양나들목,1,4,870
4,SPB-16323,2018-11-01 00:02:38,2376,수서역 6번출구 앞,20,2018-11-01 00:05:10,2376,수서역 6번출구 앞,4,2,20
...,...,...,...,...,...,...,...,...,...,...,...
958248,SPB-15173,2018-11-30 23:04:14,2266,서초역 3번출구,14,2018-12-01 02:55:28,2266,서초역 3번출구,9,230,3940
958249,SPB-18705,2018-11-30 23:45:53,1308,안암로터리 버스정류장 앞,3,2018-12-01 03:09:11,613,신설동역 10번출구 앞,1,184,1200
958250,SPB-16927,2018-11-30 23:01:20,406,상암월드컵파크 7단지 앞,5,2018-12-01 05:12:06,414,상암동주민센터 옆,5,370,1650
958251,SPB-17194,2018-11-30 23:25:14,2213,고속터미널역 5번출구 앞,15,2018-12-01 08:37:25,2148,낙성대역 3번출구 뒤,4,551,6410
958252,SPB-16091,2018-11-30 23:44:24,141,연대 대운동장 옆,16,2018-12-01 09:23:16,172,서대문소방서,4,578,1930

In [48]:
data31 = data31.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data31.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16975,2018-11-01 00:00:17,194,증산교 앞,5,2018-11-01 00:01:55,178,증산3교 앞,3,1,510
1,SPB-04475,2018-11-01 00:00:10,1024,강동구청 앞,3,2018-11-01 00:02:47,1030,미호 플랜트 앞,2,2,310
2,SPB-17659,2018-11-01 00:00:26,907,CJ 드림시티,7,2018-11-01 00:05:05,931,역촌파출소,3,4,670
3,SPB-10808,2018-11-01 00:00:24,588,뚝섬 유원지역,12,2018-11-01 00:05:07,548,자양나들목,1,4,870
4,SPB-16323,2018-11-01 00:02:38,2376,수서역 6번출구 앞,20,2018-11-01 00:05:10,2376,수서역 6번출구 앞,4,2,20

In [49]:
data31.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 958253 entries, 0 to 958252
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    958253 non-null  object
 1   대여일시     958253 non-null  datetime64[ns]
 2   대여소번호    958253 non-null  int64
 3   대여대여소명   958253 non-null  object
 4   대여거치대    958253 non-null  int64
 5   반납일시     958253 non-null  datetime64[ns]
 6   반납대여소번호  958253 non-null  int64
 7   반납대여소명   958253 non-null  object
 8   반납거치대    958253 non-null  int64
 9   이용시간     958253 non-null  int64
 10  이용거리     958253 non-null  int64
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 80.4+ MB

In [50]:
data31.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [52]:
#data31.to_excel('./서울특별시 공공자전거 대여정보_201811.xlsx', index = False)

In [53]:
data32 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201812.csv', 
                     engine = 'python', 
                     names = ['자전거번호', '대여일시', '대여소번호', '대여대여소명', '대여거치대', '반납일시', '반납대여소번호',
                              '반납대여소명', '반납거치대', '이용시간', '이용거리'])
data32

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-03255,2018-12-01 00:00:16,1135,강서구의회,9,2018-12-01 00:04:21,1132,등촌역 7번출구,5,3,550.0
1,SPB-05427,2018-12-01 00:01:03,1113,서남환경공원 버스정류장,1,2018-12-01 00:04:24,1112,마곡엠밸리4단지 정문,5,3,700.0
2,SPB-05991,2018-12-01 00:01:46,3100,북성초교,1,2018-12-01 00:04:34,3104,e편한세상 신촌4단지 앞,4,2,430.0
3,SPB-11186,2018-12-01 00:00:01,1357,북한산보국문역,13,2018-12-01 00:04:50,1360,정릉역,1,4,940.0
4,SPB-02872,2018-12-01 00:01:21,3538,서울숲 IT캐슬,8,2018-12-01 00:04:53,512,뚝섬역 1번 출구 옆,8,3,410.0
...,...,...,...,...,...,...,...,...,...,...,...
497953,SPB-14113,2018-12-31 23:33:24,1452,겸재교 진입부,6,2019-01-01 01:30:18,1452,겸재교 진입부,7,116,1410.0
497954,SPB-17654,2018-12-31 16:47:34,128,신촌역(2호선) 1번출구 옆,4,2019-01-01 01:43:48,101,(구)합정동 주민센터,2,535,3780.0
497955,SPB-03920,2018-12-31 15:28:43,1623,노원 구민회관,2,2019-01-01 02:39:06,1673,노원역?5번출구,1,670,1980.0
497956,SPB-08305,2018-12-31 23:21:42,113,홍대입구역 2번출구 앞,7,2019-01-01 06:36:48,170,가재울 뉴타운 주유소 옆,7,177,2480.0
497957,SPB-18723,2018-12-31 19:33:03,238,제2구민체육센타 앞,8,2019-01-01 14:56:36,265,영등포유통상가 사거리,11,1,0.0

In [54]:
data32 = data32.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data32.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-03255,2018-12-01 00:00:16,1135,강서구의회,9,2018-12-01 00:04:21,1132,등촌역 7번출구,5,3,550.0
1,SPB-05427,2018-12-01 00:01:03,1113,서남환경공원 버스정류장,1,2018-12-01 00:04:24,1112,마곡엠밸리4단지 정문,5,3,700.0
2,SPB-05991,2018-12-01 00:01:46,3100,북성초교,1,2018-12-01 00:04:34,3104,e편한세상 신촌4단지 앞,4,2,430.0
3,SPB-11186,2018-12-01 00:00:01,1357,북한산보국문역,13,2018-12-01 00:04:50,1360,정릉역,1,4,940.0
4,SPB-02872,2018-12-01 00:01:21,3538,서울숲 IT캐슬,8,2018-12-01 00:04:53,512,뚝섬역 1번 출구 옆,8,3,410.0

In [55]:
data32.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497958 entries, 0 to 497957
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    497958 non-null  object
 1   대여일시     497958 non-null  object
 2   대여소번호    497958 non-null  int64
 3   대여대여소명   497958 non-null  object
 4   대여거치대    497958 non-null  int64
 5   반납일시     497958 non-null  object
 6   반납대여소번호  497958 non-null  int64
 7   반납대여소명   497958 non-null  object
 8   반납거치대    497958 non-null  int64
 9   이용시간     497958 non-null  int64
 10  이용거리     497958 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 41.8+ MB

In [56]:
data32.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [57]:
#data32.to_csv('./서울특별시 공공자전거 대여정보_201812.csv', index = False, encoding ='cp949')

In [58]:
data33 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201901.csv', engine = 'python')
data33

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-10632,2019-01-01 00:00:44,1421,신내역 4번출구,3,2019-01-01 00:03:53,1420,신내어울공원 앞,13,2,580.0
1,SPB-10957,2019-01-01 00:02:16,1408,먹골역 6번출구 앞,3,2019-01-01 00:07:07,1433,중화역 2번출구,4,4,1020.0
2,SPB-16067,2019-01-01 00:04:12,347,동대문역사문화공원역 9번출구 앞,17,2019-01-01 00:07:07,387,훈련원공원주차장 앞,1,2,550.0
3,SPB-17170,2019-01-01 00:03:09,615,용두동 래미안허브리츠아파트 앞,4,2019-01-01 00:07:27,612,시립동부병원 앞 사거리,14,3,700.0
4,SPB-14130,2019-01-01 00:01:44,1177,수명중?고교,7,2019-01-01 00:08:09,1152,마곡역교차로,1,5,1090.0
...,...,...,...,...,...,...,...,...,...,...,...
485696,SPB-06778,2019-01-31 23:34:45,1925,동양미래대학교 정문 옆,16,2019-02-01 01:15:33,1996,구일역 1번 출입구 앞,2,100,16340.0
485697,SPB-18320,2019-01-31 23:53:12,1611,과기대 입구(우),2,2019-02-01 01:24:47,1503,이디야 커피 수유역점 앞,6,91,11800.0
485698,SPB-08122,2019-01-31 23:43:55,1601,석계역 문화광장 내 자전거 보관소,19,2019-02-01 01:35:52,1601,석계역 문화광장 내 자전거 보관소,11,107,1780.0
485699,SPB-19379,2019-01-31 23:30:39,843,녹사평역 광장,6,2019-02-01 02:07:03,805,문배어린이공원 앞,9,142,2660.0
485700,SPB-18550,2019-01-31 19:41:46,263,근로자회관 사거리,3,2019-02-01 14:09:49,263,근로자회관 사거리,8,1107,3230.0

In [59]:
data33 = data33.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data33.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-10632,2019-01-01 00:00:44,1421,신내역 4번출구,3,2019-01-01 00:03:53,1420,신내어울공원 앞,13,2,580.0
1,SPB-10957,2019-01-01 00:02:16,1408,먹골역 6번출구 앞,3,2019-01-01 00:07:07,1433,중화역 2번출구,4,4,1020.0
2,SPB-16067,2019-01-01 00:04:12,347,동대문역사문화공원역 9번출구 앞,17,2019-01-01 00:07:07,387,훈련원공원주차장 앞,1,2,550.0
3,SPB-17170,2019-01-01 00:03:09,615,용두동 래미안허브리츠아파트 앞,4,2019-01-01 00:07:27,612,시립동부병원 앞 사거리,14,3,700.0
4,SPB-14130,2019-01-01 00:01:44,1177,수명중?고교,7,2019-01-01 00:08:09,1152,마곡역교차로,1,5,1090.0

In [60]:
data33.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485701 entries, 0 to 485700
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    485701 non-null  object
 1   대여일시     485701 non-null  object
 2   대여대여소번호  485701 non-null  int64
 3   대여대여소명   485701 non-null  object
 4   대여거치대    485701 non-null  int64
 5   반납일시     485701 non-null  object
 6   반납대여소번호  485701 non-null  int64
 7   반납대여소명   485701 non-null  object
 8   반납거치대    485701 non-null  int64
 9   이용시간     485701 non-null  int64
 10  이용거리     485701 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 40.8+ MB

In [61]:
data33.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [62]:
#data33.to_csv('./서울특별시 공공자전거 대여정보_201901.csv', index = False, encoding ='cp949')

In [63]:
data34 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201902.csv', engine = 'python')
data34

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-00669,2019-02-01 00:00:46,2504,신사역 4번출구 뒤,1,2019-02-01 00:02:32,2277,길마중4교 하부,3,1,370.0
1,SPB-15190,2019-02-01 00:00:52,358,성대입구 사거리,6,2019-02-01 00:03:39,342,대학로 마로니에공원,1,2,590.0
2,SPB-08938,2019-02-01 00:00:11,3506,영동대교 북단,1,2019-02-01 00:03:41,585,성수2가1동 공영주차장 인근,8,3,580.0
3,SPB-12647,2019-02-01 00:01:15,1308,안암로터리 버스정류장 앞,6,2019-02-01 00:03:54,614,용두동 사거리,5,2,530.0
4,SPB-19426,2019-02-01 00:01:02,247,당산역 10번출구 앞,15,2019-02-01 00:04:28,293,충북 미래관,12,3,830.0
...,...,...,...,...,...,...,...,...,...,...,...
461967,SPB-11763,2019-02-28 05:05:06,546,잠실대교북단 교차로,8,2019-03-01 06:13:01,3536,중앙농협(자양동),1,227,880.0
461968,SPB-09011,2019-02-28 16:12:26,525,한양대병원사거리,9,2019-03-01 08:14:45,537,한양대후문역 부근,7,148,4100.0
461969,SPB-10607,2019-02-28 23:00:55,1211,방이삼거리,2,2019-03-01 09:02:46,2621,한성백제역 2번 출구,11,61,8830.0
461970,SPB-00970,2019-02-28 11:10:34,383,신당역 12번 출구 뒤,13,2019-03-01 09:10:16,346,맥스타일 앞,2,1319,860.0
461971,SPB-00428,2019-02-28 17:42:04,845,용산 선인상가,22,2019-03-01 14:35:56,845,용산 선인상가,13,1253,2270.0

In [64]:
data34 = data34.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data34.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-00669,2019-02-01 00:00:46,2504,신사역 4번출구 뒤,1,2019-02-01 00:02:32,2277,길마중4교 하부,3,1,370.0
1,SPB-15190,2019-02-01 00:00:52,358,성대입구 사거리,6,2019-02-01 00:03:39,342,대학로 마로니에공원,1,2,590.0
2,SPB-08938,2019-02-01 00:00:11,3506,영동대교 북단,1,2019-02-01 00:03:41,585,성수2가1동 공영주차장 인근,8,3,580.0
3,SPB-12647,2019-02-01 00:01:15,1308,안암로터리 버스정류장 앞,6,2019-02-01 00:03:54,614,용두동 사거리,5,2,530.0
4,SPB-19426,2019-02-01 00:01:02,247,당산역 10번출구 앞,15,2019-02-01 00:04:28,293,충북 미래관,12,3,830.0

In [65]:
data34.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461972 entries, 0 to 461971
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    461972 non-null  object
 1   대여일시     461972 non-null  object
 2   대여대여소번호  461972 non-null  int64
 3   대여대여소명   461972 non-null  object
 4   대여거치대    461972 non-null  int64
 5   반납일시     461972 non-null  object
 6   반납대여소번호  461972 non-null  int64
 7   반납대여소명   461972 non-null  object
 8   반납거치대    461972 non-null  int64
 9   이용시간     461972 non-null  int64
 10  이용거리     461972 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 38.8+ MB

In [66]:
data34.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [67]:
#data34.to_csv('./서울특별시 공공자전거 대여정보_201902.csv', index = False, encoding ='cp949')

In [68]:
data35 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201903.csv', engine = 'python')
data35

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-14409,2019-03-01 00:00:04,2321,학여울역 사거리,1,2019-03-01 00:02:48,2324,천주교 대치 2동 교회 옆,2,2,660.0
1,SPB-03135,2019-03-01 00:00:43,2621,한성백제역 2번 출구,10,2019-03-01 00:03:43,1248,방이초등학교,6,2,630.0
2,SPB-13846,2019-03-01 00:02:45,1060,천일초교 사거리,1,2019-03-01 00:04:58,1061,천호초교 입구 사거리(일주빌딩),1,1,310.0
3,SPB-18088,2019-03-01 00:00:34,284,센트럴 푸르지오 시티 앞,8,2019-03-01 00:05:03,239,유스호스텔 앞,1,4,970.0
4,SPB-04107,2019-03-01 00:01:37,262,영문초등학교 사거리,4,2019-03-01 00:05:10,275,신동아아파트,1,3,670.0
...,...,...,...,...,...,...,...,...,...,...,...
885131,SPB-14865,2019-03-31 23:47:30,159,이대역 4번 출구,1,2019-04-01 02:22:48,146,마포역 2번출구 뒤,2,154,2740.0
885132,SPB-14576,2019-03-31 21:31:33,1249,아주중학교건너편,7,2019-04-01 02:41:52,2619,석촌고분역 4번출구,8,309,6180.0
885133,SPB-05879,2019-03-31 21:50:16,1248,방이초등학교,11,2019-04-01 02:48:57,1248,방이초등학교,19,298,6840.0
885134,SPB-05239,2019-03-31 07:35:10,1734,쌍문현대1차아파트 108동 앞,5,2019-04-01 03:48:42,1733,방학사거리 (봄마당 앞),1,1213,3900.0
885135,SPB-16830,2019-03-31 22:09:01,117,홍은사거리,11,2019-04-01 10:31:36,163,명지전문대학교 정문 앞,7,742,3020.0

In [69]:
data35 = data35.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data35.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-14409,2019-03-01 00:00:04,2321,학여울역 사거리,1,2019-03-01 00:02:48,2324,천주교 대치 2동 교회 옆,2,2,660.0
1,SPB-03135,2019-03-01 00:00:43,2621,한성백제역 2번 출구,10,2019-03-01 00:03:43,1248,방이초등학교,6,2,630.0
2,SPB-13846,2019-03-01 00:02:45,1060,천일초교 사거리,1,2019-03-01 00:04:58,1061,천호초교 입구 사거리(일주빌딩),1,1,310.0
3,SPB-18088,2019-03-01 00:00:34,284,센트럴 푸르지오 시티 앞,8,2019-03-01 00:05:03,239,유스호스텔 앞,1,4,970.0
4,SPB-04107,2019-03-01 00:01:37,262,영문초등학교 사거리,4,2019-03-01 00:05:10,275,신동아아파트,1,3,670.0

In [70]:
data35.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885136 entries, 0 to 885135
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    885136 non-null  object
 1   대여일시     885136 non-null  object
 2   대여대여소번호  885136 non-null  int64
 3   대여대여소명   885136 non-null  object
 4   대여거치대    885136 non-null  int64
 5   반납일시     885136 non-null  object
 6   반납대여소번호  885136 non-null  int64
 7   반납대여소명   885136 non-null  object
 8   반납거치대    885136 non-null  int64
 9   이용시간     885136 non-null  int64
 10  이용거리     885136 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 74.3+ MB

In [71]:
data35.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [72]:
#data35.to_csv('./서울특별시 공공자전거 대여정보_201903.csv', index = False, encoding ='cp949')

In [73]:
data36 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201904.csv', 
                     engine = 'python',
                     names = ['자전거번호', '대여일시', '대여소번호', '대여대여소명', '대여거치대', '반납일시', '반납대여소번호', 
                              '반납대여소명', '반납거치대', '이용시간', '이용거리'])
data36

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-00352,2019-04-01 00:00:07,364,창신역 1번출구 앞,8,2019-04-01 00:04:36,361,동묘앞역 1번출구 뒤,4,4,740.0
1,SPB-11337,2019-04-01 00:02:10,1449,상봉역 1번출구,5,2019-04-01 00:06:03,1404,동일로 지하차도,10,3,550.0
2,SPB-05337,2019-04-01 00:02:24,1044,굽은다리역,12,2019-04-01 00:06:06,1015,샛마을 근린공원,13,3,880.0
3,SPB-17568,2019-04-01 00:02:15,127,현대벤처빌 앞,1,2019-04-01 00:06:29,437,대흥역 1번출구,5,3,760.0
4,SPB-12144,2019-04-01 00:01:57,1906,신도림역 1번 출구 앞,1,2019-04-01 00:07:16,263,근로자회관 사거리,2,5,1100.0
...,...,...,...,...,...,...,...,...,...,...,...
1427762,SPB-08266,2019-04-30 23:59:49,1016,해뜨는 주유소옆 리엔파크 109동앞,6,2019-05-01 04:16:22,1014,강동구평생학습관앞,13,255,3480.0
1427763,SPB-11986,2019-04-30 21:40:14,906,연신내역 5번출구150M 아래,3,2019-05-01 05:58:26,930,구 서부경찰서 건너편,5,242,2560.0
1427764,SPB-12383,2019-04-30 23:31:31,1824,독산근린공원 입구,6,2019-05-01 07:46:10,1824,독산근린공원 입구,6,236,11590.0
1427765,SPB-10614,2019-04-30 21:53:10,421,마포구청 앞,6,2019-05-01 08:51:17,402,상암월드컵파크 9단지 앞,3,140,3890.0
1427766,SPB-02450,2019-04-30 22:57:56,1206,9호선종합운동장역 9번출구,1,2019-05-01 09:01:36,1221,삼전사거리 포스코더샵,5,603,1400.0

In [74]:
data36 = data36.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data36.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-00352,2019-04-01 00:00:07,364,창신역 1번출구 앞,8,2019-04-01 00:04:36,361,동묘앞역 1번출구 뒤,4,4,740.0
1,SPB-11337,2019-04-01 00:02:10,1449,상봉역 1번출구,5,2019-04-01 00:06:03,1404,동일로 지하차도,10,3,550.0
2,SPB-05337,2019-04-01 00:02:24,1044,굽은다리역,12,2019-04-01 00:06:06,1015,샛마을 근린공원,13,3,880.0
3,SPB-17568,2019-04-01 00:02:15,127,현대벤처빌 앞,1,2019-04-01 00:06:29,437,대흥역 1번출구,5,3,760.0
4,SPB-12144,2019-04-01 00:01:57,1906,신도림역 1번 출구 앞,1,2019-04-01 00:07:16,263,근로자회관 사거리,2,5,1100.0

In [75]:
data36.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1427767 entries, 0 to 1427766
Data columns (total 11 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   자전거번호    1427767 non-null  object
 1   대여일시     1427767 non-null  object
 2   대여소번호    1427767 non-null  int64
 3   대여대여소명   1427767 non-null  object
 4   대여거치대    1427767 non-null  int64
 5   반납일시     1427767 non-null  object
 6   반납대여소번호  1427767 non-null  int64
 7   반납대여소명   1427767 non-null  object
 8   반납거치대    1427767 non-null  int64
 9   이용시간     1427767 non-null  int64
 10  이용거리     1427767 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 119.8+ MB

In [76]:
data36.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [77]:
#data36.to_csv('./서울특별시 공공자전거 대여정보_201904.csv', index = False, encoding ='cp949')

In [78]:
data37 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201905.csv', 
                     engine = 'python', 
                     names = ['자전거번호', '대여일시', '대여소번호', '대여대여소명', '대여거치대', '반납일시', '반납대여소번호',
                              '반납대여소명', '반납거치대', '이용시간', '이용거리'])
data37

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-01857,2019-05-01 00:01:07,1908,해원리바파크 육교 밑,3,2019-05-01 00:03:52,1957,구일고등학교 정문,6,2,480.0
1,SPB-18298,2019-05-01 00:03:06,241,신길우성1차아파트 앞 공원,5,2019-05-01 00:04:25,255,도림4거리,10,0,290.0
2,SPB-12844,2019-05-01 00:00:22,1224,아시아지하보도 2번 출구,13,2019-05-01 00:04:36,1249,아주중학교건너편,10,4,960.0
3,SPB-15490,2019-05-01 00:01:52,521,왕십리역 11번 출구 앞,2,2019-05-01 00:04:50,520,상왕십리역 4번 출구 앞,7,2,0.0
4,SPB-18475,2019-05-01 00:01:11,364,창신역 1번출구 앞,4,2019-05-01 00:04:52,361,동묘앞역 1번출구 뒤,1,3,730.0
...,...,...,...,...,...,...,...,...,...,...,...
2221795,SPB-16314,2019-05-31 23:25:34,2217,아크로리버뷰 부지 앞,14,2019-06-01 08:49:59,2289,남태령역 2번출구,4,564,5060.0
2221796,SPB-05369,2019-05-31 22:12:06,722,LG전자베스트샵 신정점,1,2019-06-01 09:37:07,1140,목동사거리 버스정류장,2,684,1790.0
2221797,SPB-14277,2019-05-31 21:48:05,1814,두산위브아파트 옆 상가건물 앞,8,2019-06-01 09:57:32,1849,대륭포스트타워5차,1,729,1580.0
2221798,SPB-10222,2019-05-31 21:19:40,1295,잠실역 8번출구,20,2019-06-01 10:04:11,626,군자교 서측 녹지대,7,253,6980.0
2221799,SPB-12224,2019-05-31 09:19:29,567,성수역 2번출구 앞,7,2019-06-01 12:38:00,567,성수역 2번출구 앞,7,235,760.0

In [79]:
data37 = data37.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data37.head()

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-01857,2019-05-01 00:01:07,1908,해원리바파크 육교 밑,3,2019-05-01 00:03:52,1957,구일고등학교 정문,6,2,480.0
1,SPB-18298,2019-05-01 00:03:06,241,신길우성1차아파트 앞 공원,5,2019-05-01 00:04:25,255,도림4거리,10,0,290.0
2,SPB-12844,2019-05-01 00:00:22,1224,아시아지하보도 2번 출구,13,2019-05-01 00:04:36,1249,아주중학교건너편,10,4,960.0
3,SPB-15490,2019-05-01 00:01:52,521,왕십리역 11번 출구 앞,2,2019-05-01 00:04:50,520,상왕십리역 4번 출구 앞,7,2,0.0
4,SPB-18475,2019-05-01 00:01:11,364,창신역 1번출구 앞,4,2019-05-01 00:04:52,361,동묘앞역 1번출구 뒤,1,3,730.0

In [80]:
data37.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2221800 entries, 0 to 2221799
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여소번호    int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 186.5+ MB

In [81]:
data37.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [82]:
#data37.to_csv('./서울특별시 공공자전거 대여정보_201905.csv', index = False, encoding ='cp949')

In [83]:
data38 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201906_1.csv', engine = 'python')
data38

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22040,2019-06-03 08:49:27,646,장한평역 1번출구 (국민은행앞),1,2019-06-03 09:17:10,3,중랑센터,14,27,1330.0
1,SPB-07446,2019-06-03 08:33:22,526,용답토속공원 앞,8,2019-06-03 09:27:16,3,중랑센터,14,54,1180.0
2,SPB-20387,2019-06-05 08:27:47,646,장한평역 1번출구 (국민은행앞),1,2019-06-05 08:41:31,3,중랑센터,2,12,1930.0
3,SPB-16794,2019-06-05 08:46:29,646,장한평역 1번출구 (국민은행앞),6,2019-06-05 08:53:10,3,중랑센터,14,6,1340.0
4,SPB-18266,2019-06-10 08:27:26,529,장한평역 8번 출구 앞,10,2019-06-10 08:33:40,3,중랑센터,2,5,1230.0
...,...,...,...,...,...,...,...,...,...,...,...
799955,SPB-22522,2019-06-01 17:47:47,726,목동3단지 시내버스정류장,6,2019-06-01 18:44:20,735,영도초등학교,5,52,2020.0
799956,SPB-01434,2019-06-01 17:49:18,735,영도초등학교,1,2019-06-01 18:55:01,735,영도초등학교,2,65,7990.0
799957,SPB-18503,2019-06-01 17:48:02,735,영도초등학교,8,2019-06-01 18:55:29,735,영도초등학교,4,66,7910.0
799958,SPB-19656,2019-06-01 18:55:01,762,오목로 무중력지대 앞,1,2019-06-01 19:08:12,735,영도초등학교,10,13,2120.0
799959,SPB-10785,2019-06-01 19:12:48,1136,등촌2파출소,10,2019-06-01 19:23:10,735,영도초등학교,10,10,1620.0

In [84]:
data38 = data38.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data38.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22040,2019-06-03 08:49:27,646,장한평역 1번출구 (국민은행앞),1,2019-06-03 09:17:10,3,중랑센터,14,27,1330.0
1,SPB-07446,2019-06-03 08:33:22,526,용답토속공원 앞,8,2019-06-03 09:27:16,3,중랑센터,14,54,1180.0
2,SPB-20387,2019-06-05 08:27:47,646,장한평역 1번출구 (국민은행앞),1,2019-06-05 08:41:31,3,중랑센터,2,12,1930.0
3,SPB-16794,2019-06-05 08:46:29,646,장한평역 1번출구 (국민은행앞),6,2019-06-05 08:53:10,3,중랑센터,14,6,1340.0
4,SPB-18266,2019-06-10 08:27:26,529,장한평역 8번 출구 앞,10,2019-06-10 08:33:40,3,중랑센터,2,5,1230.0

In [85]:
data38.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799960 entries, 0 to 799959
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    799960 non-null  object
 1   대여일시     799960 non-null  object
 2   대여대여소번호  799960 non-null  int64
 3   대여대여소명   799960 non-null  object
 4   대여거치대    799960 non-null  int64
 5   반납일시     799960 non-null  object
 6   반납대여소번호  799960 non-null  int64
 7   반납대여소명   799960 non-null  object
 8   반납거치대    799960 non-null  int64
 9   이용시간     799960 non-null  int64
 10  이용거리     799960 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [86]:
data38.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [87]:
#data38.to_csv('./서울특별시 공공자전거 대여정보_201906_1.csv', index = False, encoding ='cp949')

In [88]:
data39 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201906_2.csv', engine = 'python')
data39

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-18282,2019-06-01 21:15:39,764,목동청소년수련관,7,2019-06-01 21:22:20,735,영도초등학교,9,6,0.0
1,SPB-06551,2019-06-01 21:28:21,703,오목교역 7번출구 앞,1,2019-06-01 21:40:41,735,영도초등학교,9,11,2210.0
2,SPB-22632,2019-06-01 21:29:30,704,남부법원검찰청 교차로,3,2019-06-01 21:40:51,735,영도초등학교,7,10,1870.0
3,SPB-08605,2019-06-01 21:38:13,731,서울시 도로환경관리센터,10,2019-06-01 21:51:27,735,영도초등학교,9,12,1480.0
4,SPB-01650,2019-06-01 21:39:16,731,서울시 도로환경관리센터,10,2019-06-01 21:55:53,735,영도초등학교,8,16,1500.0
...,...,...,...,...,...,...,...,...,...,...,...
799946,SPB-06091,2019-06-23 19:31:21,1673,노원역?5번출구,9,2019-06-23 19:43:33,1692,온곡초교 교차로,7,11,1530.0
799947,SPB-12632,2019-06-23 19:31:48,1655,공릉1단지아파트,1,2019-06-23 19:57:31,1692,온곡초교 교차로,3,23,4900.0
799948,SPB-10323,2019-06-23 18:57:37,1692,온곡초교 교차로,4,2019-06-23 19:57:32,1692,온곡초교 교차로,5,57,12510.0
799949,SPB-09319,2019-06-23 19:53:33,1625,상계역(4번출구),5,2019-06-23 19:59:35,1692,온곡초교 교차로,1,6,880.0
799950,SPB-02986,2019-06-23 20:17:40,1720,도봉구청 옆(중랑천변),2,2019-06-23 20:31:11,1692,온곡초교 교차로,9,13,2640.0

In [89]:
data39 = data39.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data39.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-18282,2019-06-01 21:15:39,764,목동청소년수련관,7,2019-06-01 21:22:20,735,영도초등학교,9,6,0.0
1,SPB-06551,2019-06-01 21:28:21,703,오목교역 7번출구 앞,1,2019-06-01 21:40:41,735,영도초등학교,9,11,2210.0
2,SPB-22632,2019-06-01 21:29:30,704,남부법원검찰청 교차로,3,2019-06-01 21:40:51,735,영도초등학교,7,10,1870.0
3,SPB-08605,2019-06-01 21:38:13,731,서울시 도로환경관리센터,10,2019-06-01 21:51:27,735,영도초등학교,9,12,1480.0
4,SPB-01650,2019-06-01 21:39:16,731,서울시 도로환경관리센터,10,2019-06-01 21:55:53,735,영도초등학교,8,16,1500.0

In [90]:
data39.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799951 entries, 0 to 799950
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    799951 non-null  object
 1   대여일시     799951 non-null  object
 2   대여대여소번호  799951 non-null  int64
 3   대여대여소명   799951 non-null  object
 4   대여거치대    799951 non-null  int64
 5   반납일시     799951 non-null  object
 6   반납대여소번호  799951 non-null  int64
 7   반납대여소명   799951 non-null  object
 8   반납거치대    799951 non-null  int64
 9   이용시간     799951 non-null  int64
 10  이용거리     799951 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [91]:
data39.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [92]:
#data39.to_csv('./서울특별시 공공자전거 대여정보_201906_2.csv', index = False, encoding ='cp949')

In [93]:
data40 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201906_3.csv', engine = 'python')
data40

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15349,2019-06-23 20:52:11,1625,상계역(4번출구),4,2019-06-23 20:58:08,1692,온곡초교 교차로,6,5,870.0
1,SPB-09319,2019-06-23 20:44:41,1692,온곡초교 교차로,1,2019-06-23 20:58:34,1692,온곡초교 교차로,8,14,2420.0
2,SPB-13041,2019-06-23 20:51:23,1619,중계동 하나프라자빌딩 앞(중1-1),6,2019-06-23 21:11:33,1692,온곡초교 교차로,5,18,2420.0
3,SPB-18582,2019-06-23 21:43:26,1674,서울북부고용센터앞,15,2019-06-23 22:13:20,1692,온곡초교 교차로,5,28,3110.0
4,SPB-00104,2019-06-23 21:45:17,1674,서울북부고용센터앞,5,2019-06-23 22:13:27,1692,온곡초교 교차로,10,27,3120.0
...,...,...,...,...,...,...,...,...,...,...,...
615716,SPB-22438,2019-06-24 07:40:39,240,문래역 4번출구 앞,8,2019-06-24 07:54:16,9998,영남주차장 정비센터,10,13,900.0
615717,SPB-24455,2019-06-25 07:34:58,240,문래역 4번출구 앞,7,2019-06-25 07:42:14,9998,영남주차장 정비센터,4,6,880.0
615718,SPB-24557,2019-06-26 08:19:57,240,문래역 4번출구 앞,4,2019-06-26 08:27:49,9998,영남주차장 정비센터,10,7,930.0
615719,SPB-00649,2019-06-27 07:38:12,240,문래역 4번출구 앞,9,2019-06-27 07:49:52,9998,영남주차장 정비센터,10,11,1030.0
615720,SPB-14209,2019-06-28 07:37:07,240,문래역 4번출구 앞,10,2019-06-28 07:43:54,9998,영남주차장 정비센터,10,6,1010.0

In [94]:
data40 = data40.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data40.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15349,2019-06-23 20:52:11,1625,상계역(4번출구),4,2019-06-23 20:58:08,1692,온곡초교 교차로,6,5,870.0
1,SPB-09319,2019-06-23 20:44:41,1692,온곡초교 교차로,1,2019-06-23 20:58:34,1692,온곡초교 교차로,8,14,2420.0
2,SPB-13041,2019-06-23 20:51:23,1619,중계동 하나프라자빌딩 앞(중1-1),6,2019-06-23 21:11:33,1692,온곡초교 교차로,5,18,2420.0
3,SPB-18582,2019-06-23 21:43:26,1674,서울북부고용센터앞,15,2019-06-23 22:13:20,1692,온곡초교 교차로,5,28,3110.0
4,SPB-00104,2019-06-23 21:45:17,1674,서울북부고용센터앞,5,2019-06-23 22:13:27,1692,온곡초교 교차로,10,27,3120.0

In [95]:
data40.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615721 entries, 0 to 615720
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    615721 non-null  object
 1   대여일시     615721 non-null  object
 2   대여대여소번호  615721 non-null  int64
 3   대여대여소명   615721 non-null  object
 4   대여거치대    615721 non-null  int64
 5   반납일시     615721 non-null  object
 6   반납대여소번호  615721 non-null  int64
 7   반납대여소명   615721 non-null  object
 8   반납거치대    615721 non-null  int64
 9   이용시간     615721 non-null  int64
 10  이용거리     615721 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 51.7+ MB

In [96]:
data40.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [97]:
#data40.to_csv('./서울특별시 공공자전거 대여정보_201906_3.csv', index = False, encoding ='cp949')

In [98]:
data41 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201907_1.csv', engine = 'python')
data41

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21789,2019-07-02 08:35:17,646,장한평역 1번출구 (국민은행앞),4,2019-07-02 08:42:31,3,중랑센터,2,6,1350.0
1,SPB-22363,2019-07-03 08:35:06,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 08:42:28,3,중랑센터,2,7,1160.0
2,SPB-24965,2019-07-03 08:46:07,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 09:09:44,3,중랑센터,14,23,1270.0
3,SPB-21930,2019-07-04 08:49:57,646,장한평역 1번출구 (국민은행앞),4,2019-07-04 09:04:17,3,중랑센터,14,14,1290.0
4,SPB-17709,2019-07-05 08:45:03,529,장한평역 8번 출구 앞,12,2019-07-05 09:11:47,3,중랑센터,14,26,1200.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-11568,2019-07-22 20:28:29,844,이촌2동 동원베네스트 아파트 앞,10,2019-07-22 20:42:38,823,효창동주민센터 앞,9,14,2370.0
799996,SPB-24122,2019-07-22 20:19:27,119,서강나루 공원,2,2019-07-22 20:44:40,823,효창동주민센터 앞,6,24,4450.0
799997,SPB-22506,2019-07-22 21:32:46,819,선린인터넷 고등학교,2,2019-07-22 21:41:25,823,효창동주민센터 앞,1,8,1170.0
799998,SPB-24122,2019-07-22 21:09:04,823,효창동주민센터 앞,6,2019-07-22 23:04:52,823,효창동주민센터 앞,4,112,8960.0
799999,SPB-16860,2019-07-22 21:13:45,129,신촌역(2호선) 6번출구 옆,8,2019-07-23 00:27:01,823,효창동주민센터 앞,10,192,11960.0

In [99]:
data41 = data41.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data41.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21789,2019-07-02 08:35:17,646,장한평역 1번출구 (국민은행앞),4,2019-07-02 08:42:31,3,중랑센터,2,6,1350.0
1,SPB-22363,2019-07-03 08:35:06,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 08:42:28,3,중랑센터,2,7,1160.0
2,SPB-24965,2019-07-03 08:46:07,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 09:09:44,3,중랑센터,14,23,1270.0
3,SPB-21930,2019-07-04 08:49:57,646,장한평역 1번출구 (국민은행앞),4,2019-07-04 09:04:17,3,중랑센터,14,14,1290.0
4,SPB-17709,2019-07-05 08:45:03,529,장한평역 8번 출구 앞,12,2019-07-05 09:11:47,3,중랑센터,14,26,1200.0

In [100]:
data41.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    800000 non-null  object
 1   대여일시     800000 non-null  object
 2   대여대여소번호  800000 non-null  int64
 3   대여대여소명   800000 non-null  object
 4   대여거치대    800000 non-null  int64
 5   반납일시     800000 non-null  object
 6   반납대여소번호  800000 non-null  int64
 7   반납대여소명   800000 non-null  object
 8   반납거치대    800000 non-null  int64
 9   이용시간     800000 non-null  int64
 10  이용거리     800000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [101]:
data41.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [102]:
#data41.to_csv('./서울특별시 공공자전거 대여정보_201907_1.csv', index = False, encoding ='cp949')

In [103]:
data42 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201907_2.csv', engine = 'python')
data42

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16986,2019-07-23 00:37:06,834,효창공원앞역 3번출구 뒤,12,2019-07-23 00:40:06,823,효창동주민센터 앞,1,2,410.0
1,SPB-19381,2019-07-23 10:25:56,437,대흥역 1번출구,9,2019-07-23 10:43:56,823,효창동주민센터 앞,5,17,2530.0
2,SPB-08367,2019-07-23 11:33:56,2058,노량진동 맥도널드앞,6,2019-07-23 11:57:59,823,효창동주민센터 앞,6,23,4670.0
3,SPB-20188,2019-07-23 17:19:26,565,옥수역 3번출구,7,2019-07-23 17:59:33,823,효창동주민센터 앞,1,38,9900.0
4,SPB-16584,2019-07-23 18:19:12,835,남영역 건너편,6,2019-07-23 18:31:45,823,효창동주민센터 앞,10,12,1370.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-08827,2019-07-24 21:40:45,218,증권거래소 앞,19,2019-07-24 23:22:14,1925,동양미래대학교 정문 옆,3,94,17240.0
799996,SPB-06618,2019-07-24 23:22:34,1931,개봉역(북측광장),2,2019-07-24 23:27:22,1925,동양미래대학교 정문 옆,15,4,1170.0
799997,SPB-16997,2019-07-24 23:33:22,1991,오류동역 맞은편,3,2019-07-24 23:48:09,1925,동양미래대학교 정문 옆,12,14,2690.0
799998,SPB-01886,2019-07-24 23:45:56,1931,개봉역(북측광장),1,2019-07-24 23:55:05,1925,동양미래대학교 정문 옆,6,8,1250.0
799999,SPB-09286,2019-07-24 22:24:21,1906,신도림역 1번 출구 앞,9,2019-07-24 23:59:40,1925,동양미래대학교 정문 옆,8,91,13690.0

In [104]:
data42 = data42.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data42.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16986,2019-07-23 00:37:06,834,효창공원앞역 3번출구 뒤,12,2019-07-23 00:40:06,823,효창동주민센터 앞,1,2,410.0
1,SPB-19381,2019-07-23 10:25:56,437,대흥역 1번출구,9,2019-07-23 10:43:56,823,효창동주민센터 앞,5,17,2530.0
2,SPB-08367,2019-07-23 11:33:56,2058,노량진동 맥도널드앞,6,2019-07-23 11:57:59,823,효창동주민센터 앞,6,23,4670.0
3,SPB-20188,2019-07-23 17:19:26,565,옥수역 3번출구,7,2019-07-23 17:59:33,823,효창동주민센터 앞,1,38,9900.0
4,SPB-16584,2019-07-23 18:19:12,835,남영역 건너편,6,2019-07-23 18:31:45,823,효창동주민센터 앞,10,12,1370.0

In [105]:
data42.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    800000 non-null  object
 1   대여일시     800000 non-null  object
 2   대여대여소번호  800000 non-null  int64
 3   대여대여소명   800000 non-null  object
 4   대여거치대    800000 non-null  int64
 5   반납일시     800000 non-null  object
 6   반납대여소번호  800000 non-null  int64
 7   반납대여소명   800000 non-null  object
 8   반납거치대    800000 non-null  int64
 9   이용시간     800000 non-null  int64
 10  이용거리     800000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [106]:
data42.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [107]:
#data42.to_csv('./서울특별시 공공자전거 대여정보_201907_2.csv', index = False, encoding ='cp949')

In [108]:
data43 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201907_3.csv', engine = 'python')
data43

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-17690,2019-07-24 22:22:56,1906,신도림역 1번 출구 앞,20,2019-07-25 00:00:06,1925,동양미래대학교 정문 옆,9,96,15270.0
1,SPB-02224,2019-07-24 22:23:43,1906,신도림역 1번 출구 앞,11,2019-07-25 00:00:39,1925,동양미래대학교 정문 옆,14,96,15460.0
2,SPB-12528,2019-07-24 22:31:51,1839,수출의 다리 아래,11,2019-07-25 00:14:37,1925,동양미래대학교 정문 옆,4,97,5210.0
3,SPB-11280,2019-07-25 01:05:38,1906,신도림역 1번 출구 앞,15,2019-07-25 01:21:05,1925,동양미래대학교 정문 옆,18,14,2550.0
4,SPB-10771,2019-07-25 01:16:46,1901,신도림동주민센터 앞,1,2019-07-25 01:52:18,1925,동양미래대학교 정문 옆,2,34,2700.0
...,...,...,...,...,...,...,...,...,...,...,...
482606,SPB-20127,2019-07-19 07:41:34,240,문래역 4번출구 앞,8,2019-07-19 07:51:55,9998,영남주차장 정비센터,10,9,480.0
482607,SPB-23276,2019-07-19 07:50:48,832,이촌1동 주민센터 뒤,8,2019-07-19 08:32:51,9998,영남주차장 정비센터,12,40,8840.0
482608,SPB-17321,2019-07-22 12:43:22,266,영등포청과시장 사거리,7,2019-07-22 13:07:29,9998,영남주차장 정비센터,14,23,3320.0
482609,SPB-22044,2019-07-22 12:43:13,266,영등포청과시장 사거리,9,2019-07-22 13:08:53,9998,영남주차장 정비센터,4,25,2960.0
482610,SPB-23900,2019-07-30 07:40:19,240,문래역 4번출구 앞,10,2019-07-30 07:56:14,9998,영남주차장 정비센터,10,15,1190.0

In [109]:
data43 = data43.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data43.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-17690,2019-07-24 22:22:56,1906,신도림역 1번 출구 앞,20,2019-07-25 00:00:06,1925,동양미래대학교 정문 옆,9,96,15270.0
1,SPB-02224,2019-07-24 22:23:43,1906,신도림역 1번 출구 앞,11,2019-07-25 00:00:39,1925,동양미래대학교 정문 옆,14,96,15460.0
2,SPB-12528,2019-07-24 22:31:51,1839,수출의 다리 아래,11,2019-07-25 00:14:37,1925,동양미래대학교 정문 옆,4,97,5210.0
3,SPB-11280,2019-07-25 01:05:38,1906,신도림역 1번 출구 앞,15,2019-07-25 01:21:05,1925,동양미래대학교 정문 옆,18,14,2550.0
4,SPB-10771,2019-07-25 01:16:46,1901,신도림동주민센터 앞,1,2019-07-25 01:52:18,1925,동양미래대학교 정문 옆,2,34,2700.0

In [110]:
data43.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482611 entries, 0 to 482610
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    482611 non-null  object
 1   대여일시     482611 non-null  object
 2   대여대여소번호  482611 non-null  int64
 3   대여대여소명   482611 non-null  object
 4   대여거치대    482611 non-null  int64
 5   반납일시     482611 non-null  object
 6   반납대여소번호  482611 non-null  int64
 7   반납대여소명   482611 non-null  object
 8   반납거치대    482611 non-null  int64
 9   이용시간     482611 non-null  int64
 10  이용거리     482611 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 40.5+ MB

In [111]:
data43.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [112]:
#data43.to_csv('./서울특별시 공공자전거 대여정보_201907_3.csv', index = False, encoding ='cp949')

In [113]:
data44 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201908_1.csv', engine = 'python')
data44

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-19492,2019-08-05 08:37:44,646,장한평역 1번출구 (국민은행앞),8,2019-08-05 08:46:27,3,중랑센터,2,8,1360.0
1,SPB-17426,2019-08-05 13:37:38,3,중랑센터,7,2019-08-05 13:41:29,3,중랑센터,7,3,0.0
2,SPB-17846,2019-08-06 08:40:00,646,장한평역 1번출구 (국민은행앞),3,2019-08-06 08:47:56,3,중랑센터,2,7,1380.0
3,SPB-10871,2019-08-07 08:47:40,529,장한평역 8번 출구 앞,11,2019-08-07 09:06:16,3,중랑센터,7,18,1220.0
4,SPB-17833,2019-08-08 08:43:53,646,장한평역 1번출구 (국민은행앞),5,2019-08-08 08:49:12,3,중랑센터,2,4,1330.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-18514,2019-08-10 23:00:31,825,서빙고동 주민센터 앞,7,2019-08-10 23:22:44,839,보광동 삼성리버빌아파트 앞,9,21,1840.0
799996,SPB-16119,2019-08-10 22:59:46,825,서빙고동 주민센터 앞,6,2019-08-10 23:22:58,839,보광동 삼성리버빌아파트 앞,10,22,0.0
799997,SPB-21949,2019-08-10 22:55:41,439,마포어린이공원,3,2019-08-10 23:43:16,839,보광동 삼성리버빌아파트 앞,3,45,7520.0
799998,SPB-13380,2019-08-10 23:09:14,839,보광동 삼성리버빌아파트 앞,3,2019-08-10 23:56:49,839,보광동 삼성리버빌아파트 앞,9,47,910.0
799999,SPB-05563,2019-08-10 23:09:18,839,보광동 삼성리버빌아파트 앞,9,2019-08-11 00:00:18,839,보광동 삼성리버빌아파트 앞,10,50,910.0

In [114]:
data44 = data44.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data44.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-19492,2019-08-05 08:37:44,646,장한평역 1번출구 (국민은행앞),8,2019-08-05 08:46:27,3,중랑센터,2,8,1360.0
1,SPB-17426,2019-08-05 13:37:38,3,중랑센터,7,2019-08-05 13:41:29,3,중랑센터,7,3,0.0
2,SPB-17846,2019-08-06 08:40:00,646,장한평역 1번출구 (국민은행앞),3,2019-08-06 08:47:56,3,중랑센터,2,7,1380.0
3,SPB-10871,2019-08-07 08:47:40,529,장한평역 8번 출구 앞,11,2019-08-07 09:06:16,3,중랑센터,7,18,1220.0
4,SPB-17833,2019-08-08 08:43:53,646,장한평역 1번출구 (국민은행앞),5,2019-08-08 08:49:12,3,중랑센터,2,4,1330.0

In [115]:
data44.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    800000 non-null  object
 1   대여일시     800000 non-null  object
 2   대여대여소번호  800000 non-null  int64
 3   대여대여소명   800000 non-null  object
 4   대여거치대    800000 non-null  int64
 5   반납일시     800000 non-null  object
 6   반납대여소번호  800000 non-null  int64
 7   반납대여소명   800000 non-null  object
 8   반납거치대    800000 non-null  int64
 9   이용시간     800000 non-null  int64
 10  이용거리     800000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [116]:
data44.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [117]:
#data44.to_csv('./서울특별시 공공자전거 대여정보_201908_1.csv', index = False, encoding ='cp949')

In [118]:
data45 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201908_2.csv', engine = 'python')
data45

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12167,2019-08-10 23:37:24,828,숙대입구역 8번,1,2019-08-11 00:21:59,839,보광동 삼성리버빌아파트 앞,8,43,5010.0
1,SPB-24934,2019-08-11 01:29:05,841,신용산역 1번 출구,4,2019-08-11 01:51:49,839,보광동 삼성리버빌아파트 앞,5,22,4240.0
2,SPB-05750,2019-08-11 01:49:03,111,상수역 2번출구 앞,3,2019-08-11 03:17:21,839,보광동 삼성리버빌아파트 앞,8,87,11110.0
3,SPB-01986,2019-08-11 03:36:53,534,금호사거리,20,2019-08-11 03:54:19,839,보광동 삼성리버빌아파트 앞,9,17,4130.0
4,SPB-23733,2019-08-11 03:25:19,112,극동방송국 앞,10,2019-08-11 04:06:58,839,보광동 삼성리버빌아파트 앞,7,39,10180.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-19879,2019-08-22 08:08:33,1958,강서수도사업소민원센터,1,2019-08-22 08:18:11,1986,태평양물산빌딩,2,9,1730.0
799996,SPB-07167,2019-08-22 08:12:15,1958,강서수도사업소민원센터,7,2019-08-22 08:20:23,1986,태평양물산빌딩,15,7,1810.0
799997,SPB-09982,2019-08-22 08:18:48,1911,구로디지털단지역 앞,6,2019-08-22 08:24:13,1986,태평양물산빌딩,1,5,750.0
799998,SPB-08879,2019-08-22 08:14:25,1814,두산위브아파트 옆 상가건물 앞,4,2019-08-22 08:25:55,1986,태평양물산빌딩,15,11,1510.0
799999,SPB-23519,2019-08-22 08:22:00,1911,구로디지털단지역 앞,1,2019-08-22 08:26:01,1986,태평양물산빌딩,7,3,810.0

In [119]:
data45 = data45.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data45.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12167,2019-08-10 23:37:24,828,숙대입구역 8번,1,2019-08-11 00:21:59,839,보광동 삼성리버빌아파트 앞,8,43,5010.0
1,SPB-24934,2019-08-11 01:29:05,841,신용산역 1번 출구,4,2019-08-11 01:51:49,839,보광동 삼성리버빌아파트 앞,5,22,4240.0
2,SPB-05750,2019-08-11 01:49:03,111,상수역 2번출구 앞,3,2019-08-11 03:17:21,839,보광동 삼성리버빌아파트 앞,8,87,11110.0
3,SPB-01986,2019-08-11 03:36:53,534,금호사거리,20,2019-08-11 03:54:19,839,보광동 삼성리버빌아파트 앞,9,17,4130.0
4,SPB-23733,2019-08-11 03:25:19,112,극동방송국 앞,10,2019-08-11 04:06:58,839,보광동 삼성리버빌아파트 앞,7,39,10180.0

In [120]:
data45.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    800000 non-null  object
 1   대여일시     800000 non-null  object
 2   대여대여소번호  800000 non-null  int64
 3   대여대여소명   800000 non-null  object
 4   대여거치대    800000 non-null  int64
 5   반납일시     800000 non-null  object
 6   반납대여소번호  800000 non-null  int64
 7   반납대여소명   800000 non-null  object
 8   반납거치대    800000 non-null  int64
 9   이용시간     800000 non-null  int64
 10  이용거리     800000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [121]:
data45.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [122]:
#data45.to_csv('./서울특별시 공공자전거 대여정보_201908_2.csv', index = False, encoding ='cp949')

In [123]:
data46 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201908_3.csv', engine = 'python')
data46

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22070,2019-08-22 08:15:29,1985,구로도서관,20,2019-08-22 08:26:23,1986,태평양물산빌딩,15,10,1990.0
1,SPB-08790,2019-08-22 07:40:35,763,목동11단지 아파트,6,2019-08-22 08:26:53,1986,태평양물산빌딩,7,43,7600.0
2,SPB-07910,2019-08-22 08:22:55,2110,조원동 미성아파트,3,2019-08-22 08:27:55,1986,태평양물산빌딩,6,4,650.0
3,SPB-10982,2019-08-22 08:12:53,2102,봉림교 교통섬,1,2019-08-22 08:28:14,1986,태평양물산빌딩,14,15,3390.0
4,SPB-15225,2019-08-22 08:17:01,1914,대림역4번출구,5,2019-08-22 08:28:26,1986,태평양물산빌딩,15,11,1940.0
...,...,...,...,...,...,...,...,...,...,...,...
428693,SPB-05938,2019-08-27 09:32:58,99999,영남단말기정비,3,2019-08-27 09:35:55,99999,영남단말기정비,3,2,0.0
428694,SPB-05938,2019-08-27 11:29:56,99999,영남단말기정비,3,2019-08-27 11:35:18,99999,영남단말기정비,3,5,0.0
428695,SPB-22615,2019-08-28 11:24:58,99999,영남단말기정비,2,2019-08-28 11:27:21,99999,영남단말기정비,2,2,0.0
428696,SPB-22615,2019-08-28 12:59:58,99999,영남단말기정비,2,2019-08-28 13:25:14,99999,영남단말기정비,2,25,0.0
428697,SPB-14335,2019-08-30 11:26:25,99999,영남단말기정비,1,2019-08-30 11:29:20,99999,영남단말기정비,1,2,0.0

In [124]:
data46 = data46.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data46.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22070,2019-08-22 08:15:29,1985,구로도서관,20,2019-08-22 08:26:23,1986,태평양물산빌딩,15,10,1990.0
1,SPB-08790,2019-08-22 07:40:35,763,목동11단지 아파트,6,2019-08-22 08:26:53,1986,태평양물산빌딩,7,43,7600.0
2,SPB-07910,2019-08-22 08:22:55,2110,조원동 미성아파트,3,2019-08-22 08:27:55,1986,태평양물산빌딩,6,4,650.0
3,SPB-10982,2019-08-22 08:12:53,2102,봉림교 교통섬,1,2019-08-22 08:28:14,1986,태평양물산빌딩,14,15,3390.0
4,SPB-15225,2019-08-22 08:17:01,1914,대림역4번출구,5,2019-08-22 08:28:26,1986,태평양물산빌딩,15,11,1940.0

In [125]:
data46.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428698 entries, 0 to 428697
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    428698 non-null  object
 1   대여일시     428698 non-null  object
 2   대여대여소번호  428698 non-null  int64
 3   대여대여소명   428698 non-null  object
 4   대여거치대    428698 non-null  int64
 5   반납일시     428698 non-null  object
 6   반납대여소번호  428698 non-null  int64
 7   반납대여소명   428698 non-null  object
 8   반납거치대    428698 non-null  int64
 9   이용시간     428698 non-null  int64
 10  이용거리     428698 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 36.0+ MB

In [126]:
data46.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [127]:
#data46.to_csv('./서울특별시 공공자전거 대여정보_201908_3.csv', index = False, encoding ='cp949')

In [128]:
data47 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201909_1.csv', engine = 'python')
data47

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21062,2019-09-03 08:44:43,646,장한평역 1번출구 (국민은행앞),3,2019-09-03 09:09:13,3,중랑센터,7,23,1250.0
1,SPB-20126,2019-09-04 00:10:08,1372,KEB은행 고대점,3,2019-09-04 00:18:58,3,중랑센터,7,8,1620.0
2,SPB-00958,2019-09-04 00:41:36,1337,돈암성당 옆,4,2019-09-04 01:03:26,3,중랑센터,7,21,0.0
3,SPB-06836,2019-09-04 08:48:48,529,장한평역 8번 출구 앞,2,2019-09-04 09:05:08,3,중랑센터,7,15,1220.0
4,SPB-16611,2019-09-05 08:46:52,646,장한평역 1번출구 (국민은행앞),3,2019-09-05 08:55:59,3,중랑센터,2,7,1360.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-13269,2019-09-28 16:10:22,960,구파발역 환승센터,10,2019-09-28 16:20:34,903,은평뉴타운 아이파크,9,9,1290.0
799996,SPB-21415,2019-09-28 16:44:04,903,은평뉴타운 아이파크,17,2019-09-28 16:56:58,903,은평뉴타운 아이파크,20,12,1600.0
799997,SPB-07495,2019-09-28 16:40:20,905,구파발역 2번출구,3,2019-09-28 16:59:45,903,은평뉴타운 아이파크,1,18,1590.0
799998,SPB-08670,2019-09-28 17:09:48,962,은평뉴타운 힐데스하임,9,2019-09-28 17:16:57,903,은평뉴타운 아이파크,17,6,1020.0
799999,SPB-18186,2019-09-28 17:30:53,928,은평역사한옥박물관,10,2019-09-28 17:44:27,903,은평뉴타운 아이파크,4,13,3020.0

In [129]:
data47 = data47.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data47.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21062,2019-09-03 08:44:43,646,장한평역 1번출구 (국민은행앞),3,2019-09-03 09:09:13,3,중랑센터,7,23,1250.0
1,SPB-20126,2019-09-04 00:10:08,1372,KEB은행 고대점,3,2019-09-04 00:18:58,3,중랑센터,7,8,1620.0
2,SPB-00958,2019-09-04 00:41:36,1337,돈암성당 옆,4,2019-09-04 01:03:26,3,중랑센터,7,21,0.0
3,SPB-06836,2019-09-04 08:48:48,529,장한평역 8번 출구 앞,2,2019-09-04 09:05:08,3,중랑센터,7,15,1220.0
4,SPB-16611,2019-09-05 08:46:52,646,장한평역 1번출구 (국민은행앞),3,2019-09-05 08:55:59,3,중랑센터,2,7,1360.0

In [130]:
data47.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    800000 non-null  object
 1   대여일시     800000 non-null  object
 2   대여대여소번호  800000 non-null  int64
 3   대여대여소명   800000 non-null  object
 4   대여거치대    800000 non-null  int64
 5   반납일시     800000 non-null  object
 6   반납대여소번호  800000 non-null  int64
 7   반납대여소명   800000 non-null  object
 8   반납거치대    800000 non-null  int64
 9   이용시간     800000 non-null  int64
 10  이용거리     800000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [131]:
data47.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [132]:
#data47.to_csv('./서울특별시 공공자전거 대여정보_201909_1.csv', index = False, encoding ='cp949')

In [2]:
data48 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201909_2.csv', engine = 'python')
data48

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-25059,2019-09-28 17:50:52,960,구파발역 환승센터,2,2019-09-28 18:00:17,903,은평뉴타운 아이파크,2,9,1240.0
1,SPB-16915,2019-09-28 18:44:25,962,은평뉴타운 힐데스하임,3,2019-09-28 18:50:31,903,은평뉴타운 아이파크,19,5,1220.0
2,SPB-07495,2019-09-28 18:07:25,903,은평뉴타운 아이파크,1,2019-09-28 19:05:55,903,은평뉴타운 아이파크,20,58,7270.0
3,SPB-25059,2019-09-28 18:08:43,903,은평뉴타운 아이파크,2,2019-09-28 19:06:09,903,은평뉴타운 아이파크,13,55,6650.0
4,SPB-21314,2019-09-28 18:08:46,903,은평뉴타운 아이파크,3,2019-09-28 19:06:15,903,은평뉴타운 아이파크,18,55,7290.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-24540,2019-09-28 15:53:18,1169,염창역 1번 출구,4,2019-09-28 16:48:27,2002,노들역 1번출구,9,51,11120.0
799996,SPB-05876,2019-09-28 16:48:12,2003,사육신공원앞,4,2019-09-28 16:52:05,2002,노들역 1번출구,1,3,550.0
799997,SPB-24724,2019-09-28 16:47:31,2002,노들역 1번출구,8,2019-09-28 16:52:20,2002,노들역 1번출구,14,4,610.0
799998,SPB-18990,2019-09-28 16:23:28,836,현대자동차서비스 앞,4,2019-09-28 16:55:59,2002,노들역 1번출구,8,32,3230.0
799999,SPB-19899,2019-09-28 16:41:48,2070,노량진역 2번 출구 앞,3,2019-09-28 16:58:49,2002,노들역 1번출구,13,16,1460.0

In [3]:
data48 = data48.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data48.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-25059,2019-09-28 17:50:52,960,구파발역 환승센터,2,2019-09-28 18:00:17,903,은평뉴타운 아이파크,2,9,1240.0
1,SPB-16915,2019-09-28 18:44:25,962,은평뉴타운 힐데스하임,3,2019-09-28 18:50:31,903,은평뉴타운 아이파크,19,5,1220.0
2,SPB-07495,2019-09-28 18:07:25,903,은평뉴타운 아이파크,1,2019-09-28 19:05:55,903,은평뉴타운 아이파크,20,58,7270.0
3,SPB-25059,2019-09-28 18:08:43,903,은평뉴타운 아이파크,2,2019-09-28 19:06:09,903,은평뉴타운 아이파크,13,55,6650.0
4,SPB-21314,2019-09-28 18:08:46,903,은평뉴타운 아이파크,3,2019-09-28 19:06:15,903,은평뉴타운 아이파크,18,55,7290.0

In [4]:
data48.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    800000 non-null  object
 1   대여일시     800000 non-null  object
 2   대여대여소번호  800000 non-null  int64
 3   대여대여소명   800000 non-null  object
 4   대여거치대    800000 non-null  int64
 5   반납일시     800000 non-null  object
 6   반납대여소번호  800000 non-null  int64
 7   반납대여소명   800000 non-null  object
 8   반납거치대    800000 non-null  int64
 9   이용시간     800000 non-null  int64
 10  이용거리     800000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [5]:
data48.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [6]:
#data48.to_csv('./서울특별시 공공자전거 대여정보_201909_2.csv', index = False, encoding ='cp949')

In [7]:
data49 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201909_3.csv', engine = 'python')
data49

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-17003,2019-09-28 16:10:55,368,SK 서린빌딩 앞,4,2019-09-28 17:03:32,2002,노들역 1번출구,14,52,8940.0
1,SPB-14405,2019-09-28 16:48:16,2024,상도역 1번출구,3,2019-09-28 17:03:44,2002,노들역 1번출구,18,15,1910.0
2,SPB-18431,2019-09-28 16:59:54,2002,노들역 1번출구,10,2019-09-28 17:03:57,2002,노들역 1번출구,10,2,30.0
3,SPB-04853,2019-09-28 15:31:49,207,여의나루역 1번출구 앞,32,2019-09-28 17:10:12,2002,노들역 1번출구,19,98,9610.0
4,SPB-11122,2019-09-28 15:35:41,207,여의나루역 1번출구 앞,14,2019-09-28 17:10:37,2002,노들역 1번출구,18,90,9450.0
...,...,...,...,...,...,...,...,...,...,...,...
407584,SPB-24072,2019-09-12 08:56:34,240,문래역 4번출구 앞,9,2019-09-12 09:03:37,99999,영남단말기정비,2,6,720.0
407585,SPB-16130,2019-09-18 10:13:09,99999,영남단말기정비,1,2019-09-18 11:38:30,99999,영남단말기정비,1,85,40.0
407586,SPB-03728,2019-09-25 08:00:28,2183,동방1교,7,2019-09-25 08:54:02,99999,영남단말기정비,5,53,12910.0
407587,SPB-08928,2019-09-30 07:49:27,2183,동방1교,10,2019-09-30 09:42:27,99999,영남단말기정비,7,2,0.0
407588,SPB-06988,2019-09-30 09:58:43,99999,영남단말기정비,5,2019-09-30 13:01:26,99999,영남단말기정비,5,182,10.0

In [8]:
data49 = data49.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data49.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-17003,2019-09-28 16:10:55,368,SK 서린빌딩 앞,4,2019-09-28 17:03:32,2002,노들역 1번출구,14,52,8940.0
1,SPB-14405,2019-09-28 16:48:16,2024,상도역 1번출구,3,2019-09-28 17:03:44,2002,노들역 1번출구,18,15,1910.0
2,SPB-18431,2019-09-28 16:59:54,2002,노들역 1번출구,10,2019-09-28 17:03:57,2002,노들역 1번출구,10,2,30.0
3,SPB-04853,2019-09-28 15:31:49,207,여의나루역 1번출구 앞,32,2019-09-28 17:10:12,2002,노들역 1번출구,19,98,9610.0
4,SPB-11122,2019-09-28 15:35:41,207,여의나루역 1번출구 앞,14,2019-09-28 17:10:37,2002,노들역 1번출구,18,90,9450.0

In [9]:
data49.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 407589 entries, 0 to 407588
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    407589 non-null  object
 1   대여일시     407589 non-null  object
 2   대여대여소번호  407589 non-null  int64
 3   대여대여소명   407589 non-null  object
 4   대여거치대    407589 non-null  int64
 5   반납일시     407589 non-null  object
 6   반납대여소번호  407589 non-null  int64
 7   반납대여소명   407589 non-null  object
 8   반납거치대    407589 non-null  int64
 9   이용시간     407589 non-null  int64
 10  이용거리     407589 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 34.2+ MB

In [10]:
data49.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [11]:
#data49.to_csv('./서울특별시 공공자전거 대여정보_201909_3.csv', index = False, encoding ='cp949')

In [12]:
data50 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201910_1.csv', engine = 'python')
data50

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06409,2019-10-02 08:51:12,646,장한평역 1번출구 (국민은행앞),2,2019-10-02 09:17:06,3,중랑센터,7,25,1410.0
1,SPB-17653,2019-10-04 08:38:01,646,장한평역 1번출구 (국민은행앞),6,2019-10-04 08:46:10,3,중랑센터,2,7,1380.0
2,SPB-12373,2019-10-07 08:49:18,529,장한평역 8번 출구 앞,2,2019-10-07 09:04:22,3,중랑센터,7,14,970.0
3,SPB-22170,2019-10-08 07:50:15,1733,방학사거리 (봄마당 앞),3,2019-10-08 09:19:46,3,중랑센터,7,88,14020.0
4,SPB-19837,2019-10-10 08:38:45,646,장한평역 1번출구 (국민은행앞),6,2019-10-10 08:46:47,3,중랑센터,2,7,1290.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-24236,2019-10-03 19:46:09,627,장안동삼거리 교통섬,4,2019-10-03 19:51:27,658,촬영소 사거리,10,5,950.0
799996,SPB-22729,2019-10-03 21:58:19,602,장안동 사거리,3,2019-10-03 22:01:44,658,촬영소 사거리,3,3,510.0
799997,SPB-25244,2019-10-03 22:05:32,646,장한평역 1번출구 (국민은행앞),7,2019-10-03 22:19:11,658,촬영소 사거리,10,13,1380.0
799998,SPB-12748,2019-10-03 22:05:42,646,장한평역 1번출구 (국민은행앞),6,2019-10-03 22:19:17,658,촬영소 사거리,6,13,1590.0
799999,SPB-23652,2019-10-03 22:57:30,602,장안동 사거리,5,2019-10-03 23:01:46,658,촬영소 사거리,2,4,510.0

In [13]:
data50 = data50.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data50.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06409,2019-10-02 08:51:12,646,장한평역 1번출구 (국민은행앞),2,2019-10-02 09:17:06,3,중랑센터,7,25,1410.0
1,SPB-17653,2019-10-04 08:38:01,646,장한평역 1번출구 (국민은행앞),6,2019-10-04 08:46:10,3,중랑센터,2,7,1380.0
2,SPB-12373,2019-10-07 08:49:18,529,장한평역 8번 출구 앞,2,2019-10-07 09:04:22,3,중랑센터,7,14,970.0
3,SPB-22170,2019-10-08 07:50:15,1733,방학사거리 (봄마당 앞),3,2019-10-08 09:19:46,3,중랑센터,7,88,14020.0
4,SPB-19837,2019-10-10 08:38:45,646,장한평역 1번출구 (국민은행앞),6,2019-10-10 08:46:47,3,중랑센터,2,7,1290.0

In [14]:
data50.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    800000 non-null  object
 1   대여일시     800000 non-null  object
 2   대여대여소번호  800000 non-null  int64
 3   대여대여소명   800000 non-null  object
 4   대여거치대    800000 non-null  int64
 5   반납일시     800000 non-null  object
 6   반납대여소번호  800000 non-null  int64
 7   반납대여소명   800000 non-null  object
 8   반납거치대    800000 non-null  int64
 9   이용시간     800000 non-null  int64
 10  이용거리     800000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [15]:
data50.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [16]:
#data50.to_csv('./서울특별시 공공자전거 대여정보_201910_1.csv', index = False, encoding ='cp949')

In [17]:
data51 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201910_2.csv', engine = 'python')
data51

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12232,2019-10-03 22:58:01,642,신답역 사거리,4,2019-10-03 23:10:58,658,촬영소 사거리,3,12,2200.0
1,SPB-08690,2019-10-03 23:01:24,3500,군자역2번출구,5,2019-10-03 23:18:01,658,촬영소 사거리,1,15,2590.0
2,SPB-10680,2019-10-03 23:12:28,3534,건대입구역 5번출구 뒤,7,2019-10-03 23:35:35,658,촬영소 사거리,3,22,4580.0
3,SPB-24455,2019-10-03 23:59:54,627,장안동삼거리 교통섬,9,2019-10-04 00:11:27,658,촬영소 사거리,5,11,1190.0
4,SPB-23526,2019-10-04 00:00:05,627,장안동삼거리 교통섬,3,2019-10-04 00:11:47,658,촬영소 사거리,2,11,1130.0
...,...,...,...,...,...,...,...,...,...,...,...
799994,SPB-25039,2019-10-15 09:42:01,1642,서울여대 남문,2,2019-10-15 09:55:11,1608,공릉역 1번 출구 앞,4,12,1680.0
799995,SPB-09186,2019-10-15 09:20:22,1610,화랑대역 2번출구 앞,5,2019-10-15 09:56:53,1608,공릉역 1번 출구 앞,3,35,1790.0
799996,SPB-24300,2019-10-15 10:08:47,1684,태릉입구역 5번출구,20,2019-10-15 10:16:32,1608,공릉역 1번 출구 앞,10,7,830.0
799997,SPB-17159,2019-10-15 10:45:32,1655,공릉1단지아파트,12,2019-10-15 10:48:38,1608,공릉역 1번 출구 앞,10,2,610.0
799998,SPB-17798,2019-10-15 10:45:28,1636,백병원 사거리 농협은행 앞,5,2019-10-15 10:59:23,1608,공릉역 1번 출구 앞,8,13,2920.0

In [18]:
data51 = data51.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data51.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12232,2019-10-03 22:58:01,642,신답역 사거리,4,2019-10-03 23:10:58,658,촬영소 사거리,3,12,2200.0
1,SPB-08690,2019-10-03 23:01:24,3500,군자역2번출구,5,2019-10-03 23:18:01,658,촬영소 사거리,1,15,2590.0
2,SPB-10680,2019-10-03 23:12:28,3534,건대입구역 5번출구 뒤,7,2019-10-03 23:35:35,658,촬영소 사거리,3,22,4580.0
3,SPB-24455,2019-10-03 23:59:54,627,장안동삼거리 교통섬,9,2019-10-04 00:11:27,658,촬영소 사거리,5,11,1190.0
4,SPB-23526,2019-10-04 00:00:05,627,장안동삼거리 교통섬,3,2019-10-04 00:11:47,658,촬영소 사거리,2,11,1130.0

In [19]:
data51.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799999 entries, 0 to 799998
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    799999 non-null  object
 1   대여일시     799999 non-null  object
 2   대여대여소번호  799999 non-null  int64
 3   대여대여소명   799999 non-null  object
 4   대여거치대    799999 non-null  int64
 5   반납일시     799999 non-null  object
 6   반납대여소번호  799999 non-null  int64
 7   반납대여소명   799999 non-null  object
 8   반납거치대    799999 non-null  int64
 9   이용시간     799999 non-null  int64
 10  이용거리     799999 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [20]:
data51.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [21]:
#data51.to_csv('./서울특별시 공공자전거 대여정보_201910_2.csv', index = False, encoding ='cp949')

In [22]:
data52 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201910_3.csv', engine = 'python')
data52

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15598,2019-10-15 10:41:26,1689,마들역 3번출구,2,2019-10-15 11:18:17,1608,공릉역 1번 출구 앞,2,36,6520.0
1,SPB-08834,2019-10-15 11:01:13,1689,마들역 3번출구,4,2019-10-15 11:45:15,1608,공릉역 1번 출구 앞,10,43,4650.0
2,SPB-21817,2019-10-15 11:42:23,1401,극동늘푸른아파트,2,2019-10-15 11:52:57,1608,공릉역 1번 출구 앞,5,10,1410.0
3,SPB-09186,2019-10-15 11:16:15,1608,공릉역 1번 출구 앞,3,2019-10-15 11:53:00,1608,공릉역 1번 출구 앞,7,36,3000.0
4,SPB-17390,2019-10-15 11:56:55,1611,과기대 입구(우),17,2019-10-15 12:00:46,1608,공릉역 1번 출구 앞,1,3,810.0
...,...,...,...,...,...,...,...,...,...,...,...
741019,SPB-21025,2019-10-30 08:19:08,2141,미림여고입구 교차로,11,2019-10-30 08:59:37,99999,영남단말기정비,5,37,8140.0
741020,SPB-23664,2019-10-31 08:08:40,2183,동방1교,9,2019-10-31 09:10:37,99999,영남단말기정비,5,61,7760.0
741021,SPB-20948,2019-10-31 10:21:25,99999,영남단말기정비,2,2019-10-31 10:26:16,99999,영남단말기정비,2,4,30.0
741022,SPB-10714,2019-10-31 10:42:00,99999,영남단말기정비,1,2019-10-31 10:46:02,99999,영남단말기정비,1,3,0.0
741023,SPB-17815,2019-10-31 11:09:02,99999,영남단말기정비,5,2019-10-31 13:15:29,99999,영남단말기정비,5,123,0.0

In [23]:
data52 = data52.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data52.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15598,2019-10-15 10:41:26,1689,마들역 3번출구,2,2019-10-15 11:18:17,1608,공릉역 1번 출구 앞,2,36,6520.0
1,SPB-08834,2019-10-15 11:01:13,1689,마들역 3번출구,4,2019-10-15 11:45:15,1608,공릉역 1번 출구 앞,10,43,4650.0
2,SPB-21817,2019-10-15 11:42:23,1401,극동늘푸른아파트,2,2019-10-15 11:52:57,1608,공릉역 1번 출구 앞,5,10,1410.0
3,SPB-09186,2019-10-15 11:16:15,1608,공릉역 1번 출구 앞,3,2019-10-15 11:53:00,1608,공릉역 1번 출구 앞,7,36,3000.0
4,SPB-17390,2019-10-15 11:56:55,1611,과기대 입구(우),17,2019-10-15 12:00:46,1608,공릉역 1번 출구 앞,1,3,810.0

In [24]:
data52.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 741024 entries, 0 to 741023
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    741024 non-null  object
 1   대여일시     741024 non-null  object
 2   대여대여소번호  741024 non-null  int64
 3   대여대여소명   741024 non-null  object
 4   대여거치대    741024 non-null  int64
 5   반납일시     741024 non-null  object
 6   반납대여소번호  741024 non-null  int64
 7   반납대여소명   741024 non-null  object
 8   반납거치대    741024 non-null  int64
 9   이용시간     741024 non-null  int64
 10  이용거리     741024 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 62.2+ MB

In [25]:
data52.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [26]:
#data52.to_csv('./서울특별시 공공자전거 대여정보_201910_3.csv', index = False, encoding ='cp949')

In [27]:
data53 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201911_1.csv', engine = 'python')
data53

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 08:48:31,646,장한평역 1번출구 (국민은행앞),3,2019-11-01 09:01:24,3,중랑센터,7,12,1100.0
1,SPB-16216,2019-11-04 08:38:39,646,장한평역 1번출구 (국민은행앞),2,2019-11-04 08:56:33,3,중랑센터,2,7,1420.0
2,SPB-21097,2019-11-04 08:46:37,646,장한평역 1번출구 (국민은행앞),1,2019-11-04 08:57:35,3,중랑센터,7,10,1020.0
3,SPB-22292,2019-11-05 08:34:59,646,장한평역 1번출구 (국민은행앞),1,2019-11-05 08:45:45,3,중랑센터,2,10,1380.0
4,SPB-07935,2019-11-05 12:29:00,512,뚝섬역 1번 출구 옆,11,2019-11-05 12:39:37,3,중랑센터,7,10,1650.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-22201,2019-11-28 22:26:11,1203,밀리아나2빌딩 앞,19,2019-11-28 22:29:04,1203,밀리아나2빌딩 앞,18,2,20.0
799996,SPB-22290,2019-11-28 22:29:02,1230,송파중학교 정문,9,2019-11-28 22:36:27,1203,밀리아나2빌딩 앞,2,7,900.0
799997,SPB-15270,2019-11-28 22:16:45,2622,올림픽공원역 3번출구,7,2019-11-28 22:49:52,1203,밀리아나2빌딩 앞,7,32,3320.0
799998,SPB-11405,2019-11-28 22:33:25,1050,둔촌역 3번 출입구,14,2019-11-28 22:58:22,1203,밀리아나2빌딩 앞,6,25,4010.0
799999,SPB-13801,2019-11-28 22:51:31,1288,문정중교 사거리,8,2019-11-28 23:00:10,1203,밀리아나2빌딩 앞,12,8,1370.0

In [28]:
data53 = data53.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data53.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 08:48:31,646,장한평역 1번출구 (국민은행앞),3,2019-11-01 09:01:24,3,중랑센터,7,12,1100.0
1,SPB-16216,2019-11-04 08:38:39,646,장한평역 1번출구 (국민은행앞),2,2019-11-04 08:56:33,3,중랑센터,2,7,1420.0
2,SPB-21097,2019-11-04 08:46:37,646,장한평역 1번출구 (국민은행앞),1,2019-11-04 08:57:35,3,중랑센터,7,10,1020.0
3,SPB-22292,2019-11-05 08:34:59,646,장한평역 1번출구 (국민은행앞),1,2019-11-05 08:45:45,3,중랑센터,2,10,1380.0
4,SPB-07935,2019-11-05 12:29:00,512,뚝섬역 1번 출구 옆,11,2019-11-05 12:39:37,3,중랑센터,7,10,1650.0

In [29]:
data53.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800000 entries, 0 to 799999
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    800000 non-null  object
 1   대여일시     800000 non-null  object
 2   대여대여소번호  800000 non-null  int64
 3   대여대여소명   800000 non-null  object
 4   대여거치대    800000 non-null  int64
 5   반납일시     800000 non-null  object
 6   반납대여소번호  800000 non-null  int64
 7   반납대여소명   800000 non-null  object
 8   반납거치대    800000 non-null  int64
 9   이용시간     800000 non-null  int64
 10  이용거리     800000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 67.1+ MB

In [30]:
data53.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [31]:
#data53.to_csv('./서울특별시 공공자전거 대여정보_201911_1.csv', index = False, encoding ='cp949')

In [32]:
data54 = pd.read_csv('C:/Users/psuny/Desktop/대학원/데이터/따릉이 데이터/원본 데이터/공공자전거 대여이력 정보/서울특별시 공공자전거 대여정보_201911_2.csv', engine = 'python')
data54

,자전거번호,대여일시,대여 대여소번호,대여 대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-04392,2019-11-28 23:07:06,2377,수서역 5번출구 뒤,9,2019-11-28 23:18:44,1203,밀리아나2빌딩 앞,5,11,1980.0
1,SPB-23502,2019-11-28 22:43:23,2613,잠실나들목,3,2019-11-29 00:07:07,1203,밀리아나2빌딩 앞,1,82,11130.0
2,SPB-11498,2019-11-29 00:04:35,1256,문정현대아파트 교차로,6,2019-11-29 00:11:24,1203,밀리아나2빌딩 앞,14,6,800.0
3,SPB-16665,2019-11-29 00:02:57,1278,송파구청 교차로,9,2019-11-29 00:21:18,1203,밀리아나2빌딩 앞,2,18,3730.0
4,SPB-14688,2019-11-29 00:17:16,1230,송파중학교 정문,5,2019-11-29 00:26:36,1203,밀리아나2빌딩 앞,3,9,1370.0
...,...,...,...,...,...,...,...,...,...,...,...
678825,SPB-07983,2019-11-26 08:27:07,2183,동방1교,2,2019-11-26 09:31:27,99999,영남단말기정비,5,59,8520.0
678826,SPB-24906,2019-11-27 08:26:19,2141,미림여고입구 교차로,2,2019-11-27 09:26:19,99999,영남단말기정비,5,59,8680.0
678827,SPB-17861,2019-11-28 08:11:43,2183,동방1교,4,2019-11-28 08:54:39,99999,영남단말기정비,5,40,10570.0
678828,SPB-17173,2019-11-29 08:12:31,2183,동방1교,1,2019-11-29 09:17:29,99999,영남단말기정비,5,64,10560.0
678829,SPB-17714,2019-11-29 11:47:16,99999,영남단말기정비,5,2019-11-29 13:04:17,99999,영남단말기정비,5,76,2420.0

In [33]:
data54 = data54.rename(columns = {'자전거번호' : '자전거번호', '대여일시' : '대여일시', '대여 대여소번호' : '대여대여소번호', 
                                '대여 대여소명' : '대여대여소명', '대여거치대' : '대여거치대', '반납일시' : '반납일시',
                                '반납대여소번호' : '반납대여소번호', '반납대여소명' : '반납대여소명', '반납거치대' : '반납거치대',
                                '이용시간' : '이용시간', '이용거리' : '이용거리'})
data54.head()

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-04392,2019-11-28 23:07:06,2377,수서역 5번출구 뒤,9,2019-11-28 23:18:44,1203,밀리아나2빌딩 앞,5,11,1980.0
1,SPB-23502,2019-11-28 22:43:23,2613,잠실나들목,3,2019-11-29 00:07:07,1203,밀리아나2빌딩 앞,1,82,11130.0
2,SPB-11498,2019-11-29 00:04:35,1256,문정현대아파트 교차로,6,2019-11-29 00:11:24,1203,밀리아나2빌딩 앞,14,6,800.0
3,SPB-16665,2019-11-29 00:02:57,1278,송파구청 교차로,9,2019-11-29 00:21:18,1203,밀리아나2빌딩 앞,2,18,3730.0
4,SPB-14688,2019-11-29 00:17:16,1230,송파중학교 정문,5,2019-11-29 00:26:36,1203,밀리아나2빌딩 앞,3,9,1370.0

In [34]:
data54.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 678830 entries, 0 to 678829
Data columns (total 11 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   자전거번호    678830 non-null  object
 1   대여일시     678830 non-null  object
 2   대여대여소번호  678830 non-null  int64
 3   대여대여소명   678830 non-null  object
 4   대여거치대    678830 non-null  int64
 5   반납일시     678830 non-null  object
 6   반납대여소번호  678830 non-null  int64
 7   반납대여소명   678830 non-null  object
 8   반납거치대    678830 non-null  int64
 9   이용시간     678830 non-null  int64
 10  이용거리     678830 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 57.0+ MB

In [35]:
data54.isnull().sum()

자전거번호      0
대여일시       0
대여대여소번호    0
대여대여소명     0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
dtype: int64

In [36]:
#data54.to_csv('./서울특별시 공공자전거 대여정보_201911_2.csv', index = False, encoding ='cp949')

# 여러 개로 나뉜 데이터 병합

- 원랜 54개 파일을 1개로 만들 생각이었는데 각 파일당 용량이 너무 크므로 그냥 각 연도별, 월별로 되어 있는건 놔두고 월이 나뉘어 있는 것만 병합

In [38]:
data = pd.read_csv('./data/공공자전거 대여이력 정보_2020.07_08.csv', engine = 'python')
data

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-36089,2020-07-01 00:00:54,1734,쌍문현대1차아파트 108동 앞,0,2020-07-01 00:03:13,1726,삼익세라믹아파트교차로,0,2,0.0
1,SPB-11402,2020-07-01 00:00:15,610,동대문중 교차로,10,2020-07-01 00:03:23,657,동대문롯데캐슬아파트 앞,1,3,450.0
2,SPB-36935,2020-07-01 00:01:02,3557,서울숲리버뷰자이APT105동 앞,0,2020-07-01 00:04:15,3511,응봉역 1번출구,0,3,0.0
3,SPB-35374,2020-07-01 00:00:04,146,마포역 2번출구 뒤,0,2020-07-01 00:04:22,148,용강동 주민센터 앞,0,4,0.0
4,SPB-37258,2020-07-01 00:01:52,2170,조원동서울본병원,0,2020-07-01 00:04:24,2170,조원동서울본병원,0,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4260105,SPB-41716,2020-08-31 23:12:27,2002,노들역 1번출구,0,2020-09-01 03:05:38,2220,반포본동 주민센터 앞,0,233,0.0
4260106,SPB-31279,2020-08-31 21:08:23,1159,서서울모터리움앞,0,2020-09-01 03:13:03,1103,방화역 4번출구앞,0,365,0.0
4260107,SPB-30443,2020-08-31 23:02:51,242,신길선원가와인아파트 앞,0,2020-09-01 03:22:42,241,신길우성1차아파트 앞 공원,0,260,0.0
4260108,SPB-31171,2020-08-31 21:26:58,726,목동3단지 시내버스정류장,0,2020-09-01 03:42:35,243,이앤씨드림타워 앞,0,376,0.0
4260109,SPB-31725,2020-08-31 23:05:39,2526,반포경남쇼핑 앞,0,2020-09-01 05:12:34,1380,월곡역 5번출구 앞,0,367,0.0

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4260110 entries, 0 to 4260109
Data columns (total 11 columns):
 #   Column   Dtype
---  ------   -----
 0   자전거번호    object
 1   대여일시     object
 2   대여대여소번호  int64
 3   대여대여소명   object
 4   대여거치대    int64
 5   반납일시     object
 6   반납대여소번호  int64
 7   반납대여소명   object
 8   반납거치대    int64
 9   이용시간     int64
 10  이용거리     float64
dtypes: float64(1), int64(5), object(5)
memory usage: 357.5+ MB

In [66]:
data = data.sort_values('대여일시', ignore_index = True)
data

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-30768,2020-07-01 00:00:02,2279,교대역 5번출구뒤,0,2020-07-01 00:08:06,2266,서초역 3번출구,0,8,1057.48
1,SPB-31739,2020-07-01 00:00:02,2621,한성백제역 2번 출구,0,2020-07-01 00:08:53,1218,방이역 4번출구,0,9,1313.50
2,SPB-35374,2020-07-01 00:00:04,146,마포역 2번출구 뒤,0,2020-07-01 00:04:22,148,용강동 주민센터 앞,0,4,0.00
3,SPB-21842,2020-07-01 00:00:08,251,서울지방병무청 버스정류장,3,2020-07-01 00:14:19,1911,구로디지털단지역 앞,9,13,3240.00
4,SPB-35459,2020-07-01 00:00:14,265,영등포유통상가 사거리,0,2020-07-01 00:10:00,283,아크로타워 스퀘어(영등포시장),0,10,0.00
...,...,...,...,...,...,...,...,...,...,...,...
4260105,SPB-36683,2020-08-31 23:59:47,519,양지사거리,0,2020-09-01 00:09:02,378,청계7가 사거리,0,9,0.00
4260106,SPB-37010,2020-08-31 23:59:50,2228,뒷벌공원 옆,0,2020-09-01 00:03:32,2264,이수역 1번출구,0,4,0.00
4260107,SPB-41286,2020-08-31 23:59:54,130,신촌역(2호선) 7번출구 앞,0,2020-09-01 00:24:55,170,가재울 뉴타운 주유소 옆,0,25,0.00
4260108,SPB-40184,2020-08-31 23:59:55,502,뚝섬유원지역 1번출구 앞,0,2020-09-01 00:50:40,502,뚝섬유원지역 1번출구 앞,0,51,0.00
4260109,SPB-22523,2020-08-31 23:59:59,939,은평구청 교차로,15,2020-09-01 00:01:58,900,은평예술회관,6,1,280.00

In [69]:
data1 = data.iloc[:2544880]
data1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-30768,2020-07-01 00:00:02,2279,교대역 5번출구뒤,0,2020-07-01 00:08:06,2266,서초역 3번출구,0,8,1057.48
1,SPB-31739,2020-07-01 00:00:02,2621,한성백제역 2번 출구,0,2020-07-01 00:08:53,1218,방이역 4번출구,0,9,1313.50
2,SPB-35374,2020-07-01 00:00:04,146,마포역 2번출구 뒤,0,2020-07-01 00:04:22,148,용강동 주민센터 앞,0,4,0.00
3,SPB-21842,2020-07-01 00:00:08,251,서울지방병무청 버스정류장,3,2020-07-01 00:14:19,1911,구로디지털단지역 앞,9,13,3240.00
4,SPB-35459,2020-07-01 00:00:14,265,영등포유통상가 사거리,0,2020-07-01 00:10:00,283,아크로타워 스퀘어(영등포시장),0,10,0.00
...,...,...,...,...,...,...,...,...,...,...,...
2544875,SPB-36279,2020-07-31 23:59:50,272,당산육갑문,0,2020-08-01 00:03:08,3215,강변삼성래미안,0,3,0.00
2544876,SPB-33523,2020-07-31 23:59:52,834,효창공원앞역 3번출구 뒤,0,2020-08-01 00:07:47,818,숙명여대 입구 교차로,0,8,0.00
2544877,SPB-31478,2020-07-31 23:59:53,2002,노들역 1번출구,0,2020-08-01 00:05:54,2002,노들역 1번출구,0,6,0.00
2544878,SPB-38097,2020-07-31 23:59:55,3586,군자역 비채온 오피스텔,0,2020-08-01 00:06:16,3549,건영아파트 앞,0,6,0.00
2544879,SPB-31793,2020-07-31 23:59:57,1250,문정2동 주민센터,0,2020-08-01 00:06:06,2615,테라타워2,0,6,0.00

In [70]:
data2 = data.iloc[2544880:]
data2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
2544880,SPB-31470,2020-08-01 00:00:01,714,한국SGI 양천문화회관 앞,0,2020-08-01 00:03:47,740,으뜸공원,0,4,0.0
2544881,SPB-33655,2020-08-01 00:00:01,2549,LH 서초 4단지 403동,0,2020-08-01 00:56:05,2549,LH 서초 4단지 403동,0,56,0.0
2544882,SPB-33402,2020-08-01 00:00:01,1017,맥도날드(길동),0,2020-08-01 00:08:35,1019,다성이즈빌아파트(호원대 대각선 맞은편),0,9,0.0
2544883,SPB-42406,2020-08-01 00:00:04,1402,금란주차장 앞,0,2020-08-01 00:16:15,1447,면목역 3번출구,0,16,0.0
2544884,SPB-38679,2020-08-01 00:00:06,592,건국대학교 학생회관,0,2020-08-01 00:13:57,513,뚝섬역 5번 출구 정류소 옆,0,14,0.0
...,...,...,...,...,...,...,...,...,...,...,...
4260105,SPB-36683,2020-08-31 23:59:47,519,양지사거리,0,2020-09-01 00:09:02,378,청계7가 사거리,0,9,0.0
4260106,SPB-37010,2020-08-31 23:59:50,2228,뒷벌공원 옆,0,2020-09-01 00:03:32,2264,이수역 1번출구,0,4,0.0
4260107,SPB-41286,2020-08-31 23:59:54,130,신촌역(2호선) 7번출구 앞,0,2020-09-01 00:24:55,170,가재울 뉴타운 주유소 옆,0,25,0.0
4260108,SPB-40184,2020-08-31 23:59:55,502,뚝섬유원지역 1번출구 앞,0,2020-09-01 00:50:40,502,뚝섬유원지역 1번출구 앞,0,51,0.0
4260109,SPB-22523,2020-08-31 23:59:59,939,은평구청 교차로,15,2020-09-01 00:01:58,900,은평예술회관,6,1,280.0

In [71]:
data1.to_csv('./공공자전거 대여이력_2020.07.csv', index = False, encoding ='cp949')

In [72]:
data2.to_csv('./공공자전거 대여이력_2020.08.csv', index = False, encoding ='cp949')

-------------------------------------------------

In [74]:
data = pd.read_csv('./data/서울특별시 공공자전거 대여이력 정보_2018년_1월2월3월.csv', engine = 'python')
data

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-02041,2018-01-01 00:00:10,227,양평2나들목 보행통로 입구,9,2018-01-01 00:04:03,227,양평2나들목 보행통로 입구,9,3,50
1,SPB-03796,2018-01-01 00:00:42,2219,"고속터미널역 8-1번, 8-2번 출구 사이",15,2018-01-01 00:25:41,3511,응봉역 1번출구,9,24,7670
2,SPB-02402,2018-01-01 00:00:58,567,성수역 2번출구 앞,13,2018-01-01 00:09:33,3506,영동대교 북단,2,8,1390
3,SPB-01564,2018-01-01 00:01:02,568,청계8가사거리 부근,5,2018-01-01 00:10:13,521,왕십리역 11번 출구 앞,9,8,1820
4,SPB-05713,2018-01-01 00:01:03,361,동묘앞역 1번출구 뒤,4,2018-01-01 00:06:18,383,신당역 12번 출구 뒤,8,4,850
...,...,...,...,...,...,...,...,...,...,...,...
784729,SPB-00326,2018-03-31 23:59:46,2034,사당역 7번출구쪽,4,2018-04-01 00:26:50,2136,신림역 8번출구,7,26,5010
784730,SPB-07675,2018-03-31 23:59:52,266,영등포청과시장 사거리,10,2018-04-01 00:07:30,245,삼성생명 당산사옥 앞,10,7,950
784731,SPB-10926,2018-03-31 23:59:54,926,불광역 8번출구,2,2018-04-01 00:40:21,926,불광역 8번출구,6,39,3130
784732,SPB-15970,2018-03-31 23:59:56,503,더샵스타시티 C동 앞,15,2018-04-01 00:04:38,504,신자초교입구교차로,1,4,590
784733,SPB-04887,2018-03-31 23:59:58,1026,대명초교 입구 교차로,4,2018-04-01 01:45:18,1017,맥도날드(길동),11,104,16830

In [75]:
data = data.sort_values('대여일시', ignore_index = True)
data

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-02041,2018-01-01 00:00:10,227,양평2나들목 보행통로 입구,9,2018-01-01 00:04:03,227,양평2나들목 보행통로 입구,9,3,50
1,SPB-03796,2018-01-01 00:00:42,2219,"고속터미널역 8-1번, 8-2번 출구 사이",15,2018-01-01 00:25:41,3511,응봉역 1번출구,9,24,7670
2,SPB-02402,2018-01-01 00:00:58,567,성수역 2번출구 앞,13,2018-01-01 00:09:33,3506,영동대교 북단,2,8,1390
3,SPB-01564,2018-01-01 00:01:02,568,청계8가사거리 부근,5,2018-01-01 00:10:13,521,왕십리역 11번 출구 앞,9,8,1820
4,SPB-05713,2018-01-01 00:01:03,361,동묘앞역 1번출구 뒤,4,2018-01-01 00:06:18,383,신당역 12번 출구 뒤,8,4,850
...,...,...,...,...,...,...,...,...,...,...,...
784729,SPB-00326,2018-03-31 23:59:46,2034,사당역 7번출구쪽,4,2018-04-01 00:26:50,2136,신림역 8번출구,7,26,5010
784730,SPB-07675,2018-03-31 23:59:52,266,영등포청과시장 사거리,10,2018-04-01 00:07:30,245,삼성생명 당산사옥 앞,10,7,950
784731,SPB-10926,2018-03-31 23:59:54,926,불광역 8번출구,2,2018-04-01 00:40:21,926,불광역 8번출구,6,39,3130
784732,SPB-15970,2018-03-31 23:59:56,503,더샵스타시티 C동 앞,15,2018-04-01 00:04:38,504,신자초교입구교차로,1,4,590
784733,SPB-04887,2018-03-31 23:59:58,1026,대명초교 입구 교차로,4,2018-04-01 01:45:18,1017,맥도날드(길동),11,104,16830

In [80]:
data1 = data.iloc[:161859]
data1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-02041,2018-01-01 00:00:10,227,양평2나들목 보행통로 입구,9,2018-01-01 00:04:03,227,양평2나들목 보행통로 입구,9,3,50
1,SPB-03796,2018-01-01 00:00:42,2219,"고속터미널역 8-1번, 8-2번 출구 사이",15,2018-01-01 00:25:41,3511,응봉역 1번출구,9,24,7670
2,SPB-02402,2018-01-01 00:00:58,567,성수역 2번출구 앞,13,2018-01-01 00:09:33,3506,영동대교 북단,2,8,1390
3,SPB-01564,2018-01-01 00:01:02,568,청계8가사거리 부근,5,2018-01-01 00:10:13,521,왕십리역 11번 출구 앞,9,8,1820
4,SPB-05713,2018-01-01 00:01:03,361,동묘앞역 1번출구 뒤,4,2018-01-01 00:06:18,383,신당역 12번 출구 뒤,8,4,850
...,...,...,...,...,...,...,...,...,...,...,...
161854,SPB-01958,2018-01-31 23:58:22,380,CJ제일제당 앞,8,2018-02-01 00:12:56,388,동성중학교 앞,5,14,2850
161855,SPB-02497,2018-01-31 23:58:29,212,여의도역 1번출구 옆,34,2018-02-01 00:03:01,270,증권거래소후문교차로,1,4,450
161856,SPB-11091,2018-01-31 23:58:31,118,광흥창역 2번출구 앞,7,2018-02-01 00:07:14,114,홍대입구역 8번출구 앞,2,8,2090
161857,SPB-06657,2018-01-31 23:58:41,1014,강동구평생학습관앞,1,2018-02-01 00:05:41,1026,대명초교 입구 교차로,13,6,1540
161858,SPB-11893,2018-01-31 23:59:33,402,상암월드컵파크 9단지 앞,4,2018-02-01 00:14:39,416,상암월드컵파크 1단지 교차로,1,14,2370

In [83]:
data2 = data.iloc[161859:328196]
data2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
161859,SPB-05487,2018-02-01 00:00:02,129,신촌역(2호선) 6번출구 옆,10,2018-02-01 00:04:09,121,마포소방서 앞,15,3,790
161860,SPB-13705,2018-02-01 00:00:16,2321,학여울역 사거리,1,2018-02-01 00:03:38,2337,대모산입구역 2번출구 앞,1,3,540
161861,SPB-01759,2018-02-01 00:00:16,105,합정역 5번출구 앞,4,2018-02-01 00:10:54,119,서강나루 공원,10,10,2010
161862,SPB-13677,2018-02-01 00:00:27,637,KAIST 경영대학 앞,6,2018-02-01 00:32:50,1531,미아사거리 1번 출구,7,32,3800
161863,SPB-04759,2018-02-01 00:00:35,510,서울숲 남문 버스정류소 옆,4,2018-02-01 00:17:54,514,성수사거리 버스정류장 앞,3,17,2880
...,...,...,...,...,...,...,...,...,...,...,...
328191,SPB-06168,2018-02-28 23:53:19,371,동대입구역 6번출구 뒤,10,2018-03-01 00:14:16,388,동성중학교 앞,1,20,3690
328192,SPB-02322,2018-02-28 23:54:41,1637,KT 노원점 건물 앞,7,2018-03-01 00:18:44,1639,희성오피앙,2,23,3470
328193,SPB-10248,2018-02-28 23:54:50,2231,삼성타운(삼성생명) A동 맞은편,3,2018-03-01 00:00:29,2212,서초현대4차아파트 201동 맞은편,17,5,950
328194,SPB-09752,2018-02-28 23:57:18,1244,문정 법조단지8,1,2018-03-01 00:00:42,1240,문정 법조단지4,6,3,390
328195,SPB-10816,2018-02-28 23:57:31,145,공덕역 5번출구,5,2018-03-01 00:02:57,157,애오개역 4번출구 앞,8,5,1110

In [84]:
data3 = data.iloc[328196:]
data3

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
328196,SPB-05011,2018-03-01 00:02:04,2227,방배열린문화센터 앞,13,2018-03-01 00:08:33,2228,뒷벌공원 옆,13,6,940
328197,SPB-09752,2018-03-01 00:02:18,1240,문정 법조단지4,6,2018-03-01 00:12:01,1240,문정 법조단지4,6,9,1090
328198,SPB-04042,2018-03-01 00:08:23,1637,KT 노원점 건물 앞,9,2018-03-01 00:17:26,1625,상계역(4번출구),13,8,1200
328199,SPB-06551,2018-03-01 00:09:06,239,유스호스텔 앞,11,2018-03-01 00:12:39,244,영등포삼환아파트 앞,9,3,610
328200,SPB-02119,2018-03-01 00:09:06,1961,신도림테크노근린공원,8,2018-03-01 00:13:46,1960,화광신문사 앞,6,4,850
...,...,...,...,...,...,...,...,...,...,...,...
784729,SPB-00326,2018-03-31 23:59:46,2034,사당역 7번출구쪽,4,2018-04-01 00:26:50,2136,신림역 8번출구,7,26,5010
784730,SPB-07675,2018-03-31 23:59:52,266,영등포청과시장 사거리,10,2018-04-01 00:07:30,245,삼성생명 당산사옥 앞,10,7,950
784731,SPB-10926,2018-03-31 23:59:54,926,불광역 8번출구,2,2018-04-01 00:40:21,926,불광역 8번출구,6,39,3130
784732,SPB-15970,2018-03-31 23:59:56,503,더샵스타시티 C동 앞,15,2018-04-01 00:04:38,504,신자초교입구교차로,1,4,590
784733,SPB-04887,2018-03-31 23:59:58,1026,대명초교 입구 교차로,4,2018-04-01 01:45:18,1017,맥도날드(길동),11,104,16830

In [85]:
data1.to_csv('./공공자전거 대여이력_2018.01.csv', index = False, encoding ='cp949')

In [86]:
data2.to_csv('./공공자전거 대여이력_2018.02.csv', index = False, encoding ='cp949')

In [87]:
data3.to_csv('./공공자전거 대여이력_2018.03.csv', index = False, encoding ='cp949')

--------------------------------------------------------------------------------------------------

In [89]:
df1 = pd.read_csv('./data/서울특별시 공공자전거 대여이력 정보_2018년_6월_1.csv', engine = 'python')
df1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06782,2018-06-01 00:00:02,1952,천왕연지타운2단지 앞,2,2018-06-01 00:15:13,1969,궁동생태공원,10,14,3060
1,SPB-04511,2018-06-01 00:00:08,1446,중랑전화국 교차로,8,2018-06-01 00:19:01,1456,상아빌딩(우림시장 교차로),3,18,2070
2,SPB-10103,2018-06-01 00:00:08,2244,교육개발원입구 교차로,13,2018-06-01 00:34:08,2276,영동1교 (양재천근린공원),15,32,2750
3,SPB-06223,2018-06-01 00:00:13,349,사직동주민센터,1,2018-06-01 00:06:39,348,독립문역 사거리,4,6,1090
4,SPB-06325,2018-06-01 00:00:15,504,신자초교입구교차로,2,2018-06-01 00:16:36,551,구의삼성쉐르빌 앞,3,16,2200
...,...,...,...,...,...,...,...,...,...,...,...
566854,SPB-17268,2018-06-15 23:59:50,813,삼각지역 3번출구,20,2018-06-16 00:44:51,188,홍은동 정원여중 입구,5,44,9270
566855,SPB-12494,2018-06-15 23:59:53,334,종로3가역 2번출구 뒤,3,2018-06-16 00:10:42,340,혜화동 로터리,3,10,2450
566856,SPB-14821,2018-06-15 23:59:53,1244,문정 법조단지8,1,2018-06-16 00:22:45,2344,리엔파크 2단지 앞,3,22,3250
566857,SPB-09282,2018-06-15 23:59:55,1703,도봉산광역환승센터앞,10,2018-06-16 00:53:15,650,중랑교사거리,6,50,12160
566858,SPB-06087,2018-06-15 23:59:59,818,숙명여대 입구 교차로,2,2018-06-16 00:06:35,820,청파동입구 교차로,6,6,710

In [91]:
df2 = pd.read_csv('./data/서울특별시 공공자전거 대여이력 정보_2018년_6월_2.csv', engine = 'python')
df2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-11906,2018-06-16 00:00:07,932,예일여중,1,2018-06-16 00:16:41,934,신사동 성당,11,15,2160
1,SPB-16954,2018-06-16 00:00:07,272,당산육갑문,16,2018-06-16 02:00:36,1827,독산보도육교 앞 자전거 보관소,9,120,18100
2,SPB-09676,2018-06-16 00:00:11,1036,고덕동 주양쇼핑,7,2018-06-16 00:24:05,1038,강일 다솜 어린이 공원,9,23,3350
3,SPB-07143,2018-06-16 00:00:15,1726,삼익세라믹아파트교차로,7,2018-06-16 00:15:31,1706,기업은행 앞,9,14,1480
4,SPB-13007,2018-06-16 00:00:16,2058,노량진동 맥도널드앞,10,2018-06-16 00:14:25,258,신길역3번출구,8,13,2920
...,...,...,...,...,...,...,...,...,...,...,...
586299,SPB-15985,2018-06-30 23:59:55,505,자양사거리 광진아크로텔 앞,9,2018-07-01 00:09:38,593,자양중앙나들목,5,9,1230
586300,SPB-15081,2018-06-30 23:59:55,1328,월곡역 3번출구,7,2018-07-01 00:18:02,647,신이문역 1번출구,7,17,3600
586301,SPB-13677,2018-06-30 23:59:57,2376,수서역 6번출구 앞,2,2018-07-01 00:20:38,2387,래미안강남힐즈 사거리,5,20,2590
586302,SPB-06577,2018-06-30 23:59:57,1251,석촌역 2번출구,2,2018-07-01 00:57:29,1245,문정 법조단지9,4,57,6640
586303,SPB-03842,2018-06-30 23:59:58,2169,봉천역 2번출구,6,2018-07-01 00:08:05,2112,서울대입구역 마에스트로,7,7,910

In [92]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06782,2018-06-01 00:00:02,1952,천왕연지타운2단지 앞,2,2018-06-01 00:15:13,1969,궁동생태공원,10,14,3060
1,SPB-04511,2018-06-01 00:00:08,1446,중랑전화국 교차로,8,2018-06-01 00:19:01,1456,상아빌딩(우림시장 교차로),3,18,2070
2,SPB-10103,2018-06-01 00:00:08,2244,교육개발원입구 교차로,13,2018-06-01 00:34:08,2276,영동1교 (양재천근린공원),15,32,2750
3,SPB-06223,2018-06-01 00:00:13,349,사직동주민센터,1,2018-06-01 00:06:39,348,독립문역 사거리,4,6,1090
4,SPB-06325,2018-06-01 00:00:15,504,신자초교입구교차로,2,2018-06-01 00:16:36,551,구의삼성쉐르빌 앞,3,16,2200
...,...,...,...,...,...,...,...,...,...,...,...
1153158,SPB-15985,2018-06-30 23:59:55,505,자양사거리 광진아크로텔 앞,9,2018-07-01 00:09:38,593,자양중앙나들목,5,9,1230
1153159,SPB-15081,2018-06-30 23:59:55,1328,월곡역 3번출구,7,2018-07-01 00:18:02,647,신이문역 1번출구,7,17,3600
1153160,SPB-13677,2018-06-30 23:59:57,2376,수서역 6번출구 앞,2,2018-07-01 00:20:38,2387,래미안강남힐즈 사거리,5,20,2590
1153161,SPB-06577,2018-06-30 23:59:57,1251,석촌역 2번출구,2,2018-07-01 00:57:29,1245,문정 법조단지9,4,57,6640
1153162,SPB-03842,2018-06-30 23:59:58,2169,봉천역 2번출구,6,2018-07-01 00:08:05,2112,서울대입구역 마에스트로,7,7,910

In [93]:
df.to_csv('./공공자전거 대여이력_2018.06.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [96]:
df1 = pd.read_excel('./data/서울특별시 공공자전거 대여정보_201807_01.xlsx')
df1

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16427,2018-07-01 00:00:30,2226,신동아럭스빌아파트 앞,7,2018-07-01 00:03:59,2225,백석예술대학교 제3캠퍼스 앞,9,3,570
1,SPB-14104,2018-07-01 00:01:29,129,신촌역(2호선) 6번출구 옆,5,2018-07-01 00:04:57,125,서강대 남문 옆,9,3,660
2,SPB-06808,2018-07-01 00:02:19,1351,안암2교 옆,2,2018-07-01 00:05:00,1351,안암2교 옆,2,2,20
3,SPB-11154,2018-07-01 00:00:43,954,은평뉴타운구파발9단지,3,2018-07-01 00:05:14,903,은평뉴타운 아이파크,8,4,680
4,SPB-10458,2018-07-01 00:02:35,623,서울시립대 정문 앞,12,2018-07-01 00:05:27,623,서울시립대 정문 앞,8,2,10
...,...,...,...,...,...,...,...,...,...,...,...
1048570,SPB-17211,2018-07-30 20:52:09,2220,반포본동 주민센터 앞,4,2018-07-30 22:23:38,2220,반포본동 주민센터 앞,4,91,21930
1048571,SPB-18442,2018-07-30 22:10:36,1215,올림픽공원역 1번출구 앞,14,2018-07-30 22:23:38,1214,오금역 7번 출구 인근,8,12,2030
1048572,SPB-14058,2018-07-30 21:24:00,1601,석계역 문화광장 내 자전거 보관소,3,2018-07-30 22:23:39,1601,석계역 문화광장 내 자전거 보관소,4,59,9040
1048573,SPB-11997,2018-07-30 22:10:48,589,성수역3번출구,8,2018-07-30 22:23:40,509,이마트 버스정류소 옆,7,13,1210
1048574,SPB-15359,2018-07-30 21:25:14,1943,온수역 북측,7,2018-07-30 22:23:43,1943,온수역 북측,7,58,4550

In [97]:
df2 = pd.read_excel('./data/서울특별시 공공자전거 대여정보_201807_02.xlsx')
df2

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12284,2018-07-30 21:25:44,630,동대문구 보건소,10,2018-07-30 21:28:38,641,용두역 4번출구,1,2,340
1,SPB-11173,2018-07-30 21:26:05,168,남가좌동 사거리,5,2018-07-30 21:29:03,170,가재울 뉴타운 주유소 옆,9,3,540
2,SPB-06280,2018-07-30 21:26:49,1708,보건소사거리(다비치안경창동점),5,2018-07-30 21:29:26,1707,도봉구민회관,12,2,330
3,SPB-16456,2018-07-30 21:25:57,310,청계광장 옆,1,2018-07-30 21:29:29,312,시청역 1번출구 뒤,5,3,520
4,SPB-14453,2018-07-30 21:25:10,1308,안암로터리 버스정류장 앞,5,2018-07-30 21:29:37,1351,안암2교 옆,3,3,580
...,...,...,...,...,...,...,...,...,...,...,...
41302,SPB-09771,2018-07-31 23:30:17,1661,당현천근린공원,4,2018-08-01 05:21:17,1661,당현천근린공원,2,93,7560
41303,SPB-14425,2018-07-31 22:04:24,2003,사육신공원앞,7,2018-08-01 07:19:14,257,신길삼거리(우리은행),8,554,3020
41304,SPB-07946,2018-07-31 23:29:01,1911,구로디지털단지역 앞,6,2018-08-01 08:50:58,2107,도림천 신화교,25,49,3930
41305,SPB-10990,2018-07-31 23:46:37,704,남부법원검찰청 교차로,9,2018-08-01 09:26:41,716,신정6동 주민센터 인근,10,19,3270
41306,SPB-12546,2018-07-31 21:55:23,950,구산역 2번 출구,3,2018-08-01 10:51:16,900,은평예술회관,6,236,67710

In [98]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16427,2018-07-01 00:00:30,2226,신동아럭스빌아파트 앞,7,2018-07-01 00:03:59,2225,백석예술대학교 제3캠퍼스 앞,9,3,570
1,SPB-14104,2018-07-01 00:01:29,129,신촌역(2호선) 6번출구 옆,5,2018-07-01 00:04:57,125,서강대 남문 옆,9,3,660
2,SPB-06808,2018-07-01 00:02:19,1351,안암2교 옆,2,2018-07-01 00:05:00,1351,안암2교 옆,2,2,20
3,SPB-11154,2018-07-01 00:00:43,954,은평뉴타운구파발9단지,3,2018-07-01 00:05:14,903,은평뉴타운 아이파크,8,4,680
4,SPB-10458,2018-07-01 00:02:35,623,서울시립대 정문 앞,12,2018-07-01 00:05:27,623,서울시립대 정문 앞,8,2,10
...,...,...,...,...,...,...,...,...,...,...,...
1089877,SPB-09771,2018-07-31 23:30:17,1661,당현천근린공원,4,2018-08-01 05:21:17,1661,당현천근린공원,2,93,7560
1089878,SPB-14425,2018-07-31 22:04:24,2003,사육신공원앞,7,2018-08-01 07:19:14,257,신길삼거리(우리은행),8,554,3020
1089879,SPB-07946,2018-07-31 23:29:01,1911,구로디지털단지역 앞,6,2018-08-01 08:50:58,2107,도림천 신화교,25,49,3930
1089880,SPB-10990,2018-07-31 23:46:37,704,남부법원검찰청 교차로,9,2018-08-01 09:26:41,716,신정6동 주민센터 인근,10,19,3270
1089881,SPB-12546,2018-07-31 21:55:23,950,구산역 2번 출구,3,2018-08-01 10:51:16,900,은평예술회관,6,236,67710

In [105]:
df = df.replace(u'\xa0', u'', regex = True)

In [106]:
df.to_csv('./공공자전거 대여이력_2018.07.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [108]:
df1 = pd.read_excel('./data/서울특별시 공공자전거 대여정보_201809_1.xlsx')
df1

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16278,2018-09-01 00:01:14,1355,보문2교,4,2018-09-01 00:04:14,1338,용문2교 옆,15,2,310
1,SPB-07017,2018-09-01 00:00:08,1914,대림역4번출구,5,2018-09-01 00:05:03,1985,구로도서관,20,4,470
2,SPB-00857,2018-09-01 00:02:42,144,공덕역 8번출구,1,2018-09-01 00:05:04,144,공덕역 8번출구,1,2,0
3,SPB-16272,2018-09-01 00:01:04,1119,염창동 한마음아파트앞(염창동 빛나는 음악학원앞),1,2018-09-01 00:05:08,1115,등촌역 1번출구옆,5,3,510
4,SPB-11204,2018-09-01 00:00:01,559,왕십리역 4번 출구 건너편,10,2018-09-01 00:05:12,537,한양대후문역 부근,9,5,880
...,...,...,...,...,...,...,...,...,...,...,...
1048570,SPB-14310,2018-09-23 20:39:16,1531,미아사거리 1번 출구,1,2018-09-23 20:56:52,1535,효성인텔리안 앞,3,17,2900
1048571,SPB-17308,2018-09-23 19:43:49,2311,학동로 래미안 아파트 앞,6,2018-09-23 20:56:52,1264,천호역 10번 출구 앞,3,72,11670
1048572,SPB-10318,2018-09-23 20:29:23,211,여의도역 4번출구 옆,11,2018-09-23 20:56:53,247,당산역 10번출구 앞,14,27,4590
1048573,SPB-18216,2018-09-23 20:17:55,2206,언남초등학교 앞,4,2018-09-23 20:56:54,2206,언남초등학교 앞,5,38,6940
1048574,SPB-07388,2018-09-23 20:45:01,1009,천호역4번출구(현대백화점),8,2018-09-23 20:56:54,1047,건강보험 강동지사kt,2,11,1290

In [109]:
df2 = pd.read_excel('./data/서울특별시 공공자전거 대여정보_201809_2.xlsx')
df2

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-11299,2018-09-23 20:46:05,125,서강대 남문 옆,2,2018-09-23 20:50:02,129,신촌역(2호선) 6번출구 옆,9,4,670
1,SPB-14425,2018-09-23 20:46:03,1518,SK telecom(수유직영점) 앞,9,2018-09-23 20:50:12,1512,강북중학교 앞,19,3,1150
2,SPB-05366,2018-09-23 20:47:55,3501,광진구청 앞,3,2018-09-23 20:50:20,3520,광진경찰서,5,2,360
3,SPB-05791,2018-09-23 20:45:33,2307,압구정 한양 3차 아파트,1,2018-09-23 20:50:20,2307,압구정 한양 3차 아파트,1,4,360
4,SPB-18318,2018-09-23 20:47:01,591,건국대학교 (행정관),1,2018-09-23 20:50:30,503,더샵스타시티 C동 앞,15,3,850
...,...,...,...,...,...,...,...,...,...,...,...
385062,SPB-13770,2018-09-30 23:59:12,106,합정역 7번출구 앞,3,2018-10-01 03:43:04,248,초원아파트 앞,4,223,7730
385063,SPB-06362,2018-09-30 22:47:39,1208,풍납현대아파트쉼터,3,2018-10-01 05:49:59,1208,풍납현대아파트쉼터,10,422,0
385064,SPB-12767,2018-09-30 22:02:56,2222,사당역 12번출구 뒤,1,2018-10-01 06:29:11,2048,삼일초등학교 인근,1,250,1790
385065,SPB-18187,2018-09-30 23:59:59,277,영등포뉴타운지하상가 2번게이트,5,2018-10-01 07:07:24,268,그랜드컨벤션센터 앞,3,427,2480
385066,SPB-13571,2018-09-30 22:30:16,2025,흑석역 1번출구,6,2018-10-01 07:41:29,247,당산역 10번출구 앞,10,550,8500

In [110]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16278,2018-09-01 00:01:14,1355,보문2교,4,2018-09-01 00:04:14,1338,용문2교 옆,15,2,310
1,SPB-07017,2018-09-01 00:00:08,1914,대림역4번출구,5,2018-09-01 00:05:03,1985,구로도서관,20,4,470
2,SPB-00857,2018-09-01 00:02:42,144,공덕역 8번출구,1,2018-09-01 00:05:04,144,공덕역 8번출구,1,2,0
3,SPB-16272,2018-09-01 00:01:04,1119,염창동 한마음아파트앞(염창동 빛나는 음악학원앞),1,2018-09-01 00:05:08,1115,등촌역 1번출구옆,5,3,510
4,SPB-11204,2018-09-01 00:00:01,559,왕십리역 4번 출구 건너편,10,2018-09-01 00:05:12,537,한양대후문역 부근,9,5,880
...,...,...,...,...,...,...,...,...,...,...,...
1433637,SPB-13770,2018-09-30 23:59:12,106,합정역 7번출구 앞,3,2018-10-01 03:43:04,248,초원아파트 앞,4,223,7730
1433638,SPB-06362,2018-09-30 22:47:39,1208,풍납현대아파트쉼터,3,2018-10-01 05:49:59,1208,풍납현대아파트쉼터,10,422,0
1433639,SPB-12767,2018-09-30 22:02:56,2222,사당역 12번출구 뒤,1,2018-10-01 06:29:11,2048,삼일초등학교 인근,1,250,1790
1433640,SPB-18187,2018-09-30 23:59:59,277,영등포뉴타운지하상가 2번게이트,5,2018-10-01 07:07:24,268,그랜드컨벤션센터 앞,3,427,2480
1433641,SPB-13571,2018-09-30 22:30:16,2025,흑석역 1번출구,6,2018-10-01 07:41:29,247,당산역 10번출구 앞,10,550,8500

In [112]:
df = df.replace(u'\xa0', u'', regex = True)

In [113]:
df.to_csv('./공공자전거 대여이력_2018.09.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [115]:
df1 = pd.read_excel('./data/서울특별시 공공자전거 대여정보_201810_01.xlsx')
df1

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-13621,2018-10-01 00:02:24,127,현대벤처빌 앞,9,2018-10-01 00:04:20,124,서강대 정문 건너편,18,1,350
1,SPB-10560,2018-10-01 00:01:25,1326,상월곡역 1번출구,5,2018-10-01 00:04:37,1328,월곡역 3번출구,4,3,630
2,SPB-16256,2018-10-01 00:00:48,815,LIG강촌아파트 103동앞,10,2018-10-01 00:04:41,832,이촌1동 주민센터 뒤,11,3,44210
3,SPB-07969,2018-10-01 00:01:10,1308,안암로터리 버스정류장 앞,12,2018-10-01 00:04:51,614,용두동 사거리,1,3,560
4,SPB-10866,2018-10-01 00:02:04,575,중앙농협 중곡지점,9,2018-10-01 00:04:52,3510,중곡SK아파트앞,10,2,300
...,...,...,...,...,...,...,...,...,...,...,...
1048570,SPB-17643,2018-10-22 12:45:24,328,탑골공원 앞,3,2018-10-22 12:54:57,354,포르투갈 대사관 앞,2,9,1410
1048571,SPB-16580,2018-10-22 12:01:30,222,시범아파트버스정류장 옆,10,2018-10-22 12:54:58,222,시범아파트버스정류장 옆,10,52,8510
1048572,SPB-04430,2018-10-22 12:39:24,1243,문정 법조단지7,9,2018-10-22 12:55:01,2387,래미안강남힐즈 사거리,2,15,0
1048573,SPB-12247,2018-10-22 12:42:18,509,이마트 버스정류소 옆,5,2018-10-22 12:55:04,592,건국대학교 학생회관,2,12,1890
1048574,SPB-02720,2018-10-22 12:46:58,2033,사당동 아르테스 웨딩앞,5,2018-10-22 12:55:08,2221,하나은행 방배동지점 앞,6,7,1590

In [116]:
df2 = pd.read_excel('./data/서울특별시 공공자전거 대여정보_201810_02.xlsx')
df2

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16369,2018-10-22 12:47:09,3504,원일교회,4,2018-10-22 12:49:32,590,건국대학교 (입학정보관),1,2,500
1,SPB-01983,2018-10-22 12:46:48,191,정명학원,10,2018-10-22 12:50:27,178,증산3교 앞,10,3,530
2,SPB-15300,2018-10-22 12:47:08,3502,중곡역 1번출구,3,2018-10-22 12:50:45,3517,용마사거리,10,3,440
3,SPB-17504,2018-10-22 12:48:25,2264,이수역 1번출구,8,2018-10-22 12:50:56,2230,이수역 4번 출구,5,2,390
4,SPB-04958,2018-10-22 12:47:08,521,왕십리역 11번 출구 앞,9,2018-10-22 12:51:04,525,한양대병원사거리,16,3,730
...,...,...,...,...,...,...,...,...,...,...,...
366460,SPB-14494,2018-10-31 21:34:00,106,합정역 7번출구 앞,8,2018-11-01 08:31:54,101,(구)합정동 주민센터,4,657,1090
366461,SPB-13521,2018-10-31 21:26:20,2034,사당역 7번출구쪽,20,2018-11-01 08:35:16,2230,이수역 4번 출구,3,668,1230
366462,SPB-16660,2018-10-31 23:18:35,125,서강대 남문 옆,14,2018-11-01 08:44:03,374,청구역 2번출구 앞,3,565,10670
366463,SPB-04094,2018-10-31 22:52:45,2139,서울신성초등학교,1,2018-11-01 09:19:56,2176,보라매공원 보도육교,9,626,3890
366464,SPB-07469,2018-10-31 15:26:04,617,청솔우성아파트 앞,4,2018-11-01 10:14:22,639,서울시립대 후문,5,65,3900

In [117]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-13621,2018-10-01 00:02:24,127,현대벤처빌 앞,9,2018-10-01 00:04:20,124,서강대 정문 건너편,18,1,350
1,SPB-10560,2018-10-01 00:01:25,1326,상월곡역 1번출구,5,2018-10-01 00:04:37,1328,월곡역 3번출구,4,3,630
2,SPB-16256,2018-10-01 00:00:48,815,LIG강촌아파트 103동앞,10,2018-10-01 00:04:41,832,이촌1동 주민센터 뒤,11,3,44210
3,SPB-07969,2018-10-01 00:01:10,1308,안암로터리 버스정류장 앞,12,2018-10-01 00:04:51,614,용두동 사거리,1,3,560
4,SPB-10866,2018-10-01 00:02:04,575,중앙농협 중곡지점,9,2018-10-01 00:04:52,3510,중곡SK아파트앞,10,2,300
...,...,...,...,...,...,...,...,...,...,...,...
1415035,SPB-14494,2018-10-31 21:34:00,106,합정역 7번출구 앞,8,2018-11-01 08:31:54,101,(구)합정동 주민센터,4,657,1090
1415036,SPB-13521,2018-10-31 21:26:20,2034,사당역 7번출구쪽,20,2018-11-01 08:35:16,2230,이수역 4번 출구,3,668,1230
1415037,SPB-16660,2018-10-31 23:18:35,125,서강대 남문 옆,14,2018-11-01 08:44:03,374,청구역 2번출구 앞,3,565,10670
1415038,SPB-04094,2018-10-31 22:52:45,2139,서울신성초등학교,1,2018-11-01 09:19:56,2176,보라매공원 보도육교,9,626,3890
1415039,SPB-07469,2018-10-31 15:26:04,617,청솔우성아파트 앞,4,2018-11-01 10:14:22,639,서울시립대 후문,5,65,3900

In [121]:
df = df.replace(u'\u2024', u'', regex = True)

In [119]:
df = df.replace(u'\xa0', u'', regex = True)

In [122]:
df.to_csv('./공공자전거 대여이력_2018.10.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [124]:
df1 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201906_1.csv', engine = 'python')
df1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22040,2019-06-03 08:49:27,646,장한평역 1번출구 (국민은행앞),1,2019-06-03 09:17:10,3,중랑센터,14,27,1330.0
1,SPB-07446,2019-06-03 08:33:22,526,용답토속공원 앞,8,2019-06-03 09:27:16,3,중랑센터,14,54,1180.0
2,SPB-20387,2019-06-05 08:27:47,646,장한평역 1번출구 (국민은행앞),1,2019-06-05 08:41:31,3,중랑센터,2,12,1930.0
3,SPB-16794,2019-06-05 08:46:29,646,장한평역 1번출구 (국민은행앞),6,2019-06-05 08:53:10,3,중랑센터,14,6,1340.0
4,SPB-18266,2019-06-10 08:27:26,529,장한평역 8번 출구 앞,10,2019-06-10 08:33:40,3,중랑센터,2,5,1230.0
...,...,...,...,...,...,...,...,...,...,...,...
799955,SPB-22522,2019-06-01 17:47:47,726,목동3단지 시내버스정류장,6,2019-06-01 18:44:20,735,영도초등학교,5,52,2020.0
799956,SPB-01434,2019-06-01 17:49:18,735,영도초등학교,1,2019-06-01 18:55:01,735,영도초등학교,2,65,7990.0
799957,SPB-18503,2019-06-01 17:48:02,735,영도초등학교,8,2019-06-01 18:55:29,735,영도초등학교,4,66,7910.0
799958,SPB-19656,2019-06-01 18:55:01,762,오목로 무중력지대 앞,1,2019-06-01 19:08:12,735,영도초등학교,10,13,2120.0
799959,SPB-10785,2019-06-01 19:12:48,1136,등촌2파출소,10,2019-06-01 19:23:10,735,영도초등학교,10,10,1620.0

In [127]:
df2 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201906_2.csv', engine = 'python')
df2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-18282,2019-06-01 21:15:39,764,목동청소년수련관,7,2019-06-01 21:22:20,735,영도초등학교,9,6,0.0
1,SPB-06551,2019-06-01 21:28:21,703,오목교역 7번출구 앞,1,2019-06-01 21:40:41,735,영도초등학교,9,11,2210.0
2,SPB-22632,2019-06-01 21:29:30,704,남부법원검찰청 교차로,3,2019-06-01 21:40:51,735,영도초등학교,7,10,1870.0
3,SPB-08605,2019-06-01 21:38:13,731,서울시 도로환경관리센터,10,2019-06-01 21:51:27,735,영도초등학교,9,12,1480.0
4,SPB-01650,2019-06-01 21:39:16,731,서울시 도로환경관리센터,10,2019-06-01 21:55:53,735,영도초등학교,8,16,1500.0
...,...,...,...,...,...,...,...,...,...,...,...
799946,SPB-06091,2019-06-23 19:31:21,1673,노원역?5번출구,9,2019-06-23 19:43:33,1692,온곡초교 교차로,7,11,1530.0
799947,SPB-12632,2019-06-23 19:31:48,1655,공릉1단지아파트,1,2019-06-23 19:57:31,1692,온곡초교 교차로,3,23,4900.0
799948,SPB-10323,2019-06-23 18:57:37,1692,온곡초교 교차로,4,2019-06-23 19:57:32,1692,온곡초교 교차로,5,57,12510.0
799949,SPB-09319,2019-06-23 19:53:33,1625,상계역(4번출구),5,2019-06-23 19:59:35,1692,온곡초교 교차로,1,6,880.0
799950,SPB-02986,2019-06-23 20:17:40,1720,도봉구청 옆(중랑천변),2,2019-06-23 20:31:11,1692,온곡초교 교차로,9,13,2640.0

In [128]:
df3 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201906_3.csv', engine = 'python')
df3

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15349,2019-06-23 20:52:11,1625,상계역(4번출구),4,2019-06-23 20:58:08,1692,온곡초교 교차로,6,5,870.0
1,SPB-09319,2019-06-23 20:44:41,1692,온곡초교 교차로,1,2019-06-23 20:58:34,1692,온곡초교 교차로,8,14,2420.0
2,SPB-13041,2019-06-23 20:51:23,1619,중계동 하나프라자빌딩 앞(중1-1),6,2019-06-23 21:11:33,1692,온곡초교 교차로,5,18,2420.0
3,SPB-18582,2019-06-23 21:43:26,1674,서울북부고용센터앞,15,2019-06-23 22:13:20,1692,온곡초교 교차로,5,28,3110.0
4,SPB-00104,2019-06-23 21:45:17,1674,서울북부고용센터앞,5,2019-06-23 22:13:27,1692,온곡초교 교차로,10,27,3120.0
...,...,...,...,...,...,...,...,...,...,...,...
615716,SPB-22438,2019-06-24 07:40:39,240,문래역 4번출구 앞,8,2019-06-24 07:54:16,9998,영남주차장 정비센터,10,13,900.0
615717,SPB-24455,2019-06-25 07:34:58,240,문래역 4번출구 앞,7,2019-06-25 07:42:14,9998,영남주차장 정비센터,4,6,880.0
615718,SPB-24557,2019-06-26 08:19:57,240,문래역 4번출구 앞,4,2019-06-26 08:27:49,9998,영남주차장 정비센터,10,7,930.0
615719,SPB-00649,2019-06-27 07:38:12,240,문래역 4번출구 앞,9,2019-06-27 07:49:52,9998,영남주차장 정비센터,10,11,1030.0
615720,SPB-14209,2019-06-28 07:37:07,240,문래역 4번출구 앞,10,2019-06-28 07:43:54,9998,영남주차장 정비센터,10,6,1010.0

In [129]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22040,2019-06-03 08:49:27,646,장한평역 1번출구 (국민은행앞),1,2019-06-03 09:17:10,3,중랑센터,14,27,1330.0
1,SPB-07446,2019-06-03 08:33:22,526,용답토속공원 앞,8,2019-06-03 09:27:16,3,중랑센터,14,54,1180.0
2,SPB-20387,2019-06-05 08:27:47,646,장한평역 1번출구 (국민은행앞),1,2019-06-05 08:41:31,3,중랑센터,2,12,1930.0
3,SPB-16794,2019-06-05 08:46:29,646,장한평역 1번출구 (국민은행앞),6,2019-06-05 08:53:10,3,중랑센터,14,6,1340.0
4,SPB-18266,2019-06-10 08:27:26,529,장한평역 8번 출구 앞,10,2019-06-10 08:33:40,3,중랑센터,2,5,1230.0
...,...,...,...,...,...,...,...,...,...,...,...
1599906,SPB-06091,2019-06-23 19:31:21,1673,노원역?5번출구,9,2019-06-23 19:43:33,1692,온곡초교 교차로,7,11,1530.0
1599907,SPB-12632,2019-06-23 19:31:48,1655,공릉1단지아파트,1,2019-06-23 19:57:31,1692,온곡초교 교차로,3,23,4900.0
1599908,SPB-10323,2019-06-23 18:57:37,1692,온곡초교 교차로,4,2019-06-23 19:57:32,1692,온곡초교 교차로,5,57,12510.0
1599909,SPB-09319,2019-06-23 19:53:33,1625,상계역(4번출구),5,2019-06-23 19:59:35,1692,온곡초교 교차로,1,6,880.0
1599910,SPB-02986,2019-06-23 20:17:40,1720,도봉구청 옆(중랑천변),2,2019-06-23 20:31:11,1692,온곡초교 교차로,9,13,2640.0

In [130]:
df = df.append(df3, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22040,2019-06-03 08:49:27,646,장한평역 1번출구 (국민은행앞),1,2019-06-03 09:17:10,3,중랑센터,14,27,1330.0
1,SPB-07446,2019-06-03 08:33:22,526,용답토속공원 앞,8,2019-06-03 09:27:16,3,중랑센터,14,54,1180.0
2,SPB-20387,2019-06-05 08:27:47,646,장한평역 1번출구 (국민은행앞),1,2019-06-05 08:41:31,3,중랑센터,2,12,1930.0
3,SPB-16794,2019-06-05 08:46:29,646,장한평역 1번출구 (국민은행앞),6,2019-06-05 08:53:10,3,중랑센터,14,6,1340.0
4,SPB-18266,2019-06-10 08:27:26,529,장한평역 8번 출구 앞,10,2019-06-10 08:33:40,3,중랑센터,2,5,1230.0
...,...,...,...,...,...,...,...,...,...,...,...
2215627,SPB-22438,2019-06-24 07:40:39,240,문래역 4번출구 앞,8,2019-06-24 07:54:16,9998,영남주차장 정비센터,10,13,900.0
2215628,SPB-24455,2019-06-25 07:34:58,240,문래역 4번출구 앞,7,2019-06-25 07:42:14,9998,영남주차장 정비센터,4,6,880.0
2215629,SPB-24557,2019-06-26 08:19:57,240,문래역 4번출구 앞,4,2019-06-26 08:27:49,9998,영남주차장 정비센터,10,7,930.0
2215630,SPB-00649,2019-06-27 07:38:12,240,문래역 4번출구 앞,9,2019-06-27 07:49:52,9998,영남주차장 정비센터,10,11,1030.0
2215631,SPB-14209,2019-06-28 07:37:07,240,문래역 4번출구 앞,10,2019-06-28 07:43:54,9998,영남주차장 정비센터,10,6,1010.0

In [131]:
df = df.sort_values('대여일시', ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15924,2019-06-01 00:00:02,2000,신도림4차 e편한세상 아파트 1109동 앞,8,2019-06-01 00:41:19,2183,동방1교,2,40,9040.0
1,SPB-09991,2019-06-01 00:00:08,1321,국민은행 종암동지점 앞,10,2019-06-01 00:15:36,1362,보문역6번출구 앞,10,15,2590.0
2,SPB-16229,2019-06-01 00:00:09,131,증산2교,13,2019-06-01 00:36:49,906,연신내역 5번출구150M 아래,2,36,4180.0
3,SPB-12658,2019-06-01 00:00:09,2102,봉림교 교통섬,20,2019-06-01 00:22:39,2107,도림천 신화교,2,20,1650.0
4,SPB-23204,2019-06-01 00:00:09,1709,쌍문역4번출구 주변,15,2019-06-01 00:20:11,1525,미아동 복합청사,3,19,2820.0
...,...,...,...,...,...,...,...,...,...,...,...
2215627,SPB-06273,2019-06-30 23:59:51,1321,국민은행 종암동지점 앞,5,2019-07-01 00:09:38,1372,KEB은행 고대점,12,9,1150.0
2215628,SPB-18305,2019-06-30 23:59:54,3541,커먼그라운드,5,2019-07-01 00:26:47,1440,하나은행 면목지점,10,26,5990.0
2215629,SPB-16142,2019-06-30 23:59:55,1278,송파구청 교차로,3,2019-07-01 00:12:15,2604,삼표레미콘 앞,1,12,2930.0
2215630,SPB-03033,2019-06-30 23:59:56,1451,중랑세무서,3,2019-07-01 00:23:52,1448,코스트코 상봉점,15,23,3600.0
2215631,SPB-13912,2019-06-30 23:59:56,1504,다이소 삼양시장점,9,2019-07-01 00:13:42,1535,효성인텔리안 앞,5,13,2450.0

In [121]:
#df = df.replace(u'\u2024', u'', regex = True)

In [119]:
#df = df.replace(u'\xa0', u'', regex = True)

In [132]:
df.to_csv('./공공자전거 대여이력_2019.06.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [133]:
df1 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201907_1.csv', engine = 'python')
df1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21789,2019-07-02 08:35:17,646,장한평역 1번출구 (국민은행앞),4,2019-07-02 08:42:31,3,중랑센터,2,6,1350.0
1,SPB-22363,2019-07-03 08:35:06,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 08:42:28,3,중랑센터,2,7,1160.0
2,SPB-24965,2019-07-03 08:46:07,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 09:09:44,3,중랑센터,14,23,1270.0
3,SPB-21930,2019-07-04 08:49:57,646,장한평역 1번출구 (국민은행앞),4,2019-07-04 09:04:17,3,중랑센터,14,14,1290.0
4,SPB-17709,2019-07-05 08:45:03,529,장한평역 8번 출구 앞,12,2019-07-05 09:11:47,3,중랑센터,14,26,1200.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-11568,2019-07-22 20:28:29,844,이촌2동 동원베네스트 아파트 앞,10,2019-07-22 20:42:38,823,효창동주민센터 앞,9,14,2370.0
799996,SPB-24122,2019-07-22 20:19:27,119,서강나루 공원,2,2019-07-22 20:44:40,823,효창동주민센터 앞,6,24,4450.0
799997,SPB-22506,2019-07-22 21:32:46,819,선린인터넷 고등학교,2,2019-07-22 21:41:25,823,효창동주민센터 앞,1,8,1170.0
799998,SPB-24122,2019-07-22 21:09:04,823,효창동주민센터 앞,6,2019-07-22 23:04:52,823,효창동주민센터 앞,4,112,8960.0
799999,SPB-16860,2019-07-22 21:13:45,129,신촌역(2호선) 6번출구 옆,8,2019-07-23 00:27:01,823,효창동주민센터 앞,10,192,11960.0

In [134]:
df2 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201907_2.csv', engine = 'python')
df2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-16986,2019-07-23 00:37:06,834,효창공원앞역 3번출구 뒤,12,2019-07-23 00:40:06,823,효창동주민센터 앞,1,2,410.0
1,SPB-19381,2019-07-23 10:25:56,437,대흥역 1번출구,9,2019-07-23 10:43:56,823,효창동주민센터 앞,5,17,2530.0
2,SPB-08367,2019-07-23 11:33:56,2058,노량진동 맥도널드앞,6,2019-07-23 11:57:59,823,효창동주민센터 앞,6,23,4670.0
3,SPB-20188,2019-07-23 17:19:26,565,옥수역 3번출구,7,2019-07-23 17:59:33,823,효창동주민센터 앞,1,38,9900.0
4,SPB-16584,2019-07-23 18:19:12,835,남영역 건너편,6,2019-07-23 18:31:45,823,효창동주민센터 앞,10,12,1370.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-08827,2019-07-24 21:40:45,218,증권거래소 앞,19,2019-07-24 23:22:14,1925,동양미래대학교 정문 옆,3,94,17240.0
799996,SPB-06618,2019-07-24 23:22:34,1931,개봉역(북측광장),2,2019-07-24 23:27:22,1925,동양미래대학교 정문 옆,15,4,1170.0
799997,SPB-16997,2019-07-24 23:33:22,1991,오류동역 맞은편,3,2019-07-24 23:48:09,1925,동양미래대학교 정문 옆,12,14,2690.0
799998,SPB-01886,2019-07-24 23:45:56,1931,개봉역(북측광장),1,2019-07-24 23:55:05,1925,동양미래대학교 정문 옆,6,8,1250.0
799999,SPB-09286,2019-07-24 22:24:21,1906,신도림역 1번 출구 앞,9,2019-07-24 23:59:40,1925,동양미래대학교 정문 옆,8,91,13690.0

In [135]:
df3 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201907_3.csv', engine = 'python')
df3

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-17690,2019-07-24 22:22:56,1906,신도림역 1번 출구 앞,20,2019-07-25 00:00:06,1925,동양미래대학교 정문 옆,9,96,15270.0
1,SPB-02224,2019-07-24 22:23:43,1906,신도림역 1번 출구 앞,11,2019-07-25 00:00:39,1925,동양미래대학교 정문 옆,14,96,15460.0
2,SPB-12528,2019-07-24 22:31:51,1839,수출의 다리 아래,11,2019-07-25 00:14:37,1925,동양미래대학교 정문 옆,4,97,5210.0
3,SPB-11280,2019-07-25 01:05:38,1906,신도림역 1번 출구 앞,15,2019-07-25 01:21:05,1925,동양미래대학교 정문 옆,18,14,2550.0
4,SPB-10771,2019-07-25 01:16:46,1901,신도림동주민센터 앞,1,2019-07-25 01:52:18,1925,동양미래대학교 정문 옆,2,34,2700.0
...,...,...,...,...,...,...,...,...,...,...,...
482606,SPB-20127,2019-07-19 07:41:34,240,문래역 4번출구 앞,8,2019-07-19 07:51:55,9998,영남주차장 정비센터,10,9,480.0
482607,SPB-23276,2019-07-19 07:50:48,832,이촌1동 주민센터 뒤,8,2019-07-19 08:32:51,9998,영남주차장 정비센터,12,40,8840.0
482608,SPB-17321,2019-07-22 12:43:22,266,영등포청과시장 사거리,7,2019-07-22 13:07:29,9998,영남주차장 정비센터,14,23,3320.0
482609,SPB-22044,2019-07-22 12:43:13,266,영등포청과시장 사거리,9,2019-07-22 13:08:53,9998,영남주차장 정비센터,4,25,2960.0
482610,SPB-23900,2019-07-30 07:40:19,240,문래역 4번출구 앞,10,2019-07-30 07:56:14,9998,영남주차장 정비센터,10,15,1190.0

In [136]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21789,2019-07-02 08:35:17,646,장한평역 1번출구 (국민은행앞),4,2019-07-02 08:42:31,3,중랑센터,2,6,1350.0
1,SPB-22363,2019-07-03 08:35:06,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 08:42:28,3,중랑센터,2,7,1160.0
2,SPB-24965,2019-07-03 08:46:07,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 09:09:44,3,중랑센터,14,23,1270.0
3,SPB-21930,2019-07-04 08:49:57,646,장한평역 1번출구 (국민은행앞),4,2019-07-04 09:04:17,3,중랑센터,14,14,1290.0
4,SPB-17709,2019-07-05 08:45:03,529,장한평역 8번 출구 앞,12,2019-07-05 09:11:47,3,중랑센터,14,26,1200.0
...,...,...,...,...,...,...,...,...,...,...,...
1599995,SPB-08827,2019-07-24 21:40:45,218,증권거래소 앞,19,2019-07-24 23:22:14,1925,동양미래대학교 정문 옆,3,94,17240.0
1599996,SPB-06618,2019-07-24 23:22:34,1931,개봉역(북측광장),2,2019-07-24 23:27:22,1925,동양미래대학교 정문 옆,15,4,1170.0
1599997,SPB-16997,2019-07-24 23:33:22,1991,오류동역 맞은편,3,2019-07-24 23:48:09,1925,동양미래대학교 정문 옆,12,14,2690.0
1599998,SPB-01886,2019-07-24 23:45:56,1931,개봉역(북측광장),1,2019-07-24 23:55:05,1925,동양미래대학교 정문 옆,6,8,1250.0
1599999,SPB-09286,2019-07-24 22:24:21,1906,신도림역 1번 출구 앞,9,2019-07-24 23:59:40,1925,동양미래대학교 정문 옆,8,91,13690.0

In [137]:
df = df.append(df3, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21789,2019-07-02 08:35:17,646,장한평역 1번출구 (국민은행앞),4,2019-07-02 08:42:31,3,중랑센터,2,6,1350.0
1,SPB-22363,2019-07-03 08:35:06,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 08:42:28,3,중랑센터,2,7,1160.0
2,SPB-24965,2019-07-03 08:46:07,646,장한평역 1번출구 (국민은행앞),2,2019-07-03 09:09:44,3,중랑센터,14,23,1270.0
3,SPB-21930,2019-07-04 08:49:57,646,장한평역 1번출구 (국민은행앞),4,2019-07-04 09:04:17,3,중랑센터,14,14,1290.0
4,SPB-17709,2019-07-05 08:45:03,529,장한평역 8번 출구 앞,12,2019-07-05 09:11:47,3,중랑센터,14,26,1200.0
...,...,...,...,...,...,...,...,...,...,...,...
2082606,SPB-20127,2019-07-19 07:41:34,240,문래역 4번출구 앞,8,2019-07-19 07:51:55,9998,영남주차장 정비센터,10,9,480.0
2082607,SPB-23276,2019-07-19 07:50:48,832,이촌1동 주민센터 뒤,8,2019-07-19 08:32:51,9998,영남주차장 정비센터,12,40,8840.0
2082608,SPB-17321,2019-07-22 12:43:22,266,영등포청과시장 사거리,7,2019-07-22 13:07:29,9998,영남주차장 정비센터,14,23,3320.0
2082609,SPB-22044,2019-07-22 12:43:13,266,영등포청과시장 사거리,9,2019-07-22 13:08:53,9998,영남주차장 정비센터,4,25,2960.0
2082610,SPB-23900,2019-07-30 07:40:19,240,문래역 4번출구 앞,10,2019-07-30 07:56:14,9998,영남주차장 정비센터,10,15,1190.0

In [138]:
df = df.sort_values('대여일시', ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15508,2019-07-01 00:00:00,2025,흑석역 1번출구,3,2019-07-01 01:14:49,2027,중앙대학교 정문,9,74,19720.0
1,SPB-00485,2019-07-01 00:00:03,402,상암월드컵파크 9단지 앞,20,2019-07-01 00:41:40,415,DMC역 9번출구 앞,10,41,2760.0
2,SPB-23530,2019-07-01 00:00:03,232,양평우림 이비즈센타 앞,7,2019-07-01 01:54:49,231,남부고용노동지청 남측,5,107,23280.0
3,SPB-16822,2019-07-01 00:00:04,2302,교보타워 버스정류장(신논현역 3번출구 후면),2,2019-07-01 00:08:43,2504,신사역 4번출구 뒤,8,8,1370.0
4,SPB-14288,2019-07-01 00:00:06,2102,봉림교 교통섬,2,2019-07-01 00:45:47,2102,봉림교 교통섬,1,45,10720.0
...,...,...,...,...,...,...,...,...,...,...,...
2082606,SPB-15478,2019-07-31 23:59:32,1178,개화산역 2번 출구,4,2019-08-01 00:06:12,1103,방화역 4번출구앞,10,6,1020.0
2082607,SPB-13871,2019-07-31 23:59:40,2615,테라타워2,13,2019-08-01 00:04:17,1201,가락시장역 3번 출구,7,4,720.0
2082608,SPB-10732,2019-07-31 23:59:53,2156,농협 관악문성지점,4,2019-08-01 00:08:43,2066,양문교회 앞,10,8,1860.0
2082609,SPB-05565,2019-07-31 23:59:54,109,제일빌딩 앞,9,2019-08-01 00:07:02,114,홍대입구역 8번출구 앞,2,6,1310.0
2082610,SPB-15578,2019-07-31 23:59:55,1199,우장산역 3번출구,8,2019-08-01 00:12:43,1145,곰달래 문화복지센터 1-2,4,12,2540.0

In [121]:
#df = df.replace(u'\u2024', u'', regex = True)

In [119]:
#df = df.replace(u'\xa0', u'', regex = True)

In [139]:
df.to_csv('./공공자전거 대여이력_2019.07.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [140]:
df1 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201908_1.csv', engine = 'python')
df1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-19492,2019-08-05 08:37:44,646,장한평역 1번출구 (국민은행앞),8,2019-08-05 08:46:27,3,중랑센터,2,8,1360.0
1,SPB-17426,2019-08-05 13:37:38,3,중랑센터,7,2019-08-05 13:41:29,3,중랑센터,7,3,0.0
2,SPB-17846,2019-08-06 08:40:00,646,장한평역 1번출구 (국민은행앞),3,2019-08-06 08:47:56,3,중랑센터,2,7,1380.0
3,SPB-10871,2019-08-07 08:47:40,529,장한평역 8번 출구 앞,11,2019-08-07 09:06:16,3,중랑센터,7,18,1220.0
4,SPB-17833,2019-08-08 08:43:53,646,장한평역 1번출구 (국민은행앞),5,2019-08-08 08:49:12,3,중랑센터,2,4,1330.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-18514,2019-08-10 23:00:31,825,서빙고동 주민센터 앞,7,2019-08-10 23:22:44,839,보광동 삼성리버빌아파트 앞,9,21,1840.0
799996,SPB-16119,2019-08-10 22:59:46,825,서빙고동 주민센터 앞,6,2019-08-10 23:22:58,839,보광동 삼성리버빌아파트 앞,10,22,0.0
799997,SPB-21949,2019-08-10 22:55:41,439,마포어린이공원,3,2019-08-10 23:43:16,839,보광동 삼성리버빌아파트 앞,3,45,7520.0
799998,SPB-13380,2019-08-10 23:09:14,839,보광동 삼성리버빌아파트 앞,3,2019-08-10 23:56:49,839,보광동 삼성리버빌아파트 앞,9,47,910.0
799999,SPB-05563,2019-08-10 23:09:18,839,보광동 삼성리버빌아파트 앞,9,2019-08-11 00:00:18,839,보광동 삼성리버빌아파트 앞,10,50,910.0

In [141]:
df2 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201908_2.csv', engine = 'python')
df2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12167,2019-08-10 23:37:24,828,숙대입구역 8번,1,2019-08-11 00:21:59,839,보광동 삼성리버빌아파트 앞,8,43,5010.0
1,SPB-24934,2019-08-11 01:29:05,841,신용산역 1번 출구,4,2019-08-11 01:51:49,839,보광동 삼성리버빌아파트 앞,5,22,4240.0
2,SPB-05750,2019-08-11 01:49:03,111,상수역 2번출구 앞,3,2019-08-11 03:17:21,839,보광동 삼성리버빌아파트 앞,8,87,11110.0
3,SPB-01986,2019-08-11 03:36:53,534,금호사거리,20,2019-08-11 03:54:19,839,보광동 삼성리버빌아파트 앞,9,17,4130.0
4,SPB-23733,2019-08-11 03:25:19,112,극동방송국 앞,10,2019-08-11 04:06:58,839,보광동 삼성리버빌아파트 앞,7,39,10180.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-19879,2019-08-22 08:08:33,1958,강서수도사업소민원센터,1,2019-08-22 08:18:11,1986,태평양물산빌딩,2,9,1730.0
799996,SPB-07167,2019-08-22 08:12:15,1958,강서수도사업소민원센터,7,2019-08-22 08:20:23,1986,태평양물산빌딩,15,7,1810.0
799997,SPB-09982,2019-08-22 08:18:48,1911,구로디지털단지역 앞,6,2019-08-22 08:24:13,1986,태평양물산빌딩,1,5,750.0
799998,SPB-08879,2019-08-22 08:14:25,1814,두산위브아파트 옆 상가건물 앞,4,2019-08-22 08:25:55,1986,태평양물산빌딩,15,11,1510.0
799999,SPB-23519,2019-08-22 08:22:00,1911,구로디지털단지역 앞,1,2019-08-22 08:26:01,1986,태평양물산빌딩,7,3,810.0

In [142]:
df3 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201908_3.csv', engine = 'python')
df3

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22070,2019-08-22 08:15:29,1985,구로도서관,20,2019-08-22 08:26:23,1986,태평양물산빌딩,15,10,1990.0
1,SPB-08790,2019-08-22 07:40:35,763,목동11단지 아파트,6,2019-08-22 08:26:53,1986,태평양물산빌딩,7,43,7600.0
2,SPB-07910,2019-08-22 08:22:55,2110,조원동 미성아파트,3,2019-08-22 08:27:55,1986,태평양물산빌딩,6,4,650.0
3,SPB-10982,2019-08-22 08:12:53,2102,봉림교 교통섬,1,2019-08-22 08:28:14,1986,태평양물산빌딩,14,15,3390.0
4,SPB-15225,2019-08-22 08:17:01,1914,대림역4번출구,5,2019-08-22 08:28:26,1986,태평양물산빌딩,15,11,1940.0
...,...,...,...,...,...,...,...,...,...,...,...
428693,SPB-05938,2019-08-27 09:32:58,99999,영남단말기정비,3,2019-08-27 09:35:55,99999,영남단말기정비,3,2,0.0
428694,SPB-05938,2019-08-27 11:29:56,99999,영남단말기정비,3,2019-08-27 11:35:18,99999,영남단말기정비,3,5,0.0
428695,SPB-22615,2019-08-28 11:24:58,99999,영남단말기정비,2,2019-08-28 11:27:21,99999,영남단말기정비,2,2,0.0
428696,SPB-22615,2019-08-28 12:59:58,99999,영남단말기정비,2,2019-08-28 13:25:14,99999,영남단말기정비,2,25,0.0
428697,SPB-14335,2019-08-30 11:26:25,99999,영남단말기정비,1,2019-08-30 11:29:20,99999,영남단말기정비,1,2,0.0

In [143]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-19492,2019-08-05 08:37:44,646,장한평역 1번출구 (국민은행앞),8,2019-08-05 08:46:27,3,중랑센터,2,8,1360.0
1,SPB-17426,2019-08-05 13:37:38,3,중랑센터,7,2019-08-05 13:41:29,3,중랑센터,7,3,0.0
2,SPB-17846,2019-08-06 08:40:00,646,장한평역 1번출구 (국민은행앞),3,2019-08-06 08:47:56,3,중랑센터,2,7,1380.0
3,SPB-10871,2019-08-07 08:47:40,529,장한평역 8번 출구 앞,11,2019-08-07 09:06:16,3,중랑센터,7,18,1220.0
4,SPB-17833,2019-08-08 08:43:53,646,장한평역 1번출구 (국민은행앞),5,2019-08-08 08:49:12,3,중랑센터,2,4,1330.0
...,...,...,...,...,...,...,...,...,...,...,...
1599995,SPB-19879,2019-08-22 08:08:33,1958,강서수도사업소민원센터,1,2019-08-22 08:18:11,1986,태평양물산빌딩,2,9,1730.0
1599996,SPB-07167,2019-08-22 08:12:15,1958,강서수도사업소민원센터,7,2019-08-22 08:20:23,1986,태평양물산빌딩,15,7,1810.0
1599997,SPB-09982,2019-08-22 08:18:48,1911,구로디지털단지역 앞,6,2019-08-22 08:24:13,1986,태평양물산빌딩,1,5,750.0
1599998,SPB-08879,2019-08-22 08:14:25,1814,두산위브아파트 옆 상가건물 앞,4,2019-08-22 08:25:55,1986,태평양물산빌딩,15,11,1510.0
1599999,SPB-23519,2019-08-22 08:22:00,1911,구로디지털단지역 앞,1,2019-08-22 08:26:01,1986,태평양물산빌딩,7,3,810.0

In [144]:
df = df.append(df3, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-19492,2019-08-05 08:37:44,646,장한평역 1번출구 (국민은행앞),8,2019-08-05 08:46:27,3,중랑센터,2,8,1360.0
1,SPB-17426,2019-08-05 13:37:38,3,중랑센터,7,2019-08-05 13:41:29,3,중랑센터,7,3,0.0
2,SPB-17846,2019-08-06 08:40:00,646,장한평역 1번출구 (국민은행앞),3,2019-08-06 08:47:56,3,중랑센터,2,7,1380.0
3,SPB-10871,2019-08-07 08:47:40,529,장한평역 8번 출구 앞,11,2019-08-07 09:06:16,3,중랑센터,7,18,1220.0
4,SPB-17833,2019-08-08 08:43:53,646,장한평역 1번출구 (국민은행앞),5,2019-08-08 08:49:12,3,중랑센터,2,4,1330.0
...,...,...,...,...,...,...,...,...,...,...,...
2028693,SPB-05938,2019-08-27 09:32:58,99999,영남단말기정비,3,2019-08-27 09:35:55,99999,영남단말기정비,3,2,0.0
2028694,SPB-05938,2019-08-27 11:29:56,99999,영남단말기정비,3,2019-08-27 11:35:18,99999,영남단말기정비,3,5,0.0
2028695,SPB-22615,2019-08-28 11:24:58,99999,영남단말기정비,2,2019-08-28 11:27:21,99999,영남단말기정비,2,2,0.0
2028696,SPB-22615,2019-08-28 12:59:58,99999,영남단말기정비,2,2019-08-28 13:25:14,99999,영남단말기정비,2,25,0.0
2028697,SPB-14335,2019-08-30 11:26:25,99999,영남단말기정비,1,2019-08-30 11:29:20,99999,영남단말기정비,1,2,0.0

In [145]:
df = df.sort_values('대여일시', ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23685,2019-08-01 00:00:02,2270,서초포레스타 7단지,8,2019-08-01 00:06:59,2206,언남초등학교 앞,11,6,990.0
1,SPB-17786,2019-08-01 00:00:21,590,건국대학교 (입학정보관),2,2019-08-01 00:12:15,593,자양중앙나들목,1,11,1900.0
2,SPB-22428,2019-08-01 00:00:27,1175,대한항공 인력개발센터,15,2019-08-01 00:06:40,1157,강서구청,1,5,1040.0
3,SPB-10605,2019-08-01 00:00:32,1029,롯데 시네마,7,2019-08-01 00:03:36,1274,영파여고 앞,3,3,680.0
4,SPB-19165,2019-08-01 00:00:39,1663,동해문화예술관앞,7,2019-08-01 00:04:41,1601,석계역 문화광장 내 자전거 보관소,5,3,910.0
...,...,...,...,...,...,...,...,...,...,...,...
2028693,SPB-18711,2019-08-31 23:59:55,1260,방이동 한양3차아파트 옆,3,2019-09-01 00:22:59,1011,LIGA 아파트 앞,7,22,4130.0
2028694,SPB-21354,2019-08-31 23:59:58,1328,월곡역 3번출구,2,2019-09-01 00:04:30,1375,생명의 전화 종합복지관 앞 교차로,20,4,510.0
2028695,SPB-14957,2019-08-31 23:59:58,275,신동아아파트,7,2019-09-01 00:12:48,266,영등포청과시장 사거리,6,12,1590.0
2028696,SPB-13829,2019-08-31 23:59:59,502,뚝섬유원지역 1번출구 앞,16,2019-09-01 01:20:03,548,자양나들목,12,79,0.0
2028697,SPB-03194,2019-08-31 23:59:59,2202,청계산입구역 1번출구,5,2019-09-01 00:03:32,2501,서초 포레스타5단지,4,3,610.0

In [146]:
df.to_csv('./공공자전거 대여이력_2019.08.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [147]:
df1 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201909_1.csv', engine = 'python')
df1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21062,2019-09-03 08:44:43,646,장한평역 1번출구 (국민은행앞),3,2019-09-03 09:09:13,3,중랑센터,7,23,1250.0
1,SPB-20126,2019-09-04 00:10:08,1372,KEB은행 고대점,3,2019-09-04 00:18:58,3,중랑센터,7,8,1620.0
2,SPB-00958,2019-09-04 00:41:36,1337,돈암성당 옆,4,2019-09-04 01:03:26,3,중랑센터,7,21,0.0
3,SPB-06836,2019-09-04 08:48:48,529,장한평역 8번 출구 앞,2,2019-09-04 09:05:08,3,중랑센터,7,15,1220.0
4,SPB-16611,2019-09-05 08:46:52,646,장한평역 1번출구 (국민은행앞),3,2019-09-05 08:55:59,3,중랑센터,2,7,1360.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-13269,2019-09-28 16:10:22,960,구파발역 환승센터,10,2019-09-28 16:20:34,903,은평뉴타운 아이파크,9,9,1290.0
799996,SPB-21415,2019-09-28 16:44:04,903,은평뉴타운 아이파크,17,2019-09-28 16:56:58,903,은평뉴타운 아이파크,20,12,1600.0
799997,SPB-07495,2019-09-28 16:40:20,905,구파발역 2번출구,3,2019-09-28 16:59:45,903,은평뉴타운 아이파크,1,18,1590.0
799998,SPB-08670,2019-09-28 17:09:48,962,은평뉴타운 힐데스하임,9,2019-09-28 17:16:57,903,은평뉴타운 아이파크,17,6,1020.0
799999,SPB-18186,2019-09-28 17:30:53,928,은평역사한옥박물관,10,2019-09-28 17:44:27,903,은평뉴타운 아이파크,4,13,3020.0

In [148]:
df2 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201909_2.csv', engine = 'python')
df2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-25059,2019-09-28 17:50:52,960,구파발역 환승센터,2,2019-09-28 18:00:17,903,은평뉴타운 아이파크,2,9,1240.0
1,SPB-16915,2019-09-28 18:44:25,962,은평뉴타운 힐데스하임,3,2019-09-28 18:50:31,903,은평뉴타운 아이파크,19,5,1220.0
2,SPB-07495,2019-09-28 18:07:25,903,은평뉴타운 아이파크,1,2019-09-28 19:05:55,903,은평뉴타운 아이파크,20,58,7270.0
3,SPB-25059,2019-09-28 18:08:43,903,은평뉴타운 아이파크,2,2019-09-28 19:06:09,903,은평뉴타운 아이파크,13,55,6650.0
4,SPB-21314,2019-09-28 18:08:46,903,은평뉴타운 아이파크,3,2019-09-28 19:06:15,903,은평뉴타운 아이파크,18,55,7290.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-24540,2019-09-28 15:53:18,1169,염창역 1번 출구,4,2019-09-28 16:48:27,2002,노들역 1번출구,9,51,11120.0
799996,SPB-05876,2019-09-28 16:48:12,2003,사육신공원앞,4,2019-09-28 16:52:05,2002,노들역 1번출구,1,3,550.0
799997,SPB-24724,2019-09-28 16:47:31,2002,노들역 1번출구,8,2019-09-28 16:52:20,2002,노들역 1번출구,14,4,610.0
799998,SPB-18990,2019-09-28 16:23:28,836,현대자동차서비스 앞,4,2019-09-28 16:55:59,2002,노들역 1번출구,8,32,3230.0
799999,SPB-19899,2019-09-28 16:41:48,2070,노량진역 2번 출구 앞,3,2019-09-28 16:58:49,2002,노들역 1번출구,13,16,1460.0

In [149]:
df3 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201909_3.csv', engine = 'python')
df3

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-17003,2019-09-28 16:10:55,368,SK 서린빌딩 앞,4,2019-09-28 17:03:32,2002,노들역 1번출구,14,52,8940.0
1,SPB-14405,2019-09-28 16:48:16,2024,상도역 1번출구,3,2019-09-28 17:03:44,2002,노들역 1번출구,18,15,1910.0
2,SPB-18431,2019-09-28 16:59:54,2002,노들역 1번출구,10,2019-09-28 17:03:57,2002,노들역 1번출구,10,2,30.0
3,SPB-04853,2019-09-28 15:31:49,207,여의나루역 1번출구 앞,32,2019-09-28 17:10:12,2002,노들역 1번출구,19,98,9610.0
4,SPB-11122,2019-09-28 15:35:41,207,여의나루역 1번출구 앞,14,2019-09-28 17:10:37,2002,노들역 1번출구,18,90,9450.0
...,...,...,...,...,...,...,...,...,...,...,...
407584,SPB-24072,2019-09-12 08:56:34,240,문래역 4번출구 앞,9,2019-09-12 09:03:37,99999,영남단말기정비,2,6,720.0
407585,SPB-16130,2019-09-18 10:13:09,99999,영남단말기정비,1,2019-09-18 11:38:30,99999,영남단말기정비,1,85,40.0
407586,SPB-03728,2019-09-25 08:00:28,2183,동방1교,7,2019-09-25 08:54:02,99999,영남단말기정비,5,53,12910.0
407587,SPB-08928,2019-09-30 07:49:27,2183,동방1교,10,2019-09-30 09:42:27,99999,영남단말기정비,7,2,0.0
407588,SPB-06988,2019-09-30 09:58:43,99999,영남단말기정비,5,2019-09-30 13:01:26,99999,영남단말기정비,5,182,10.0

In [150]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21062,2019-09-03 08:44:43,646,장한평역 1번출구 (국민은행앞),3,2019-09-03 09:09:13,3,중랑센터,7,23,1250.0
1,SPB-20126,2019-09-04 00:10:08,1372,KEB은행 고대점,3,2019-09-04 00:18:58,3,중랑센터,7,8,1620.0
2,SPB-00958,2019-09-04 00:41:36,1337,돈암성당 옆,4,2019-09-04 01:03:26,3,중랑센터,7,21,0.0
3,SPB-06836,2019-09-04 08:48:48,529,장한평역 8번 출구 앞,2,2019-09-04 09:05:08,3,중랑센터,7,15,1220.0
4,SPB-16611,2019-09-05 08:46:52,646,장한평역 1번출구 (국민은행앞),3,2019-09-05 08:55:59,3,중랑센터,2,7,1360.0
...,...,...,...,...,...,...,...,...,...,...,...
1599995,SPB-24540,2019-09-28 15:53:18,1169,염창역 1번 출구,4,2019-09-28 16:48:27,2002,노들역 1번출구,9,51,11120.0
1599996,SPB-05876,2019-09-28 16:48:12,2003,사육신공원앞,4,2019-09-28 16:52:05,2002,노들역 1번출구,1,3,550.0
1599997,SPB-24724,2019-09-28 16:47:31,2002,노들역 1번출구,8,2019-09-28 16:52:20,2002,노들역 1번출구,14,4,610.0
1599998,SPB-18990,2019-09-28 16:23:28,836,현대자동차서비스 앞,4,2019-09-28 16:55:59,2002,노들역 1번출구,8,32,3230.0
1599999,SPB-19899,2019-09-28 16:41:48,2070,노량진역 2번 출구 앞,3,2019-09-28 16:58:49,2002,노들역 1번출구,13,16,1460.0

In [151]:
df = df.append(df3, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-21062,2019-09-03 08:44:43,646,장한평역 1번출구 (국민은행앞),3,2019-09-03 09:09:13,3,중랑센터,7,23,1250.0
1,SPB-20126,2019-09-04 00:10:08,1372,KEB은행 고대점,3,2019-09-04 00:18:58,3,중랑센터,7,8,1620.0
2,SPB-00958,2019-09-04 00:41:36,1337,돈암성당 옆,4,2019-09-04 01:03:26,3,중랑센터,7,21,0.0
3,SPB-06836,2019-09-04 08:48:48,529,장한평역 8번 출구 앞,2,2019-09-04 09:05:08,3,중랑센터,7,15,1220.0
4,SPB-16611,2019-09-05 08:46:52,646,장한평역 1번출구 (국민은행앞),3,2019-09-05 08:55:59,3,중랑센터,2,7,1360.0
...,...,...,...,...,...,...,...,...,...,...,...
2007584,SPB-24072,2019-09-12 08:56:34,240,문래역 4번출구 앞,9,2019-09-12 09:03:37,99999,영남단말기정비,2,6,720.0
2007585,SPB-16130,2019-09-18 10:13:09,99999,영남단말기정비,1,2019-09-18 11:38:30,99999,영남단말기정비,1,85,40.0
2007586,SPB-03728,2019-09-25 08:00:28,2183,동방1교,7,2019-09-25 08:54:02,99999,영남단말기정비,5,53,12910.0
2007587,SPB-08928,2019-09-30 07:49:27,2183,동방1교,10,2019-09-30 09:42:27,99999,영남단말기정비,7,2,0.0
2007588,SPB-06988,2019-09-30 09:58:43,99999,영남단말기정비,5,2019-09-30 13:01:26,99999,영남단말기정비,5,182,10.0

In [152]:
df = df.sort_values('대여일시', ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15562,2019-09-01 00:00:01,1412,면목초등학교,8,2019-09-01 00:50:47,1412,면목초등학교,2,50,2320.0
1,SPB-25067,2019-09-01 00:00:01,1158,가양역 8번출구,8,2019-09-01 00:56:25,1160,양천향교역 7번출구앞,12,53,4250.0
2,SPB-23223,2019-09-01 00:00:01,1955,디지털입구 교차로,9,2019-09-01 00:46:02,2171,서울대입구역 5번출구,6,42,5370.0
3,SPB-13407,2019-09-01 00:00:02,147,마포역 4번출구 뒤,5,2019-09-01 00:08:03,439,마포어린이공원,1,7,560.0
4,SPB-19692,2019-09-01 00:00:02,1332,석계역 5번출구 건너편,6,2019-09-01 00:28:09,634,외국어대 정문 앞,12,27,2560.0
...,...,...,...,...,...,...,...,...,...,...,...
2007584,SPB-05023,2019-09-30 23:59:52,2387,래미안강남힐즈 사거리,10,2019-10-01 00:09:02,2384,자곡사거리,10,8,1200.0
2007585,SPB-09057,2019-09-30 23:59:57,1689,마들역 3번출구,5,2019-10-01 00:14:09,1708,보건소사거리(다비치안경창동점),3,14,2060.0
2007586,SPB-01570,2019-09-30 23:59:58,574,아차산역4번출구,6,2019-10-01 00:06:59,3518,군자역 7번출구뒤,5,6,0.0
2007587,SPB-19458,2019-09-30 23:59:59,2384,자곡사거리,4,2019-10-01 00:07:24,2387,래미안강남힐즈 사거리,9,7,970.0
2007588,SPB-18328,2019-09-30 23:59:59,183,하늘채코오롱아파트 건너편,5,2019-10-01 00:23:46,934,신사동 성당,1,23,5190.0

In [153]:
df.to_csv('./공공자전거 대여이력_2019.09.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [154]:
df1 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201910_1.csv', engine = 'python')
df1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06409,2019-10-02 08:51:12,646,장한평역 1번출구 (국민은행앞),2,2019-10-02 09:17:06,3,중랑센터,7,25,1410.0
1,SPB-17653,2019-10-04 08:38:01,646,장한평역 1번출구 (국민은행앞),6,2019-10-04 08:46:10,3,중랑센터,2,7,1380.0
2,SPB-12373,2019-10-07 08:49:18,529,장한평역 8번 출구 앞,2,2019-10-07 09:04:22,3,중랑센터,7,14,970.0
3,SPB-22170,2019-10-08 07:50:15,1733,방학사거리 (봄마당 앞),3,2019-10-08 09:19:46,3,중랑센터,7,88,14020.0
4,SPB-19837,2019-10-10 08:38:45,646,장한평역 1번출구 (국민은행앞),6,2019-10-10 08:46:47,3,중랑센터,2,7,1290.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-24236,2019-10-03 19:46:09,627,장안동삼거리 교통섬,4,2019-10-03 19:51:27,658,촬영소 사거리,10,5,950.0
799996,SPB-22729,2019-10-03 21:58:19,602,장안동 사거리,3,2019-10-03 22:01:44,658,촬영소 사거리,3,3,510.0
799997,SPB-25244,2019-10-03 22:05:32,646,장한평역 1번출구 (국민은행앞),7,2019-10-03 22:19:11,658,촬영소 사거리,10,13,1380.0
799998,SPB-12748,2019-10-03 22:05:42,646,장한평역 1번출구 (국민은행앞),6,2019-10-03 22:19:17,658,촬영소 사거리,6,13,1590.0
799999,SPB-23652,2019-10-03 22:57:30,602,장안동 사거리,5,2019-10-03 23:01:46,658,촬영소 사거리,2,4,510.0

In [155]:
df2 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201910_2.csv', engine = 'python')
df2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-12232,2019-10-03 22:58:01,642,신답역 사거리,4,2019-10-03 23:10:58,658,촬영소 사거리,3,12,2200.0
1,SPB-08690,2019-10-03 23:01:24,3500,군자역2번출구,5,2019-10-03 23:18:01,658,촬영소 사거리,1,15,2590.0
2,SPB-10680,2019-10-03 23:12:28,3534,건대입구역 5번출구 뒤,7,2019-10-03 23:35:35,658,촬영소 사거리,3,22,4580.0
3,SPB-24455,2019-10-03 23:59:54,627,장안동삼거리 교통섬,9,2019-10-04 00:11:27,658,촬영소 사거리,5,11,1190.0
4,SPB-23526,2019-10-04 00:00:05,627,장안동삼거리 교통섬,3,2019-10-04 00:11:47,658,촬영소 사거리,2,11,1130.0
...,...,...,...,...,...,...,...,...,...,...,...
799994,SPB-25039,2019-10-15 09:42:01,1642,서울여대 남문,2,2019-10-15 09:55:11,1608,공릉역 1번 출구 앞,4,12,1680.0
799995,SPB-09186,2019-10-15 09:20:22,1610,화랑대역 2번출구 앞,5,2019-10-15 09:56:53,1608,공릉역 1번 출구 앞,3,35,1790.0
799996,SPB-24300,2019-10-15 10:08:47,1684,태릉입구역 5번출구,20,2019-10-15 10:16:32,1608,공릉역 1번 출구 앞,10,7,830.0
799997,SPB-17159,2019-10-15 10:45:32,1655,공릉1단지아파트,12,2019-10-15 10:48:38,1608,공릉역 1번 출구 앞,10,2,610.0
799998,SPB-17798,2019-10-15 10:45:28,1636,백병원 사거리 농협은행 앞,5,2019-10-15 10:59:23,1608,공릉역 1번 출구 앞,8,13,2920.0

In [156]:
df3 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201910_3.csv', engine = 'python')
df3

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-15598,2019-10-15 10:41:26,1689,마들역 3번출구,2,2019-10-15 11:18:17,1608,공릉역 1번 출구 앞,2,36,6520.0
1,SPB-08834,2019-10-15 11:01:13,1689,마들역 3번출구,4,2019-10-15 11:45:15,1608,공릉역 1번 출구 앞,10,43,4650.0
2,SPB-21817,2019-10-15 11:42:23,1401,극동늘푸른아파트,2,2019-10-15 11:52:57,1608,공릉역 1번 출구 앞,5,10,1410.0
3,SPB-09186,2019-10-15 11:16:15,1608,공릉역 1번 출구 앞,3,2019-10-15 11:53:00,1608,공릉역 1번 출구 앞,7,36,3000.0
4,SPB-17390,2019-10-15 11:56:55,1611,과기대 입구(우),17,2019-10-15 12:00:46,1608,공릉역 1번 출구 앞,1,3,810.0
...,...,...,...,...,...,...,...,...,...,...,...
741019,SPB-21025,2019-10-30 08:19:08,2141,미림여고입구 교차로,11,2019-10-30 08:59:37,99999,영남단말기정비,5,37,8140.0
741020,SPB-23664,2019-10-31 08:08:40,2183,동방1교,9,2019-10-31 09:10:37,99999,영남단말기정비,5,61,7760.0
741021,SPB-20948,2019-10-31 10:21:25,99999,영남단말기정비,2,2019-10-31 10:26:16,99999,영남단말기정비,2,4,30.0
741022,SPB-10714,2019-10-31 10:42:00,99999,영남단말기정비,1,2019-10-31 10:46:02,99999,영남단말기정비,1,3,0.0
741023,SPB-17815,2019-10-31 11:09:02,99999,영남단말기정비,5,2019-10-31 13:15:29,99999,영남단말기정비,5,123,0.0

In [157]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06409,2019-10-02 08:51:12,646,장한평역 1번출구 (국민은행앞),2,2019-10-02 09:17:06,3,중랑센터,7,25,1410.0
1,SPB-17653,2019-10-04 08:38:01,646,장한평역 1번출구 (국민은행앞),6,2019-10-04 08:46:10,3,중랑센터,2,7,1380.0
2,SPB-12373,2019-10-07 08:49:18,529,장한평역 8번 출구 앞,2,2019-10-07 09:04:22,3,중랑센터,7,14,970.0
3,SPB-22170,2019-10-08 07:50:15,1733,방학사거리 (봄마당 앞),3,2019-10-08 09:19:46,3,중랑센터,7,88,14020.0
4,SPB-19837,2019-10-10 08:38:45,646,장한평역 1번출구 (국민은행앞),6,2019-10-10 08:46:47,3,중랑센터,2,7,1290.0
...,...,...,...,...,...,...,...,...,...,...,...
1599994,SPB-25039,2019-10-15 09:42:01,1642,서울여대 남문,2,2019-10-15 09:55:11,1608,공릉역 1번 출구 앞,4,12,1680.0
1599995,SPB-09186,2019-10-15 09:20:22,1610,화랑대역 2번출구 앞,5,2019-10-15 09:56:53,1608,공릉역 1번 출구 앞,3,35,1790.0
1599996,SPB-24300,2019-10-15 10:08:47,1684,태릉입구역 5번출구,20,2019-10-15 10:16:32,1608,공릉역 1번 출구 앞,10,7,830.0
1599997,SPB-17159,2019-10-15 10:45:32,1655,공릉1단지아파트,12,2019-10-15 10:48:38,1608,공릉역 1번 출구 앞,10,2,610.0
1599998,SPB-17798,2019-10-15 10:45:28,1636,백병원 사거리 농협은행 앞,5,2019-10-15 10:59:23,1608,공릉역 1번 출구 앞,8,13,2920.0

In [158]:
df = df.append(df3, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06409,2019-10-02 08:51:12,646,장한평역 1번출구 (국민은행앞),2,2019-10-02 09:17:06,3,중랑센터,7,25,1410.0
1,SPB-17653,2019-10-04 08:38:01,646,장한평역 1번출구 (국민은행앞),6,2019-10-04 08:46:10,3,중랑센터,2,7,1380.0
2,SPB-12373,2019-10-07 08:49:18,529,장한평역 8번 출구 앞,2,2019-10-07 09:04:22,3,중랑센터,7,14,970.0
3,SPB-22170,2019-10-08 07:50:15,1733,방학사거리 (봄마당 앞),3,2019-10-08 09:19:46,3,중랑센터,7,88,14020.0
4,SPB-19837,2019-10-10 08:38:45,646,장한평역 1번출구 (국민은행앞),6,2019-10-10 08:46:47,3,중랑센터,2,7,1290.0
...,...,...,...,...,...,...,...,...,...,...,...
2341018,SPB-21025,2019-10-30 08:19:08,2141,미림여고입구 교차로,11,2019-10-30 08:59:37,99999,영남단말기정비,5,37,8140.0
2341019,SPB-23664,2019-10-31 08:08:40,2183,동방1교,9,2019-10-31 09:10:37,99999,영남단말기정비,5,61,7760.0
2341020,SPB-20948,2019-10-31 10:21:25,99999,영남단말기정비,2,2019-10-31 10:26:16,99999,영남단말기정비,2,4,30.0
2341021,SPB-10714,2019-10-31 10:42:00,99999,영남단말기정비,1,2019-10-31 10:46:02,99999,영남단말기정비,1,3,0.0
2341022,SPB-17815,2019-10-31 11:09:02,99999,영남단말기정비,5,2019-10-31 13:15:29,99999,영남단말기정비,5,123,0.0

In [159]:
df = df.sort_values('대여일시', ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-22110,2019-10-01 00:00:00,1361,홍익중고 입구,20,2019-10-01 00:11:22,1355,보문2교,1,10,2000.0
1,SPB-05925,2019-10-01 00:00:00,1109,공항시장역 4번출구,6,2019-10-01 00:04:40,1150,송정역 1번출구,9,4,350.0
2,SPB-14624,2019-10-01 00:00:01,1235,잠실트리지움310동 옆,13,2019-10-01 00:08:08,1297,석촌호수교차로(동호 팔각정 앞),1,7,1760.0
3,SPB-06181,2019-10-01 00:00:04,565,옥수역 3번출구,2,2019-10-01 00:30:27,2002,노들역 1번출구,9,30,8460.0
4,SPB-03784,2019-10-01 00:00:04,602,장안동 사거리,9,2019-10-01 00:04:27,627,장안동삼거리 교통섬,1,4,790.0
...,...,...,...,...,...,...,...,...,...,...,...
2341018,SPB-25293,2019-10-31 23:59:49,501,광진구의회 앞,15,2019-11-01 00:42:28,2619,석촌고분역 4번출구,5,42,6070.0
2341019,SPB-08174,2019-10-31 23:59:51,183,하늘채코오롱아파트 건너편,1,2019-11-01 00:06:24,113,홍대입구역 2번출구 앞,22,6,1030.0
2341020,SPB-23917,2019-10-31 23:59:52,3508,화양사거리,6,2019-11-01 00:33:35,602,장안동 사거리,1,30,4660.0
2341021,SPB-17182,2019-10-31 23:59:54,1603,롯데캐슬 102동 코너(월계주유소건너),9,2019-11-01 00:19:39,1601,석계역 문화광장 내 자전거 보관소,15,19,2800.0
2341022,SPB-02983,2019-10-31 23:59:59,1201,가락시장역 3번 출구,3,2019-11-01 00:15:20,2375,수서역 1번출구 앞,8,15,0.0

In [160]:
df.to_csv('./공공자전거 대여이력_2019.10.csv', index = False, encoding ='cp949')

----------------------------------------------------------------

In [161]:
df1 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201911_1.csv', engine = 'python')
df1

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 08:48:31,646,장한평역 1번출구 (국민은행앞),3,2019-11-01 09:01:24,3,중랑센터,7,12,1100.0
1,SPB-16216,2019-11-04 08:38:39,646,장한평역 1번출구 (국민은행앞),2,2019-11-04 08:56:33,3,중랑센터,2,7,1420.0
2,SPB-21097,2019-11-04 08:46:37,646,장한평역 1번출구 (국민은행앞),1,2019-11-04 08:57:35,3,중랑센터,7,10,1020.0
3,SPB-22292,2019-11-05 08:34:59,646,장한평역 1번출구 (국민은행앞),1,2019-11-05 08:45:45,3,중랑센터,2,10,1380.0
4,SPB-07935,2019-11-05 12:29:00,512,뚝섬역 1번 출구 옆,11,2019-11-05 12:39:37,3,중랑센터,7,10,1650.0
...,...,...,...,...,...,...,...,...,...,...,...
799995,SPB-22201,2019-11-28 22:26:11,1203,밀리아나2빌딩 앞,19,2019-11-28 22:29:04,1203,밀리아나2빌딩 앞,18,2,20.0
799996,SPB-22290,2019-11-28 22:29:02,1230,송파중학교 정문,9,2019-11-28 22:36:27,1203,밀리아나2빌딩 앞,2,7,900.0
799997,SPB-15270,2019-11-28 22:16:45,2622,올림픽공원역 3번출구,7,2019-11-28 22:49:52,1203,밀리아나2빌딩 앞,7,32,3320.0
799998,SPB-11405,2019-11-28 22:33:25,1050,둔촌역 3번 출입구,14,2019-11-28 22:58:22,1203,밀리아나2빌딩 앞,6,25,4010.0
799999,SPB-13801,2019-11-28 22:51:31,1288,문정중교 사거리,8,2019-11-28 23:00:10,1203,밀리아나2빌딩 앞,12,8,1370.0

In [162]:
df2 = pd.read_csv('./data/서울특별시 공공자전거 대여정보_201911_2.csv', engine = 'python')
df2

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-04392,2019-11-28 23:07:06,2377,수서역 5번출구 뒤,9,2019-11-28 23:18:44,1203,밀리아나2빌딩 앞,5,11,1980.0
1,SPB-23502,2019-11-28 22:43:23,2613,잠실나들목,3,2019-11-29 00:07:07,1203,밀리아나2빌딩 앞,1,82,11130.0
2,SPB-11498,2019-11-29 00:04:35,1256,문정현대아파트 교차로,6,2019-11-29 00:11:24,1203,밀리아나2빌딩 앞,14,6,800.0
3,SPB-16665,2019-11-29 00:02:57,1278,송파구청 교차로,9,2019-11-29 00:21:18,1203,밀리아나2빌딩 앞,2,18,3730.0
4,SPB-14688,2019-11-29 00:17:16,1230,송파중학교 정문,5,2019-11-29 00:26:36,1203,밀리아나2빌딩 앞,3,9,1370.0
...,...,...,...,...,...,...,...,...,...,...,...
678825,SPB-07983,2019-11-26 08:27:07,2183,동방1교,2,2019-11-26 09:31:27,99999,영남단말기정비,5,59,8520.0
678826,SPB-24906,2019-11-27 08:26:19,2141,미림여고입구 교차로,2,2019-11-27 09:26:19,99999,영남단말기정비,5,59,8680.0
678827,SPB-17861,2019-11-28 08:11:43,2183,동방1교,4,2019-11-28 08:54:39,99999,영남단말기정비,5,40,10570.0
678828,SPB-17173,2019-11-29 08:12:31,2183,동방1교,1,2019-11-29 09:17:29,99999,영남단말기정비,5,64,10560.0
678829,SPB-17714,2019-11-29 11:47:16,99999,영남단말기정비,5,2019-11-29 13:04:17,99999,영남단말기정비,5,76,2420.0

In [163]:
df = df1.append(df2, ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 08:48:31,646,장한평역 1번출구 (국민은행앞),3,2019-11-01 09:01:24,3,중랑센터,7,12,1100.0
1,SPB-16216,2019-11-04 08:38:39,646,장한평역 1번출구 (국민은행앞),2,2019-11-04 08:56:33,3,중랑센터,2,7,1420.0
2,SPB-21097,2019-11-04 08:46:37,646,장한평역 1번출구 (국민은행앞),1,2019-11-04 08:57:35,3,중랑센터,7,10,1020.0
3,SPB-22292,2019-11-05 08:34:59,646,장한평역 1번출구 (국민은행앞),1,2019-11-05 08:45:45,3,중랑센터,2,10,1380.0
4,SPB-07935,2019-11-05 12:29:00,512,뚝섬역 1번 출구 옆,11,2019-11-05 12:39:37,3,중랑센터,7,10,1650.0
...,...,...,...,...,...,...,...,...,...,...,...
1478825,SPB-07983,2019-11-26 08:27:07,2183,동방1교,2,2019-11-26 09:31:27,99999,영남단말기정비,5,59,8520.0
1478826,SPB-24906,2019-11-27 08:26:19,2141,미림여고입구 교차로,2,2019-11-27 09:26:19,99999,영남단말기정비,5,59,8680.0
1478827,SPB-17861,2019-11-28 08:11:43,2183,동방1교,4,2019-11-28 08:54:39,99999,영남단말기정비,5,40,10570.0
1478828,SPB-17173,2019-11-29 08:12:31,2183,동방1교,1,2019-11-29 09:17:29,99999,영남단말기정비,5,64,10560.0
1478829,SPB-17714,2019-11-29 11:47:16,99999,영남단말기정비,5,2019-11-29 13:04:17,99999,영남단말기정비,5,76,2420.0

In [164]:
df = df.sort_values('대여일시', ignore_index = True)
df

,자전거번호,대여일시,대여대여소번호,대여대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-06669,2019-11-01 00:00:00,2255,시민의숲역 1번출구 옆,7,2019-11-01 00:13:54,2206,언남초등학교 앞,1,13,3470.0
1,SPB-07525,2019-11-01 00:00:01,1425,용마문화복지센터,7,2019-11-01 00:08:51,1459,용마한신아파트사거리,8,8,0.0
2,SPB-09584,2019-11-01 00:00:02,1603,롯데캐슬 102동 코너(월계주유소건너),3,2019-11-01 00:19:02,1375,생명의 전화 종합복지관 앞 교차로,13,18,2680.0
3,SPB-19332,2019-11-01 00:00:02,574,아차산역4번출구,8,2019-11-01 00:07:28,3520,광진경찰서,1,7,1390.0
4,SPB-15865,2019-11-01 00:00:04,201,진미파라곤 앞,2,2019-11-01 01:35:42,245,삼성생명 당산사옥 앞,10,95,2630.0
...,...,...,...,...,...,...,...,...,...,...,...
1478825,SPB-11584,2019-11-30 23:59:54,1210,롯데월드타워(잠실역2번출구 쪽),5,2019-12-01 00:43:23,1008,암사역 3번출구(국민은행앞),4,41,5290.0
1478826,SPB-23182,2019-11-30 23:59:54,1008,암사역 3번출구(국민은행앞),2,2019-12-01 00:09:06,1060,천일초교 사거리,2,8,720.0
1478827,SPB-05360,2019-11-30 23:59:55,589,성수역3번출구,8,2019-12-01 00:04:26,585,성수2가1동 공영주차장 인근,1,4,930.0
1478828,SPB-10817,2019-11-30 23:59:57,2239,교대역 6번출구,1,2019-12-01 00:25:30,2217,아크로리버뷰 부지 앞,15,23,2900.0
1478829,SPB-07113,2019-11-30 23:59:58,113,홍대입구역 2번출구 앞,13,2019-12-01 00:06:40,116,일진아이윌아파트 옆,2,6,1050.0

In [165]:
df.to_csv('./공공자전거 대여이력_2019.11.csv', index = False, encoding ='cp949')