In [16]:
import pandas as pd
import numpy as np

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)

mpl.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.family'] = 'Malgun Gothic'


pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [17]:
df1 = pd.read_csv('./일별 대여소별 자전거 거치수량(2020년).csv', encoding = 'cp949')
df2 = pd.read_csv('./일별 대여소별 자전거 거치수량(21년1~5월).csv', encoding = 'cp949')
df = pd.merge(df1, df2, on = ['일시', '대여소번호', '대여소ID', '거치수량'],how='outer')
df

                     일시  대여소번호    대여소ID  거치수량
0       2020-01-01 8:00      7   ST-982    50
1       2020-01-01 8:00     10   ST-484   216
2       2020-01-01 8:00     11   ST-598     0
3       2020-01-01 8:00    101     ST-3    11
4       2020-01-01 8:00    102     ST-4    14
...                 ...    ...      ...   ...
975555  2021-05-31 8:00   4861  ST-2755     4
975556  2021-05-31 8:00   4862  ST-2756     7
975557  2021-05-31 8:00   4863  ST-2728    10
975558  2021-05-31 8:00   9999  ST-1747    11
975559  2021-05-31 8:00  99998    ST-34     4

[975560 rows x 4 columns]

In [18]:
station = pd.read_csv('./대학원/데이터/정리 데이터/공공자전거 대여소 정보(21.06월 기준).csv')
station.head()

,대여소 번호,보관소(대여소)명,자치구,상세주소,위도,경도,설치 시기,LCD 거치대수,QR 거치대수,운영 방식
0,102,망원역 1번출구 앞,마포구,서울특별시 마포구 월드컵로 72,37.555649,126.910629,2015-09-06,20.0,NaN,LCD
1,103,망원역 2번출구 앞,마포구,서울특별시 마포구 월드컵로 79,37.554951,126.910835,2015-09-06,14.0,NaN,LCD
2,104,합정역 1번출구 앞,마포구,서울특별시 마포구 양화로 59,37.550629,126.914986,2015-09-06,13.0,NaN,LCD
3,105,합정역 5번출구 앞,마포구,서울특별시 마포구 양화로 48,37.550007,126.914825,2015-09-06,5.0,NaN,LCD
4,106,합정역 7번출구 앞,마포구,서울특별시 마포구 독막로 4,37.548645,126.912826,2015-09-06,10.0,NaN,LCD

In [19]:
station = station.fillna(0)

In [20]:
station['거치대수'] = station['LCD 거치대수'] + station['QR 거치대수']
station.head()

,대여소 번호,보관소(대여소)명,자치구,상세주소,위도,경도,설치 시기,LCD 거치대수,QR 거치대수,운영 방식,거치대수
0,102,망원역 1번출구 앞,마포구,서울특별시 마포구 월드컵로 72,37.555649,126.910629,2015-09-06,20.0,0.0,LCD,20.0
1,103,망원역 2번출구 앞,마포구,서울특별시 마포구 월드컵로 79,37.554951,126.910835,2015-09-06,14.0,0.0,LCD,14.0
2,104,합정역 1번출구 앞,마포구,서울특별시 마포구 양화로 59,37.550629,126.914986,2015-09-06,13.0,0.0,LCD,13.0
3,105,합정역 5번출구 앞,마포구,서울특별시 마포구 양화로 48,37.550007,126.914825,2015-09-06,5.0,0.0,LCD,5.0
4,106,합정역 7번출구 앞,마포구,서울특별시 마포구 독막로 4,37.548645,126.912826,2015-09-06,10.0,0.0,LCD,10.0

In [21]:
station = station.rename(columns = {'대여소 번호' : '대여소번호', '보관소(대여소)명' : '대여소명'})
station

,대여소번호,대여소명,자치구,상세주소,위도,경도,설치 시기,LCD 거치대수,QR 거치대수,운영 방식,거치대수
0,102,망원역 1번출구 앞,마포구,서울특별시 마포구 월드컵로 72,37.555649,126.910629,2015-09-06,20.0,0.0,LCD,20.0
1,103,망원역 2번출구 앞,마포구,서울특별시 마포구 월드컵로 79,37.554951,126.910835,2015-09-06,14.0,0.0,LCD,14.0
2,104,합정역 1번출구 앞,마포구,서울특별시 마포구 양화로 59,37.550629,126.914986,2015-09-06,13.0,0.0,LCD,13.0
3,105,합정역 5번출구 앞,마포구,서울특별시 마포구 양화로 48,37.550007,126.914825,2015-09-06,5.0,0.0,LCD,5.0
4,106,합정역 7번출구 앞,마포구,서울특별시 마포구 독막로 4,37.548645,126.912826,2015-09-06,10.0,0.0,LCD,10.0
...,...,...,...,...,...,...,...,...,...,...,...
2462,4864,송파사거리,송파구,송파구 송파동 97-2,37.502056,127.110550,2021-04-27,0.0,6.0,QR,6.0
2463,4865,한성백제역 1번출구 뒤,송파구,송파구 방이동 45-4,37.516342,127.115593,2021-04-28,0.0,5.0,QR,5.0
2464,4867,가락대림아파트 앞,송파구,송파구 가락동 94-9,37.500027,127.118431,2021-04-28,0.0,10.0,QR,10.0
2465,4868,레이크 호텔 앞,송파구,송파구 석촌동 158,37.507172,127.101242,2021-05-18,0.0,7.0,QR,7.0
2466,4869,잠실나들목6,송파구,잠실동 24,37.516296,127.084610,2021-06-21,0.0,9.0,QR,9.0

In [22]:
df_new = pd.merge(df, station[['자치구', '대여소번호', '대여소명', '거치대수']], on = '대여소번호')
df_new.head()

                일시  대여소번호 대여소ID  거치수량  자치구        대여소명  거치대수
0  2020-01-01 8:00    102  ST-4    14  마포구  망원역 1번출구 앞  20.0
1  2020-01-02 8:00    102  ST-4    13  마포구  망원역 1번출구 앞  20.0
2  2020-01-03 8:00    102  ST-4    12  마포구  망원역 1번출구 앞  20.0
3  2020-01-04 8:00    102  ST-4    18  마포구  망원역 1번출구 앞  20.0
4  2020-01-05 8:00    102  ST-4     3  마포구  망원역 1번출구 앞  20.0

In [23]:
df_new['일시'] = pd.to_datetime(df_new['일시'])
df_new['년'] = df_new['일시'].dt.year
df_new['월'] = df_new['일시'].dt.month
df_new['일'] = df_new['일시'].dt.day
df_new['시간'] = df_new['일시'].dt.hour

In [24]:
df_new.head()

,일시,대여소번호,대여소ID,거치수량,자치구,대여소명,거치대수,년,월,일,시간
0,2020-01-01 08:00:00,102,ST-4,14,마포구,망원역 1번출구 앞,20.0,2020,1,1,8
1,2020-01-02 08:00:00,102,ST-4,13,마포구,망원역 1번출구 앞,20.0,2020,1,2,8
2,2020-01-03 08:00:00,102,ST-4,12,마포구,망원역 1번출구 앞,20.0,2020,1,3,8
3,2020-01-04 08:00:00,102,ST-4,18,마포구,망원역 1번출구 앞,20.0,2020,1,4,8
4,2020-01-05 08:00:00,102,ST-4,3,마포구,망원역 1번출구 앞,20.0,2020,1,5,8

In [25]:
df_new = df_new.drop(['대여소ID', '거치대수'], axis = 1)
df_new.head()

                   일시  대여소번호  거치수량  자치구        대여소명     년  월  일  시간
0 2020-01-01 08:00:00    102    14  마포구  망원역 1번출구 앞  2020  1  1   8
1 2020-01-02 08:00:00    102    13  마포구  망원역 1번출구 앞  2020  1  2   8
2 2020-01-03 08:00:00    102    12  마포구  망원역 1번출구 앞  2020  1  3   8
3 2020-01-04 08:00:00    102    18  마포구  망원역 1번출구 앞  2020  1  4   8
4 2020-01-05 08:00:00    102     3  마포구  망원역 1번출구 앞  2020  1  5   8

In [26]:
df_new = df_new[['일시', '대여소명', '대여소번호', '년', '월', '일', '시간', '거치수량']]
df_new.head()

                   일시  자치구        대여소명  대여소번호     년  월  일  시간  거치수량
0 2020-01-01 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  1   8    14
1 2020-01-02 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  2   8    13
2 2020-01-03 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  3   8    12
3 2020-01-04 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  4   8    18
4 2020-01-05 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  5   8     3

In [27]:
df_new = df_new.rename(columns = {'거치수량' : '재고량'})
df_new.head()

                   일시  자치구        대여소명  대여소번호     년  월  일  시간  재고량
0 2020-01-01 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  1   8   14
1 2020-01-02 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  2   8   13
2 2020-01-03 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  3   8   12
3 2020-01-04 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  4   8   18
4 2020-01-05 08:00:00  마포구  망원역 1번출구 앞    102  2020  1  5   8    3

In [29]:
df_new = df_new[df_new['대여소명'] == '롯데월드타워(잠실역2번출구 쪽)']
df_new.reset_index(drop = True)

                     일시  자치구               대여소명  대여소번호     년  월   일  시간  재고량
0   2020-01-01 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2020  1   1   8    1
1   2020-01-02 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2020  1   2   8    4
2   2020-01-03 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2020  1   3   8    7
3   2020-01-04 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2020  1   4   8    6
4   2020-01-05 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2020  1   5   8    2
..                  ...  ...                ...    ...   ... ..  ..  ..  ...
500 2021-05-27 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2021  5  27   8   11
501 2021-05-28 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2021  5  28   8    9
502 2021-05-29 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2021  5  29   8    2
503 2021-05-30 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2021  5  30   8    6
504 2021-05-31 08:00:00  송파구  롯데월드타워(잠실역2번출구 쪽)   1210  2021  5  31   8   24

[505 rows x 9 columns]

In [30]:
df_new.to_excel('./롯데월드타워(잠실역2번출구 쪽) 1년 365일 8시 재고량.xlsx', index = False)

In [76]:
idx = df_new[(df_new['년'] == 2020) & (df_new['월'] == 1)].index
df_new.drop(idx, inplace = True)

In [77]:
idx = df_new[(df_new['년'] == 2020) & (df_new['월'] == 2)].index
df_new.drop(idx, inplace = True)

In [78]:
idx = df_new[(df_new['년'] == 2020) & (df_new['월'] == 3)].index
df_new.drop(idx, inplace = True)

In [79]:
idx = df_new[(df_new['년'] == 2020) & (df_new['월'] == 4)].index
df_new.drop(idx, inplace = True)

In [80]:
idx = df_new[(df_new['년'] == 2020) & (df_new['월'] == 5)].index
df_new.drop(idx, inplace = True)

In [90]:
df_new.reset_index(drop = True, inplace = True)

In [91]:
df_new

        자치구         대여소명  대여소번호     년  월   일  시간  거치대수  재고량
0       마포구   망원역 1번출구 앞    102  2020  6   1   8    20    5
1       마포구   망원역 1번출구 앞    102  2020  6   2   8    20    2
2       마포구   망원역 1번출구 앞    102  2020  6   3   8    20    1
3       마포구   망원역 1번출구 앞    102  2020  6   4   8    20   10
4       마포구   망원역 1번출구 앞    102  2020  6   5   8    20    1
...     ...          ...    ...   ... ..  ..  ..   ...  ...
731470  중랑구   중랑데시앙플렉스 앞   4815  2021  5  31   8     8    2
731471  강서구  이랜드글로벌R&D센터   3801  2021  5  28   8    10    0
731472  강서구  이랜드글로벌R&D센터   3801  2021  5  29   8    10    0
731473  강서구  이랜드글로벌R&D센터   3801  2021  5  30   8    10    1
731474  강서구  이랜드글로벌R&D센터   3801  2021  5  31   8    10    0

[731475 rows x 9 columns]

In [92]:
df_new.to_excel('./1년 365일 8시 재고량.xlsx', index = False)